/*
 * Copyright (c) 2025 OopsClick LLC. All rights reserved.
 * This work is licensed under the O'Saasy License Agreement, a copy of which can be
 * found in the LICENSE file in the root directory of this project or at https://silkbuilder.com/core-license.
 */

/**
 * Returns a Button instance.
 *
 * @class
 * @classdesc
The Button Class provides properties, methods, and events to interface with the HTML tags generated by the [silk:Button](../tags/Button.md) component tag. The **silk:Button** component will instantiate a Button object using the component's ID. Using this object, the developer can interact with the button programmatically.

```xml
<silk:Button id="bt1" label="Click Me" />
<silk:JQcode>
	bt1.on("click", function(){
		silk.alert("I have been clicked!");
	});
</silk:JQcode>
```
 *
 * @constructor
 * @param {String} buttonID - Button's name and unique identifier.
 * @param {Object} options - Object containing the configuration.
 * @param {String} [option.targetPage] - The page to activate if clicked.
 * @param {Boolean} [option.singleClick] - The single click behavior. It is true by default
 * @param {Boolean} [option.autoEnable] - The auto enable status after a click. It is true by default.
 * @param {String} [option.confirmTitle] - The confirmation dialog title.
 * @param {String} [option.confirmMessage] - The confirmation dialog message.
 * @param {String} [option.confirmLabel] - The confirmation dialog button's label.
 * @param {String} [option.confirmIcon] - The confirmation dialog icon.
 * @param {String} [option.toggleList] -The list of comma-separated elements that will be toggled together with the component.
 *
 * @property {Object} $button - jQuery object referencing to the button HTML tag.
 *
 */
var Button = function(buttonID, options){
	
	this.className = "Button";

	if( ifUndefined(options,"")=="" ) options = {};
	var targetPage = ifUndefined( options["targetPage"],"");
	this.singleClick = ifUndefined( options["singleClick"],true);
	this.autoEnable = ifUndefined( options["autoEnable"],true);
	var confirmTitle = ifUndefined( options["confirmTitle"],undefined);
	var confirmMessage = ifUndefined( options["confirmMessage"],undefined);
	var confirmLabel = ifUndefined( options["confirmLabel"],undefined);
	var confirmIcon = ifUndefined( options["confirmIcon"],undefined);
	var toggleList = ifUndefined( options["toggleList"],"");
	
	/* $button : Public Property */
	this.$button = null;
	
	/*
	 * Setting event manager
	 */
	var eventManager = new EventManager();

	/*
	 * Setting toggle manager
	 */
	var toggleManager = new ToggleManager(toggleList);
	
	/**
	 * Load events to respond to the button's interactions. To set an event, use this code: ```Button.on(<eventName>, function(){<code>})```.
	 * @param {String} eventName - The event's name.
	 * @param {function} eventFunction - The function to be triggered.
	 */
	this.on = eventManager.on;
	
	/**
	 * Sets the button's label.
	 * @function
	 * @param {string} label - The text of the new label.
	 */
	this.setLabel = function(label){
		this.$button.find(".silk-button-label").text(label);
	}
	
	/**
	 * Gets the button's label.
	 * @function
	 * @returns {String}
	 */
	this.getLabel = function(){
		return this.$button.find(".silk-button-label").html();
	}
	
	/**
	 * Return true if the button will ask for confirmation.
	 * @return {Boolean}
	 */
	this.getNeedsConfirmation = function(){
		return !(isEmpty(confirmTitle) && isEmpty(confirmMessage) && isEmpty(confirmLabel) && isEmpty(confirmIcon))
	}
	
	/**
	 * Sets the title for the confirmation dialog
	 * @param {String} title - The new title
	 */
	this.setConfirmTitle = function(title){
		confirmTitle = title;
	}

	/**
	 * Get the title of the confirmation dialog.
	 * @returns {String}
	 */
	this.getConfirmTitle = function(){
		return confirmTitle;
	}

	/**
	 * Sets the message for the confirmation dialog.
	 * @param {String} message - The new message
	 */
	this.setConfirmMessage = function(message){
		confirmMessage = message;
	}

	/**
	 * Get the message for the confirmation dialog.
	 * @returns {String}
	 */
	this.getConfirmMessage = function(){
		return confirmMessage;
	};
	
	/**
	 * Sets the button's label for the confirmation dialog.
	 * @param {String} label - The new label
	 */
	this.setConfirmLabel = function(label){
		confirmLabel = label;
	}

	/**
	 * gets the button's label from the confirmation dialog.
	 * @returns {String}
	 */
	this.getConfirmLabel = function(){
		return confirmLabel;
	};
	
	
	/**
	 * Sets the icon for the confirmation dialog
	 * @param {String} icon - The new icon
	 */
	this.setConfirmIcon = function(icon){
		confirmIcon = icon;
	}
	
	/**
	 * Hides or shows the button based on the provided parameter. If the parameter is not provided, it will invert the current display status. If shown, it will be hidden; if hidden, it will be displayed.
	 * @function
	 * @param {boolean} status - True shows and false hides.
	 */
	this.toggle = function(status){
		if( status == undefined ){
			this.$button.toggle();
		}else{
			if( typeof status == "boolean" ){
				this.$button.toggle(status);
			}else{
				this.$button.toggle(callFunction(status));
			}
		}
		
		if( isNotEmpty(toggleList) ) toggleManager.toggle(this.$button.getCSSValue("display") != "none", this.$button);
	}
	
	/**
	 * Hides the button
	 * @function
	 */
	this.hide = function(){
		this.toggle(false)
	};
	
	/**
	 * Shows the button
	 * @function
	 */
	this.show = function(){
		this.toggle(true)
	};
	
	/**
	 * Disables an enabled button. If a parameter is provided, the action will change accordingly. True will disable the button, and false will enable it.
	 * @function
	 * @param {boolean} mode - True disables and false enables.
	 */
	this.setDisable = function(mode){
		if(mode==undefined) mode=true;
		if( callFunction(mode) ){
			this.$button.prop("disabled","disabled");
		}else{
			this.$button.prop("disabled","");			
		}
	};
	
	/**
	 * Enables a disabled button. If a parameter is provided, the action will change accordingly. True will enable the button, and false will disable it.
	 * @function
	 * @param {boolean} mode=true - True enables and false disables
	 */
	this.setEnable = function(mode){
		if(mode==undefined) mode=true;
		if( mode ){
			this.$button.prop("disabled","");
		}else{
			this.$button.prop("disabled","disabled");			
		}
	};
	
	/**
	 * Executes the click event programmatically. This method will ignore the confirmation dialog if configured. This method is executed after the user clicks the button, and a confirmation dialog has not been set up. Ultimately, the confirmation process will also execute this method.
	 * @function
	 */
	this.click = function(){
		
		/**
		 * This event is triggered when the button is clicked. It is created with the ```Button.on("click", function(){})``` method.
		 * @event Button#Event:click
		 */
		eventManager.dispatch("click");
		this.go();
		
	};
	
	/**
	 * Opens the confirmation dialog programmatically and waits for a response. A positive answer will execute the click event.
	 * @function
	 */
	this.confirm = function(){
		
		/**
		 * This event is triggered after the button is clicked but before the click event is called, or the confirmation dialog is open if configured. It is created with the ```Button.on("beforeClick", function(){})``` method. If the set function returns *false,* neither the click event nor the dialog is called.
		 * @event Button#Event:beforeClick
		 */
		if( !ifUndefined(eventManager.dispatch("beforeClick"),true) ){
			return;
		}

		//console.log(">"+confirmTitle);

		silk.confirmation(this, undefined, ifUndefined(confirmTitle,this.getLabel()), confirmMessage, confirmLabel, confirmIcon );
		
	};
	
	/**
	 * Triggers the show method in the targetPage if configured.
	 * @function
	 */
	this.go = function(){
		
		if( targetPage=="" ) return;
		
		var page="";
		if( targetPage.indexOf("(")>-1 ){
			page = targetPage();
		}else{
			page = targetPage;
		}
		
		if(page==undefined) return;
		if(page=="") return;

		window[page].show();
	}
	
	this.initButton = function(){
		
		this.$button = $('#'+buttonID);
		
		/*
		 * Assigned click function to button
		 */
		this.$button.click($.proxy(function(){
			
			/*
			 * Checks if button needs confirmation.
			 * If confirmation is not needed it calls the click method.
			 */
			if( !this.getNeedsConfirmation() ){
				
				/*
				 * Triggers the beforeClick event.
				 * If needs confirmation is setup if executes its own beforeClick call.
				 */
				if( !ifUndefined(eventManager.dispatch("beforeClick"),true) ){
					return;
				}
								
				this.click();
				
				/*
				 * Enforces single click policy
				 */
				if( this.singleClick ){
					this.setDisable(true);
					
					/*
					 * Set a timer to auto enable the button
					 */
					if( this.autoEnable ){
						setTimeout($.proxy(function(){this.setDisable(false);},this),500);
					}
				}
				
				return;	
			} 

			/**
			 * This event is triggered before the button's confirmation dialog is called. This only operates if a confirmation dialog has been set up.
			 * If it returns true or does not return a value, the dialog is displayed. If it returns *false,* the confirmation dialog is ignored and the click event is executed.
			 * This event can also be used to modify the confirmation dialog properties before they are displayed.
			 * It is created with the ```Button.on("validateConfirm", function(){})``` method.
			 * @event Button#Event:validateConfirm
			 */
			if( ifUndefined(eventManager.dispatch("validateConfirm"),true) ){
				this.confirm();
			}else{
				this.click();
			}
			
			/*
			 * Enforces single click policy
			 */
			if( this.singleClick ){
				this.setDisable(true);
				
				/*
				 * Set a timer to auto enable the button
				 */
				if( this.autoEnable ){
					setTimeout($.proxy(function(){this.setDisable(false);},this),500);
				}
			}
			
		},this));

	}

};
