/*
 * Copyright (c) 2025 OopsClick LLC. All rights reserved.
 * This work is licensed under the O'Saasy License Agreement, a copy of which can be
 * found in the LICENSE file in the root directory of this project or at https://silkbuilder.com/core-license.
 */

/** 
 * Returns a ChartJS instance. 
 * @class
 * @classdesc
The ChartJS Class provides properties, methods, and events to interface with the HTML tags generated by the [silk:Chart](../tags/Chart.md) component. This object extends the functionality of the popular Chart.js library (https://www.chartjs.org).

### Data Source

The data is provided by a **silk:DataProvider**, which should contain two columns: one with labels and another with values.

```xml
<silk:Chart id="chart" dataSource="dataDP" labelColumn="state" dataColumn="population" />
<silk:DataProvider id="dataDP" servicePath="..." />
```

### JavaScript Object

SilkBuilder also creates a companion JavaScript object using the [ChartJS](..\js_object\ChartJS.js.md) class to provide JavaScript programmatic interaction. This object will have the same name as the component's ID.

```xml
<silk:JQcode>
	chart.on("click", function(index, value, label){
		silk.alert(label+":"+value);
  });	
</silk:JQcode>
```
 * 
 * 
 * @constructor
 * @param {String} id - Unique identifier.
 * @param {Object} option - Object containing the configuration.
 * @param {String} [option.chartType=bar] - Types: bar, line, pie, and doughnut. The default value is "bar". The chart type is from https://www.chartjs.org/docs/latest/charts/.
 * @param {String} [option.dataSource] - Unique identifier of the dataProvider used to fill the Chart.
 * @param {String} [option.labelColumn] - The name of the column that defines the characters' labels.
 * @param {String} [option.dataColumn] - The name of the column that defines the char's data.
 * @param {String} [option.backgroundColor=#1886C1] - The chart's background color.
 * @param {String} [option.showGrid=true] - Defines if the chart will show a grid.
 * @param {String} [option.showLegend=false] - Defines if the chart will show the legend.
 * @param {String} [option.indexAxis=x] - Sets the chart's index axis.
 * @param {String} [option.tooltip=true] - Defines if the chart will show the tooltips.
 * @param {String} [option.dataLabels=true] - Defines if the chart will show data labels.
 *
 * @property {Object} $target - jQuery object referencing the HTML <div> tag wraping the chart.
 * @property {Object} $canvas - jQuery object referencing chart's canvas.
 * @property {Object} $title - jQuery object referencing chart's title.
 * @property {Object} $chartObject - jQuery object referencing chart's object.
 * @property {Object} config - Object containing the chart configuration.
 *
 */
var ChartJS = function(target, options) {

	this.$target;
	this.$canvas;
	this.$title;
	this.chartObject;

	if (ifUndefined(options, "") == "") options = {};
	var chartType = ifUndefined(options["chartType"], "bar");
	var dataSource = ifUndefined(options["dataSource"], "");
	var labelColumn = ifUndefined(options["labelColumn"], "");
	var dataColumn = ifUndefined(options["dataColumn"], "");
	var backgroundColor = ifUndefined(options["backgroundColor"], "#1886C1");
	var showGrid = ifUndefined(options["showGrid"], true);
	var showLegend = ifUndefined(options["showLegend"], false);
	var indexAxis = ifUndefined(options["indexAxis"], "x");
	var tooltip = ifUndefined(options["tooltip"], false);
	var dataLabels = ifUndefined(options["dataLabels"], true);

	var defaultColor = "1886C1";

	/*
	 * Setting event manager
	 */
	var eventManager = new EventManager();

	/**
	 * Load events to respond to the chartJS's interactions. To set an event, use this code: ```ChartJS.on(<eventName>, function(){<code>})```.
	 * @param {String} eventName - The event's name.
	 * @param {function} eventFunction - The function to be triggered.
	 */
	this.on = eventManager.on;

	var dataObject = {
		labels: [],
		datasets: []
	}

	var datasetArray = new Array();
	if (dataColumn != "") {

		var columnArray = dataColumn.split(",");
		var colorArray = backgroundColor.split(",");

		for (x in columnArray) {
			var dataColumn = columnArray[x].trim();
			var colorColumn = defaultColor;
			if (colorArray.length > x) {
				colorColumn = colorArray[x].trim().split("|");;
			}
			var dataset = new Object();
			dataset["dataColumn"] = dataColumn;
			dataset["backgroundColor"] = colorColumn;
			dataset["data"] = new Array();
			datasetArray.push(dataset);
		}
	}

	this.config = {
		type: chartType,
		data: null,
		options: {
			animation: true,
			indexAxis: indexAxis,
			layout: {
				padding: 20
			},
			plugins: {
				legend: {
					display: showLegend,
					position: "bottom"
				},
				tooltip: {
					enabled: tooltip
				},
				datalabels: {
					display: false
				}
			},
			scales: {
				y: {
					grace: "25%",
					display: showGrid
				},
				x: {
					grace: "25%",
					display: showGrid
				}
			},
			onClick: function(event, chartElements, chart) {
				var index = -1;
				var value = -1;
				var label = "";
				var points = undefined;

				if (chartElements) {
					if (chartElements.length > 0) {
						index = chartElements[0].index;
						value = getNumber(chartElements[0].element.$context.raw);
					} else {
						points = chart.getElementsAtEventForMode(event, 'nearest', { intersect: false }, true);
					}
				} else {
					points = chart.getElementsAtEventForMode(event, 'nearest', { intersect: false }, true);
				}

				if (points != undefined) {
					if (points.length > 0) index = points[0].index;
				}

				label = chart.config._config.data.labels[index];

				/**
				 * This event is triggered when a ChartJS data segment is clicked. Created with the ```ChartJS.on("click", function(index,value,label){})``` method.
				 * @param {Integer} index - The dataSource index providing data for the selected element.
				 * @param {Numeric} value - The numeric value of the selected element.
				 * @param {String} label - The label of the selected element.
				 * @event ChartJS#Event:click
				 */
				eventManager.dispatch("click", index, value, label);

			},
			onResize: $.proxy(function(chart, size) {
				setTimeout($.proxy(function() { this.setTitle(); }, this), 200);

				/**
				 * This event is triggered when a ChartJS gets resized. Created with the ```ChartJS.on("resize", function(size){})``` method.
				 * @param {Object} size - The chart's new size.
				 * @event ChartJS#Event:resize
				 */
				eventManager.dispatch("resize", size);
			}, this)
		}
	};

	if (dataLabels) {
		this.config.options.plugins.datalabels = {
			display: true,
			anchor: "end",
			align: "end",
			formatter: Math.round,
			font: {
				weight: "bold",
				size: 14
			}
		};
	}

	/**
	 * Hides the chart.
	 */
	this.hide = function() {
		this.toggle(false)
	};

	/**
	 * Shows the chart from being hidden.
	 */
	this.show = function() {
		this.toggle(true)
	};

	/**
	 * Hides or shows the chart based on the provided parameter. If the parameter is not provided, it will invert the current display status. If shown, it will be hidden; if hidden, it will be displayed.
	 * @param mode - True shows and false hides.
	 */
	this.toggle = function(mode) {
		this.$target.toggle(mode)
	};

	/**
	 * Sets the Chart's title.
	 * @param title - The chart's title.
	 */
	this.setTitle = function(title) {

		if (!isEmpty(title)) {
			this.$title.html(title);
		}

		if (this.$title.parent().hasClass("silk-chart-middle-title")) {
			if (this.chartObject == undefined) return;
			var boxHeight = this.chartObject.chartArea.height + 40;
			var titleHeight = this.$title.height();
			var titleTop = (boxHeight / 2) - (titleHeight / 2);

			this.$title.parent().css("top", titleTop + "px");
		}

	};

	/**
	 * Loads the data from the dataSource, a **silk:DataProvider**, and generates the chart graphic.
	 */
	this.load = function() {

		/**
		 * This event is triggered before ChartJS loads the data and generates the graphic. Created with the ```ChartJS.on("beforeLoad", function(){})``` method.
		 * @event ChartJS#Event:beforeLoad
		 */
		eventManager.dispatch("beforeLoad");

		try {
			this.chartObject.destroy();
		} catch (err) {
		}

		dataObject.labels = new Array();
		for (x in columnArray) {
			datasetArray[x].data = new Array();
		}

		if (dataSource != "") {
			for (x = 0; x < dataSource.size(); x++) {
				dataObject.labels.push(dataSource.getItemAt(x, labelColumn));
				for (y in datasetArray) {
					var dataColumn = datasetArray[y].dataColumn;
					datasetArray[y].data.push(dataSource.getItemAt(x, dataColumn));
				}
			}
			dataObject.datasets = datasetArray;
		}

		this.config.data = dataObject;

		this.chartObject = new Chart(
			this.$canvas,
			this.config
		);

		/**
		 * This event is triggered after ChartJS has loaded the data and generated the graphic. Created with the ```ChartJS.on("afterLoad", function(){})``` method.
		 * @event ChartJS#Event:afterLoad
		 */
		eventManager.dispatch("afterLoad");

		this.setTitle();

	}

	this.initChart = function() {
		this.$target = $("#" + target);
		this.$canvas = this.$target.find("canvas");
		this.$title = this.$target.find(".silk-chart-title");
	}

};