/*
 * Copyright (c) 2025 OopsClick LLC. All rights reserved.
 * This work is licensed under the O'Saasy License Agreement, a copy of which can be
 * found in the LICENSE file in the root directory of this project or at https://silkbuilder.com/core-license.
 */

/**
 * Returns a Column instance.
 * @class
 * @classdesc
The Column Class provides properties, methods, and events to interface with the HTML tags generated by the [silk:Column](../tags/Column.md) tag.
This Object is used internally by the [silk:Table](../tags/Table.md) component and the [Table](Table.js.md) Class to create a table's columns. It can also be used directly to add columns to a table using JavaScript dynamically.

* @constructor
* @param {String} id - Column's unique identifier
* @param {Object} option - Object configuration.
* @param {Object} [option.title] - The text shown in the column header
* @param {Object} [option.tableID] - The ID of the target table
* @param {Object} [option.template] - HTML template containing the data binding fields.
* @param {Object} [option.width] - The column's width
* @param {Object} [option.align] - Horizontal alignment: left, center, and right.
* @param {Object} [option.valign] - Vertical alignment: top, middle, and bottom
* @param {Object} [option.wrap] - Defines if the text will wrap. True by default.
* @param {Object} [option.rendererFn] - The name of the function that will render the column's content.
* @param {Object} [option.targetPage] - The name of the page, or modal, which will be shown when the column is clicked.
* @param {Object} [option.cssClass] - The CSS class or classes to style the column's content.
* @param {Object} [option.draggable] - Defines if the column's rows can be dragged. False by default.
* @param {Object} [option.ordering] - When set to "true," the column header allows data ordering or sorting.
* @param {Object} [option.inputType] - The input type rendered when the table is in input mode.
* @param {Object} [option.inputMask] - The mask defining the input mode.
* @param {Object} [option.valueColumn] - The name of the data column that will fill the input.
* @param {Object} [option.labelColumn] - The name of the data column used to define the input's label.
* @param {Object} [option.visibleColumn] - This property determines the input's visibility.
* @param {Object} [option.sortColumn] - The column used to sort the dataProvider.
* @param {Object} [option.idColumn] - Defines the input's identifier to be used to extract the entered data.
* @param {Object} [option.cleanIf] - Logic statement indicating the condition in which the column cell should show empty.
* @param {Object} [option.distinct] - The column that will determine the distinct condition.
*/
var Column = function(id, options) {
	this.$th = null;

	var title = ifUndefined(options["title"], "");
	var tableID = ifUndefined(options["tableID"], "");
	var template = ifUndefined(options["template"], "");
	var width = ifUndefined(options["width"], 0);
	var align = ifUndefined(options["align"], "");
	var valign = ifUndefined(options["valign"], "");
	var wrap = ifUndefined(options["wrap"], true);
	var rendererFn = ifUndefined(options["rendererFn"], "");
	var targetPage = ifUndefined(options["targetPage"], "");
	var cssClass = ifUndefined(options["cssClass"], "");
	var draggable = ifUndefined(options["draggable"], false);
	var ordering = ifUndefined(options["ordering"], false);
	var inputType = ifUndefined(options["inputType"], "");
	var inputMask = ifUndefined(options["inputMask"], "");
	var valueColumn = ifUndefined(options["valueColumn"], "");
	var labelColumn = ifUndefined(options["labelColumn"], "");
	var visibleColumn = ifUndefined(options["visibleColumn"], "");
	var sortColumn = ifUndefined(options["sortColumn"], "");
	var idColumn = ifUndefined(options["idColumn"], "");
	var cleanIf = ifUndefined(options["cleanIf"], "");
	var distinct = ifUndefined(options["distinct"], "");

	this.hasInput = inputType != "" || valueColumn != "";

	this.renderer = null;

	/*
	 * Setting event manager
	 */
	var eventManager = new EventManager();

	/**
	 * Load events to respond to the column's interactions. To set an event, use this code: ```Column.on(<eventName>, function(){<code>})```.
	 * @param {String} eventName - The event's name.
	 * @param {function} eventFunction - The function to be triggered.
	 */
	this.on = eventManager.on;

	/**
	 * Returns column's table's id.
	 * @returns {String}
	 */
	this.getTableID = function() {
		return tableID;
	};

	/**
	 * Returns the column's table ID.
	 * @param {String} newTableID - The table's id.
	 */
	this.setTableID = function(newTableID) {
		tableID = newTableID;
	};

	/**
	 * Return the HTML template used to generate the cell text.
	 * @returns {String}
	 */
	this.getTemplate = function() {
		return template;
	}

	/**
	 * Sets the HTML template used to render the cell text.
	 * @param {String} newTemplate - The new HTML template.
	 */
	this.setTemplate = function(newTemplate) {
		template = newTemplate;
	}

	/**
	 * Returns the cell text.
	 * @param {Integer} index - The data provider index.
	 * @param {Object} item - The object with the row structure.
	 */
	this.getData = function(index, item) {
		var data = getTemplateData(template, index, item, this.renderer);

		if (cleanIf != "") {
			if (cleanIf == "empty") {
				if (isEmpty(data)) return "";
			} else {
				cleanIf = cleanIf.replaceAll("?", "'" + data + "'");
				if (eval(cleanIf)) return "";
			}
		}

		return data;
	}

	/**
	 * Returns the Input's HTML to be rendered in the cell.
	 * @param {Integer} index - The data provider index.
	 * @param {Object} item - The object with the row structure.
	 * @param {String} type - The input type
	 * @param {Object} object - An object with custom properties to be stored in the input.
	 */
	this.getInput = function(index, item, type, mask, object) {
		if (!this.hasInput) return this.getData(index, item);

		var objectString = "{}";
		if (object != undefined) objectString = JSON.stringify(object);

		var renderType = "text";
		if (type != undefined) {
			renderType = type;
		} else {
			renderType = inputType;
		}

		var renderMask = "";
		if (mask != undefined) {
			renderMask = mask;
		} else {
			renderMask = inputMask;
		}

		var inputClass = "";
		var value = "";

		var inputID = "";
		if (idColumn != "") {
			inputID = "id='" + item[idColumn] + "' ";
		}

		if (valueColumn != "") {
			value = item[valueColumn];
			if (value == undefined) value = "";
			inputClass = tableID + "-input " + tableID + "-" + valueColumn + "-input";
		}

		var extraClass = "";

		/*
		 * Input type HTML does not need a mask. Mask is removed in case the user entered one.
		 */
		if (renderType == "html") renderMask = "";

		/*
		 * If renderMask is empty the mask is determined by the inputType.
		 */
		if (renderMask == "") {

			/*
			 * Process inputTypes number and interger
			 */
			if (renderType == "number" || renderType.toLowerCase() == "integer") {
				extraClass = "text-right";
				renderMask = "data-mask=\"###,###'###,###\" data-mask-reverse='true'";

				/*
				 * Process inputType decimal
				 */
			} else if (renderType.indexOf("decimal") != -1) {
				extraClass = "text-right";

				var decimals = getNumber(renderType);
				if (decimals == 0) decimals = 2;

				var digits = ("0").repeat(decimals);
				var format = "###,###'###,###." + digits + "D";

				if (isNotEmpty(value)) value = getFormattedValue(getNumber(value, decimals), format);

				renderMask = "data-mask=\"" + format + "\" data-mask-reverse='true'";

				/*
				 * Not recognized inputType set mask to empty
				 */
			} else {
				renderMask = "";
			}

			/*
			 * If renderMask is provided creates create mask template
			 */
		} else {

			renderMask = "data-mask=\"" + renderMask + "\" ";

			if (right(renderMask.trim(), 2) == "D\"") {
				renderMask += " data-mask-reverse='true'";
				extraClass = "text-right";
			}
		}


		var inputWidth = "";
		if (width == 0) {
			inputWidth = "width:fit-content;";
		} else {
			inputWidth = "width:" + width + ";";
		}

		var html = "";

		if (renderType == "textarea") {
			html = "<textarea " + inputID + " " +
				"type='text' " +
				"class='form-control " + extraClass + " " + inputClass + "' " +
				"data-type='" + renderType + "' " +
				"data-column='" + valueColumn + "' " +
				"data-value='" + value + "' " +
				"data-index='" + index + "' " +
				"data-json='" + objectString + "' " +
				"style='" + inputWidth + " display:initial;' " +
				renderMask + " " +
				">" +
				value +
				"</textarea>";

		} else if (renderType == "html") {
			html = "<div " + inputID + " " +
				"contenteditable='true' " +
				"type='html' " +
				"class='form-control " + extraClass + " " + inputClass + "' " +
				"data-type='" + renderType + "' " +
				"data-column='" + valueColumn + "' " +
				"data-value='" + value + "' " +
				"data-index='" + index + "' " +
				"data-json='" + objectString + "' " +
				"style='" + inputWidth + " display:initial; display:block !important; width: 100% !important; height: auto !important;' " +
				renderMask + " " +
				">" +
				value +
				"</div>";

		} else {
			html = "<input " + inputID + " " +
				"type='text' " +
				"class='form-control " + extraClass + " " + inputClass + "' " +
				"value='" + value + "' " +
				"data-type='" + renderType + "' " +
				"data-column='" + valueColumn + "' " +
				"data-value='" + value + "' " +
				"data-index='" + index + "' " +
				"data-json='" + objectString + "' " +
				"style='" + inputWidth + " display:initial;' " +
				renderMask + " " +
				"/>";
		}

		return html;
	}

	/**
	 * Returnt the column's ID. The ID is composed of the table name, an underscore, and the column name. If not provided, the name will be "ht*".
	 * @returns {String}
	 */
	this.getID = function() { return id; };

	/**
	 * Returns the column's title.
	 * @returns {String}
	 */
	this.getTitle = function() { return ifUndefined(title, ""); };

	/**
	 * Sets the column's' title.
	 * @param {String} newTitle - The new title.
	 */
	this.setTitle = function(newTitle) { title = newTitle; };

	/**
	 * Returns the column's width.
	 * @returns {String}
	 */
	this.getWidth = function() { return ifUndefined(width, ""); };

	/**
	 * Sets the column's width. This shoudl use the same width format as CSS styling.
	 * @param {String} newWidth - The new column's width.
	 */
	this.setWidth = function(newWidth) { width = newWidth };

	/**
	 * Returns the column's alignment.
	 * @returns {String}
	 */
	this.getAlign = function() { return ifUndefined(align, ""); };

	/**
	 * Sets the column's alignment. Same value as a CSS styling.
	 * @param {String} newAlign - The new alignment.
	 */
	this.setAlign = function(newAlign) { return align = newAlign; };

	/**
	 * Returns the column's vertical alignment.
	 * @returns {String}
	 */
	this.getValign = function() { return ifUndefined(valign, ""); };

	/**
	 * Sets the column's vertical alignment. Seame value as a CSS styling.
	 * @param {String} newValign - The new vertical alignment.
	 */
	this.setValign = function(newValign) { valign = newValign; };

	/**
	 * Returns the column's wrap condition. It is false by default.
	 * @returns {Boolean}
	 */
	this.getWrap = function() { return ifUndefined(wrap, true); };

	/**
	 * Sets the column's wrap condition. The values are "true" or "false".
	 * @param {Boolean} newWrap - The wrap condition.
	 */
	this.setWrap = function(newWrap) { wrap = newWrap; };

	/**
	 * Returns the page to be shown when the column gets clicked.
	 * @returns {String}
	 */
	this.getTargetPage = function() { return ifUndefined(targetPage, ""); };

	/**
	 * Sets the target page called when the cell is clicked.
	 * @param {String} newTarget - The new target page.
	 */
	this.setTargetPage = function(newTarget) { targetPage = newTarget; };

	/**
	 * Returns the column's CSS class.
	 * @returns {String}
	 */
	this.getCssClass = function() { return ifUndefined(cssClass, ""); };

	/**
	 * Sets the column's CSS class.
	 * @param {String} newClass - The new CSS class.
	 */
	this.setCssClass = function(newClass) { cssClass = newClass; };

	/**
	 * Returns the column's draggable condition.
	 * @returns {Booelan}
	 */
	this.getDraggable = function() {
		if (draggable) {
			return true;
		}
		return false;
	};

	/**
	 * Return the column's ordering condition.
	 * @returns {Boolean}
	 */
	this.getOrdering = function() {
		if (ordering) {
			return true;
		}
		return false;
	};

	/**
	 * Returns the column's input type.
	 * @returns {String}
	 */
	this.getInputType = function() {
		return inputType;
	};

	/**
	 * Returns the column's input mask.
	 * @returns {String}
	 */
	this.getInputMask = function() {
		return inputMask;
	};

	/**
	 * Returns the data provider's column holding the input's value.
	 * @returns {String}
	 */
	this.getValueColumn = function() {
		return valueColumn;
	};

	/**
	 * Returns the data provider's column holding the input's label.
	 * @returns {String}
	 */
	this.getLabelColumn = function() {
		return labelColumn;
	};

	/**
	 * Returns the data provider's column holding the input's visibility.
	 * @returns {String}
	 */
	this.getVisibleColumn = function() {
		return visibleColumn;
	};

	/**
	 * Returns the data provider's column used to sort the table.
	 * @returns {String}
	 */
	this.getSortColumn = function() {
		return sortColumn;
	};

	/**
	 * Returns the column's visible condition. This triggers the "visible" event.
	 * @returns {Boolean}
	 */
	this.getVisible = function(item) {
		if (!eventManager.eventExists("visible")) return true;

		/**
		 * This event is triggered when the column is rendered. If the event's function returns true, the column will be added. If it returns false, it will not be added.
		 * Created with the ```Column.on("visible", function(item){})``` method.
		 * @event Column#Event:visible
		 */
		var visible = eventManager.dispatch("visible", item);
		return ifUndefined(visible, true);

	};

	/**
	 * Sets the column to check distinct condition.
	 * @param {String} columm - The column to check.
	 */
	this.setDistinct = function(column) {
		distinct = column;
	};

	/**
	 * Return the column used to check the distinct condition.
	 */
	this.getDistinct = function() {
		return distinct;
	};

	/**
	 * Shows a page using the "targetPage" property.
	 */
	this.showPage = function() {
		if (!isEmpty(targetPage)) window[targetPage].show();
	};

	this.initColumn = function() {

		if (rendererFn != "") {
			this.renderer = window[rendererFn];
		}

		if (id == "") return;
		this.$th = $("#" + id);
	}

}
