/*
 * Copyright (c) 2025 OopsClick LLC. All rights reserved.
 * This work is licensed under the O'Saasy License Agreement, a copy of which can be
 * found in the LICENSE file in the root directory of this project or at https://silkbuilder.com/core-license.
 */

/**
 * Returns a DataProvider instance. 
 * @class
 * @classdesc
The Form Class provides properties, methods, and events to interface with the code generated by the [silk:Form](../tags/Form.md) tag. The **silk:Form** component will instantiate a Form object using the component's ID. Using this object, the developer can interact with the button programmatically.
 *
 * @constructor
 * @param {String} id - Unique identifier.
 * @param {Object} options - Object containing the DataProvider configuration options.
 * @param {Boolean} [options.startMode=false] - Starting mode. True is editing, and false is read-only.
 * @param {Boolean} [options.dialog=true] - Sets the dialog used. If *false*, the automatic generation of the submit button is disabled.
 * @param {String} [opsions.dataSource] - The name of the Table or DataProvider.
 * @param {String} [options.insertBt] - The name of the button used to activate an insert action.
 * @param {String} [options.updateBt] - The name of the button used to activate an update action.
 * @param {String} [options.deleteBt] - The name of the button used to activate a delete action.
 * @param {String} [options.cancelBt] - The name of the button used to activate a cancel action.
 * @param {String} [options.submitBt] - The name of the button used to activate a submit action.
 * @param {String} [options.dialogTitle] - The title of the dialog box.
 * @param {String} [options.insertTitle] - The title for the insert action.
 * @param {String} [options.updateTitle] - The title for the update action.
 * @param {String} [options.deleteTitle] - The title for the delete action.
 * @param {String} [options.insertMessage] - The message for the insert action.
 * @param {String} [options.updateMessage] - The message for the update action.
 * @param {String} [options.deleteMessage] - The message for the delete action.
 * @param {String} [options.confirmTitle] - The confirmation dialog title.
 * @param {String} [options.confirmMessage] - The confirmation dialog message.
 * @param {String} [options.confirmLabel] - The confirmation dialog button's label.
 * @param {String} [options.confirmIcon] - The confirmation dialog icon.
 * @param {String} [options.confirmTarget] - Sets which actions will trigger the confirmation dialog.
 * @param {String} [options.autoFocus] - Set if the first input will be auto focused.
 
 * @property {Object} $form - jQuery object referencing the form HTML tag.
 * @property {Boolean} mask - Indicates if the form's mask is active.
 * @property {Object} insertBt - The name of the Button object to initiate an insert if provided.
 * @property {Object} updateBt - The name of the Button object to initiate an update if provided.
 * @property {Object} deleteBt - The name of the Button object to initiate a delete if provided.
 * @property {Object} cancelBt - The name of the Button object to initiate a cancel if provided.
 * @property {Object} submitBt - The name of the Button object to initiate a submit if provided.
 */
var Form = function(id, options) {
	this.className = "form";

	if (ifUndefined(options, "") == "") options = {};

	var startMode = ifUndefined(options["startMode"], false);
	var dialog = ifUndefined(options["dialog"], true);
	var dataSource = ifUndefined(options["dataSource"], null);
	this.insertBt = ifUndefined(options["insertBt"], null);
	this.updateBt = ifUndefined(options["updateBt"], null);
	this.deleteBt = ifUndefined(options["deleteBt"], null);
	this.cancelBt = ifUndefined(options["cancelBt"], null);
	this.submitBt = ifUndefined(options["submitBt"], null);

	var dialogTitle = ifUndefined(options["dialogTitle"], "");

	var insertTitle = ifUndefined(options["insertTitle"], "Adding");
	var updateTitle = ifUndefined(options["updateTitle"], "Editing");
	var deleteTitle = ifUndefined(options["deleteTitle"], "Deleting");

	var insertMessage = ifUndefined(options["insertMessage"], "Created");
	var updateMessage = ifUndefined(options["updateMessage"], "Edited");
	var deleteMessage = ifUndefined(options["deleteMessage"], "Deleted");

	var toggleList = ifUndefined(options["toggleList"], "");
	var toggleEdit = ifUndefined(options["toggleEdit"], "");

	var autoFocus = ifUndefined(options["autoFocus"], true);

	var cancelBtLabel = "Cancel";
	var submitBtLabel = "Submit"

	var confirmTitle = ifUndefined(options["confirmTitle"], "");
	var confirmMessage = ifUndefined(options["confirmMessage"], "");
	var confirmLabel = ifUndefined(options["confirmLabel"], "");
	var confirmIcon = ifUndefined(options["confirmIcon"], "");
	var confirmTarget = ifUndefined(options["confirmTarget"], "");

	var enableStatus = true;

	if (isNotEmpty(window.globalTranslationTags)) {
		if (insertTitle == "Adding") insertTitle = globalTranslationTags["global-form-adding"];
		if (updateTitle == "Editing") updateTitle = globalTranslationTags["global-form-editing"];
		if (deleteTitle == "Deleting") deleteTitle = globalTranslationTags["global-form-deleting"];
		if (insertMessage == "Created") insertMessage = globalTranslationTags["global-form-created"];
		if (updateMessage == "Edited") updateMessage = globalTranslationTags["global-form-edited"];
		if (deleteMessage == "Deleted") deleteMessage = globalTranslationTags["global-form-deleted"];

		cancelBtLabel = globalTranslationTags["global-button-cancel"];
		submitBtLabel = globalTranslationTags["global-button-submit"];

	}

	/**
	 * Returns the component's unique identifier.
	 */
	this.getID = function() {
		return id;
	}

	/*
	 * Setting event manager
	 */
	var eventManager = new EventManager();

	/**
	 * Load events to respond to the Form's interactions. To set an event, use this code: ```Form.on(<eventName>, function(){<code>})```.
	 * @param {String} eventName - The event's name.
	 * @param {function} eventFunction - The function to be triggered.
	 */
	this.on = eventManager.on;

	/*
	 * Setting toggle manager for List
	 */
	var toggleManager = new ToggleManager(toggleList, id);

	/*
	 * Setting toggle manager for edit
	 */
	var toggleEditManager = new ToggleManager(toggleEdit, id);


	/**
	 * Hides or shows the form based on the provided parameter.
	 * @function
	 * @param {boolean} status - True shows and false hides.
	 */
	this.toggle = function(status) {
		if (status == undefined) {
			this.$form.toggle();
		} else {
			if (typeof status == "boolean") {
				this.$form.toggle(status);
			} else {
				this.$form.toggle(callFunction(status));
			}
		}
		if (isNotEmpty(toggleList)) toggleManager.toggle(this.$form.getCSSValue("display") != "none", this.$form);
	}

	/**
	 * Hides the form.
	 * @function
	 */
	this.hide = function() {
		this.toggle(false)
	};

	/**
	 * Shows the form.
	 * @function
	 */
	this.show = function() {
		this.toggle(true)
	};

	/**
	 * Returns the list of events loaded.
	 * @returns {Array}
	 */
	this.getEventList = function() {
		return eventManager.getList();
	}

	this.$form;
	this.mask = true;

	var _action = "none";

	var pageID = undefined;
	var isModal = false;

	var $formBar = null;
	var $formBarTitle = null;
	var $pageBar = null;

	var inputs = new Array();
	var mode = false;

	/*
	 * The object holding the select record form the dataSource
	 */
	var item = new Object();

	/*
	 * Interval checking if the submit button should be enable of disable.
	 */
	var submitCheckInterval;


	/*
	 * Method used by Inputs to trigger the parent Form's change event.
	 * @param {Input} Input = The Input object triggering the change event.
	 */
	this.dispatchOnChange = function(input) {
		/**
		 * This event is triggered when the input's value changes. Created with the ```Form.on("change", function(input){})``` method. The function's parameter is the input that triggered the change.
		 * @param {Input} Input - The Input object triggering the change event.
		 * @event Form#Event:change
		 */
		eventManager.dispatch("change", input);
	}

	/**
	 * Adds an input object to the input array.
	 * 
	 * @param {Input} input - The Input object to add.
	 */
	this.pushInput = function(input) {
		inputs.push(input);
	}

	/**
	 * Sets the action form's action that the form will execute. This could be: "insert", "update", "delete", or "none" if set to read-only mode. The form's action is set by clicking the set action buttons.
	 * @param {String} action - This could be "insert", "update", "delete", or "none".
	 */
	this.setAction = function(action) {
		_action = action;
	}

	/**
	 * Returns the form's action.	
	 */
	this.getAction = function() {
		return _action;
	}

	/**
	 * Returns array containing the form's inputs added using the method *puchInput*.
	 * @returns {Array}
	 */
	this.getInputs = function() {
		return inputs;
	}

	/**
	 * Returns the ID of the Page or Modal hosting the Form. Otherwise, it returns undefined.
	 * @returns {String} 
	 */
	this.getPage = function() {
		return pageID;
	}

	/**
	 * Enables the form's input and buttons. If the parameter is provided, *true* enables, and *false* disables.
	 * @param {Boolean} status - (Optional) boolean value;
	 */
	this.setEnable = function(status) {
		if (status == undefined) status = true;
		for (x in inputs) {
			this[inputs[x]].setEnable(status);
		}

		if (this.insertBt != null) this.insertBt.setEnable(status);
		if (this.updateBt != null) this.updateBt.setEnable(status);
		if (this.deleteBt != null) this.deleteBt.setEnable(status);
		if (this.cancelBt != null) this.cancelBt.setEnable(status);
		if (this.submitBt != null) this.submitBt.setEnable(status);

		enableStatus = status;
	}

	/**
	 * Disables the form's input and buttons. If the parameter is provided, *true* disables, and *false* enables.
	 * @param {Boolean} status - (Optional) boolean value;
	 */
	this.setDisable = function(status) {
		if (status == undefined) status = true;
		for (x in inputs) {
			this[inputs[x]].setEnable(!status);
		}

		if (this.insertBt != null) this.insertBt.setEnable(!status);
		if (this.updateBt != null) this.updateBt.setEnable(!status);
		if (this.deleteBt != null) this.deleteBt.setEnable(!status);
		if (this.cancelBt != null) this.cancelBt.setEnable(!status);
		if (this.submitBt != null) this.submitBt.setEnable(!status);

		enableStatus = !status;
	};

	/**
	 * Returns true is the form is enable
	 * @return {Boolean}
	 */
	this.getEnable = function() {
		return enableStatus;
	};

	/**
	 * Returns true is the form is disable
	 * @return {Boolean}
	 */
	this.getDisable = function() {
		return !enableStatus;
	};

	/**
	 * Returns the select item in the Table or DataProvider.
	 * @returns {Object}
	 */
	this.getSelectedItem = function() {
		if (dataSource == null) return new Object();
		return dataSource.getSelectedItem();
	}

	/**
	 * Set the Form mode. *True* activates the inputs for data entry, while *false* activates the inputs for read-only. This method will also hide or show the interaction buttons accordingly. If configured, the dialog window will also show when set to *true*.
	 * If the parameter is not provided, it is set to read-only.
	 * 
	 * @param {Boolean} [viewMode=false] - The mode to set.
	 */
	this.setMode = function(viewMode) {

		/*
		 * Verifies that a row is selected.
		 * If selectRow is false the dataSource does not have records.
		 */
		var selectedRow = true;
		if (dataSource != null) {
			if (dataSource.selectedIndex == -1) selectedRow = false
		}

		/*
		 * Sets the form's vew mode. If mode is not provided it is set to false.
		 */
		if (viewMode == undefined) {
			mode = false;
		} else {
			mode = viewMode;
		}

		/*
		 * Sets the dialog's title and icon based on the action.
		 */
		var iconHtml = ""
		if (this.getAction() == "insert") {
			if (this.insertBt != null) {
				if (this.insertBt.$button.find('.silk-button-icon').length > 0) iconHtml = this.insertBt.$button.find('.silk-button-icon')[0].outerHTML + " ";
			}
			$formBarTitle.html(iconHtml + insertTitle);
		} else if (this.getAction() == "update") {
			if (this.updateBt != null) {
				if (this.updateBt.$button.find('.silk-button-icon').length > 0) iconHtml = this.updateBt.$button.find('.silk-button-icon')[0].outerHTML + " ";
			}
			$formBarTitle.html(iconHtml + updateTitle);
		} else if (this.getAction() == "delete") {
			if (this.deleteBt != null) {
				if (this.deleteBt.$button.find('.silk-button-icon').length > 0) iconHtml = this.deleteBt.$button.find('.silk-button-icon')[0].outerHTML + " ";
			}
			$formBarTitle.html(iconHtml + deleteTitle);
		} else {
			$formBarTitle.text("");
		}


		/**
		 * This event is triggered before the mode changes are applied. Created with the ```Form.on("beforeModeChange", function(mode){})``` method. The mode changes between read-only (false) and editable (true);
		 * @event Form#Event:beforeModeChange
		 */
		eventManager.dispatch("beforeModeChange", mode);

		if (pageID != undefined && this.mask) window[pageID].mask(mode);

		if (this.insertBt != null) {
			/**
			 * This event is triggered before the insert button's visibility changes. It is created with the ```Form.on("showInsertBt", function(){})``` method. If the function returns *false* the button is not displayed.
			 * @event Form#Event:showInsertBt
			 */
			const showInsertBt = ifUndefined(eventManager.dispatch("showInsertBt"), true);
			this.insertBt.toggle(!mode && showInsertBt);
		}

		/*
		 * Determines if elements should show when row is the tree root.
		 */
		var isTreeData = false;
		var noRoot = false;
		var deleteBranch = false;
		var showOnTree = true; // Default true any operation except if changed.

		if (dataSource != null) {
			isTreeData = dataSource.isTreeData();
			if (dataSource["getNoRoot"] != undefined) noRoot = dataSource.getNoRoot();
			if (isTreeData && !noRoot) {
				showOnTree = dataSource.selectedIndex > 0
			}
			if (isTreeData) {
				deleteBranch = dataSource.getDeleteBranch();
			}
		}

		if (this.updateBt != null) {
			/**
			 * This event is triggered before the update button's visibility changes. Created with the ```Form.on("showUdatetBt", function(){})``` method. If the function returns *false* the button is not displayed.
			 * @event Form#Event:showUdatetBt
			 */
			const showUdatetBt = ifUndefined(eventManager.dispatch("showUdatetBt"), true);
			this.updateBt.toggle(!mode && showOnTree && showUdatetBt && selectedRow);
		}

		if (this.deleteBt != null) {
			var hasChildren = 0;
			if (dataSource != null) hasChildren = dataSource.getSelectedItem()._childrenCount;
			if (hasChildren == undefined) hasChildren = 0;

			/**
			 * This event is triggered before the delete button's visibility changes. Created with the ```Form.on("showDeleteBt", function(){})``` method. If the function returns *false* the button is not displayed.
			 * @event Form#Event:showDeleteBt
			 */
			const showDeleteBt = ifUndefined(eventManager.dispatch("showDeletetBt"), true);

			this.deleteBt.toggle(
				!mode &&
					showOnTree &&
					(deleteBranch) ? true : hasChildren == 0 &&
					showDeleteBt &&
				selectedRow
			);
		}

		if (isTreeData) {
			if (mode) {
				this.$form.show();
			} else {
				this.$form.toggle(showOnTree);
			}
		}

		if (mode) {
			/*
			 * If dialog is false it activates the inputs mode and cancel the process to avoid showing the dialog bar.
			 */
			if (dialog) {
				if (isModal) {
					if ($pageBar != null) $pageBar.css("visibility", "hidden");
				} else {
					if ($pageBar != null) $pageBar.hide();
				}
				if ($formBar != null) $formBar.css("display", "");
			}

			if (this.cancelBt != null) this.cancelBt.$button.show();
			if (this.submitBt != null) {
				this.submitBt.$button.show();
				disableSubmit(true, this);
				if (this.getAction() == "delete" || inputs.length == 0) {
					submitCheckInterval = setInterval($.proxy(function() { disableSubmit(false, this); }, this), 1000);
				} else {
					submitCheckInterval = setInterval($.proxy(function() { activateSubmit(this) }, this), 500);
				}
			}
		} else {
			/*
			 * If dialog is false it activates the inputs mode and cancel the process to avoid showing the dialog bar.
			 */
			if (dialog) {
				if (isModal) {
					if ($pageBar != null) $pageBar.css("visibility", "visible");
				} else {
					if ($pageBar != null) $pageBar.show();
				}
				if ($formBar != null) $formBar.hide();
			}

			if (this.cancelBt != null) this.cancelBt.$button.hide();
			if (this.submitBt != null) {
				this.submitBt.$button.hide();
				clearInterval(submitCheckInterval);
			}

			/*
			 * If the data source does not have records is clears form.
			 */
			if (dataSource != null) {
				if (dataSource.length() == 0) {
					if (isModal) window[pageID].goBack();
					this.clean();
				}
			}

		}

		if (this.getAction() == "delete") mode = false;
		this.setInputMode(mode)

		if (pageID != undefined) {
			window[pageID].resize();
		}

		/*
		 * Hides of show elements during editing of show element during read-only mode.
		 */
		toggleEditManager.toggle(!mode);

		/**
		 * This event is triggered after the mode has changed. Created with the ```Form.on("afterModeChange", function(mode){})``` method. The mode changes between read-only (false) and editable (true);
		 * This event is similar to the *modeChange* event, and it is added for coding and reference convenience.
		 * @event Form#Event:afterModeChange
		 */
		eventManager.dispatch("afterModeChange", mode);

		/**
		 * This event is triggered after the mode has changed. Created with the ```Form.on("modeChange", function(mode){})``` method. The mode changes between read-only (false) and editable (true);
		 * This event is similar to the *afterModeChange* event, and it is added for coding and reference convenience.
		 * @event Form#Event:modeChange
		 */
		eventManager.dispatch("modeChange", mode);

		/*
		 * Sets the first visible input into focus
		 */
		if (mode && autoFocus) {
			let firstInput = null;
			for (x in inputs) {
				/*
				 * Set the first input to apply auto focus.
				 */
				if (firstInput == null && this[inputs[x]].getType() != "hidden" && mode && autoFocus) {
					if (this[inputs[x]].getVisible()) firstInput = this[inputs[x]];
				}
			}
			if (firstInput != null) {
				setTimeout(function() {
					//console.log(firstInput);
					firstInput.focus();
				}, 500);
			}
		}

	}

	/**
	 * Returns the form's mode.
	 * @returns {Boolean}
	 */
	this.getMode = function() {
		return mode;
	}

	/**
	 * It changes the inputs' mode without affecting the form's mode. By default, it sets the previous values to restart the monitoring of input changes. If the property setPreviousData is set to *false*, the input will preserve the previous data and keep the changed condition after setting the new mode.
	 * @param {Boolean} mode=false - The logic value
	 * @param {Boolean} setPreviousData=true - The logic value
	 */
	this.setInputMode = function(mode, setPreviousData) {
		for (x in inputs) {
			this[inputs[x]].setMode(mode, setPreviousData);
		}
	}

	/*
	 * List of input types which are editable
	 */
	var submitTypeList = "text,textarea,code,html,sql,xml,js,xhtml,date,time,datetime,select,numeric,integer,decimal,checkbox,button,options,radio,password,file,email";

	/*
	 * Function to run to decide if the submit button should be active.
	 * This should return a boolean
	 */
	var disableSubmit = function(mode, that) {
		if (enableStatus) {
			that.submitBt.setDisable(mode);
		} else {
			that.submitBt.setDisable();
		}
	};

	/*
	 * Activates the Submit button if requirements are met.
	 */
	var activateSubmit = function(that) {

		var filled = true;
		var required = false;

		//var countChange = 0;
		for (x in inputs) {
			var input = that[inputs[x]];
			if (submitTypeList.indexOf(input.getType()) > -1) {
				if (input.hasChanged()) filled = false;
				if (input.getRequired()) {
					var value = input.getValue();
					if (value == null) value = "";
					if (value == undefined) value = "";
					if (value == "") required = true;
				}
			}
		}

		/**
		 * This event is triggered before the submit button disable or enable condition changes.  Created with the ```Form.on("submitBtActivation", function(){})``` method. If the function returns *false*, the button is disabled.
		 * When the form is set for data entry, the submit button is displayed as disabled. It changes to enabled when an input changes. This default behaviour can be modified with this event. 
		 * @event Form#Event:submitBtActivation
		 */
		var disable = !ifUndefined(eventManager.dispatch("submitBtActivation"), true)

		if (disable == undefined) {
			disable = filled || required;

		} else {
			disable = disable || filled || required;
		}

		disableSubmit(disable, that);

	}

	/**
	 * It loads the data from the data source into the form's inputs, sets the mode to false, and triggers events. If the data source records do not have data, the form's inputs are cleaned.
	 */
	this.load = function() {

		if (!enableStatus) this.setEnable();

		if (dataSource == null) return;

		/**
		 * This event is triggered before the form loads the data from the data source. It is created with the ```Form.on("beforeLoad", function(action){})``` method.
		 * @param {String} action - The executed action.
		 * @event Form#Event:beforeLoad
		 */
		eventManager.dispatch("beforeLoad", this.getAction())

		var pkColumn = dataSource.getPkColumn();

		/*
		 * Add primary key input hidden is not added
		 */
		if (inputs.indexOf(pkColumn) == -1) {
			this[pkColumn] = new Input(id + "_" + pkColumn, "hidden", "", {
				columnID: pkColumn,
				target: id,
				form: window[id]
			});
			this.pushInput(pkColumn);
		}

		// Scope setup to 0: Force to send
		if (this[pkColumn] != undefined) this[pkColumn].setScope(0);

		if (dataSource.length() == 0) {

			this.clean();

		} else {

			item = dataSource.getSelectedItem();

			if (this.getAction() == "none") {
				this.fillInputValues();
				this.setMode(false);
			} else {
				this.doCancel();
			}

		}

		/**
		 * This event is triggered after the form loads the data from the data source and the inputs have been set. It is created with the ```Form.on("afterLoad", function(){})``` method.
		 * @param {String} action - The executed action.
		 * @event Form#Event:afterLoad
		 */
		eventManager.dispatch("afterLoad", this.getAction())

	};

	/*
	 * Process had an error
	 */
	this.errorHandle = function() {
		/**
		 * This event is triggered after an error has occurred while loading the data. It is created with the ```Form.on("error", function(action){})``` method.
		 * @param {String} action - The action
		 * @event Form#Event:error
		 */
		eventManager.dispatch("error", this.getAction())
		this.setAction("none")
		this.doCancel();
	}


	/**
	 * It loads the data from the data source into the form's inputs only. This is used by the *load* method.
	 */
	this.fillInputValues = function() {
		for (x in inputs) {
			this[inputs[x]].setValue(item[inputs[x]]);
		}
	}


	/**
	 * Cleans the form's input values
	 */
	this.clean = function() {
		this.setAction("none");
		if (this.updateBt != undefined) this.updateBt.$button.hide();
		if (this.deleteBt != undefined) this.deleteBt.$button.hide();
		for (x in inputs) {
			this[inputs[x]].setValue("");
		}

	}

	//------------------------------------------------------------

	/**
	 * Returns and *operationObject* that the DataProvider will submit to the server. The *action* parameter receives "insert", "update", or "delete".
	 * @param {Boolean} action - The action to process
	 * @returns {Object}
	 */
	this.getOperationList = function(action) {
		var operationObject = new Object();
		operationObject["action"] = action;

		var inputArray = new Array();
		for (x in inputs) {

			var column = inputs[x];
			var input = this[column];
			var scope = input.getScope();

			/*
			 * Scope Values
			 *  
			 * 0 : Force send
			 * 1 : if changed go to DB (Default)
			 * 2 : if changed go to DP only
			 * 3 : Stay in form
			 */

			if (scope != 0) {
				if (scope == 3) continue;
				//if( !input.checkEditable() ) continue;
				if (!input.hasChanged()) continue;
			}

			var obj = new Object();
			obj["column"] = column;
			obj["value"] = input.getValue();
			if (scope == 2) obj["scope"] = "2";
			inputArray.push(obj);

			/*
			 * Adding other related elements only for the dataProvider
			 */
			if (input.getType() == "select") {
				var segments = input.getLinkedColumns().split(",");
				for (x in segments) {
					segments[x] = segments[x].trim();
					if (segments[x] == "") continue;
					var columns = segments[x].split(":");
					if (columns.length == 1) columns.push(columns[0]);
					try {
						obj = new Object();
						obj["column"] = columns[0].trim();
						obj["value"] = input.getItem(columns[1].trim());
						obj["scope"] = "2";
						inputArray.push(obj);
					} catch (error) { }
				}
			}

		}

		operationObject["columnList"] = inputArray;

		var operationList = new Array();
		operationList.push(operationObject);

		return operationList;
	}

	/**
	 * Sets the dialog title
	 * @param {String} title - The title text
	 */
	this.setDialogTitle = function(title) {
		if ($formBarTitle != null) $formBarTitle.text(title);
	}

	//------------------------------------------------------------

	/**
	 * Sets the Form to initiate an insert operation. This operation is executed when clicking the form's insert button, if set.
	 */
	this.setInsert = function() {
		if (this.getAction() != "none") return;
		if (pageID != undefined) window[pageID].show();
		this.clean();
		this.setAction("insert");
		this.setMode(true);
	}

	/**
	 * Sets the Form to initiate an update operation. This operation is executed when clicking the form's update button, if set.
	 */
	this.setUpdate = function() {
		if (this.getAction() != "none") return;
		if (pageID != undefined) window[pageID].show();
		this.setAction("update");
		this.setMode(true);
	}

	/**
	 * Sets the Form to initiate a delete operation. This operation is executed when clicking the form's delete button, if set.
	 */
	this.setDelete = function() {
		if (this.getAction() != "none") return;
		if (pageID != undefined) window[pageID].show();
		this.setAction("delete");
		this.setMode(true);
	}

	/**
	 * Operates a cancel operation. This operation is executed when clicking the form's cancel button, if set.
	 * @param {Boolean} buttonClicked - Indicates that the call is from a button being clicked. Only use interanlly.
	 */
	this.doCancel = function(buttonClicked) {
		if (!buttonClicked) buttonClicked = false;
		if (this.getAction() == "none") return;
		// Any action leads to close the form and return to parent list
		// If the page is modal it closes after an insert and delete.
		if (pageID != undefined) {
			if (!isModal || !buttonClicked) window[pageID].goBack();
		}
		this.setAction("none");
		this.setMode(false);
		this.fillInputValues();
		this.setInputMode(false);

	}


	this.validate = function() {
		var inputsErrors = new Array();
		for (x in inputs) {
			if (this[inputs[x]].validate() > 0) {
				inputsErrors.push(this[inputs[x]].getLabel());
			}
		}
		return inputsErrors;
	}

	/**
	 * Operates the data submission process. This operation is executed when clicking the form's submit button, if set.
	 * @param {String} action - The action to be executed.
	 */
	this.doSubmit = function(action) {
		/*
		 * Stop if action is equals to "none" 
		 */
		if (this.getAction() == "none" && dataSource != null) return;

		/**
		 * This event is triggered before the form's data is validated for submission. Use this event to apply changes or run operations before the form's input validation. If it returns false, the process is canceled. Created with the ```Form.on("beforeSubmit", function(){})``` method.
		 * @event Form#Event:beforeSubmit
		 */
		if (!ifUndefined(eventManager.dispatch("beforeSubmit"), true)) return;

		/*
		 * Collects and counts input errors.
		 */
		var inputsErrorReported = this.validate();

		if (inputsErrorReported.length == 0) {
			/*
			 * No errors found
			 */

			/**
			 * This event is triggered before the form's data has been validated and is ready to be submitted for processing. The event *beforeSubmit* is triggered before this event.
			 * If the function returns *false* the process is canceled. Created with the ```Form.on("submit", function(){})``` method.
			 * @event Form#Event:submit
			 */
			if (!ifUndefined(eventManager.dispatch("submit"), true)) return;

			/*
			 * Submits the form's data fo the dataSource.
			 * If the transaction is sucessful the form mode will change to read-only.
			 */
			if (dataSource != null) {
				/*
				 * Disables form's inputs and buttons before submitting.
				 */
				this.setDisable();

				/*
				 * Calls DataProvider action.
				 */
				dataSource.callAction(this.getOperationList(this.getAction()));
			}
		} else {

			/*
			 * Errors found
			 */

			/**
			 * This event is triggered when the form's inputs have errors.  It is created with the ```Form.on("formErrors", function(){})``` method. The function receives an array containing the labels of the inputs needing correction.
			 * When data has to be corrected, the form's inputs will show a warning border color. The developer can use this event to add extra guiding messages.
			 * @param {Array} inputList - The list of iputs with errors.
			 * @event Form#Event:formErrors
			 */
			eventManager.dispatch("formErrors", inputsErrorReported);
		}
	}

	//------------------------------------------------------------

	/**
	 * Retursn the form inputs' values as an JavaScript Object's properties.
	 * @returns {Object} - An Oject with the form's inputs as properties
	 */
	this.getObject = function() {
		let returnObject = {};
		for (let item of this.getOperationList()[0].columnList) {
			returnObject[item.column] = item.value;
		}
		return returnObject;
	};

	/**
	 * Return the form input's values as a JSON String.
	 * @returns {JSON} - A JSON String 
	 */
	this.getJSON = function() {
		return JSON.stringify(this.getObject());
	};

	/**
	 * Excutes a jQuesr ajax post/json call to the provided URL. The handle function received the parameter result, which can be true or false, and the response data.
	 * @param {String} serviceURL - The URL to the target service
	 * @param {Function} handleFunction - The functin which will received the response.
	 */
	this.post = function(serviceURL, handleFunction) {
		postToService(serviceURL, this.getObject(), handleFunction, this);
	};

	//------------------------------------------------------------

	/*
	 * Binds buttons with form's button properties.
	 */
	if (window[id + "_insertBt"] != undefined) this.insertBt = window[id + "_insertBt"];
	if (window[id + "_updateBt"] != undefined) this.updateBt = window[id + "_updateBt"];
	if (window[id + "_deleteBt"] != undefined) this.deleteBt = window[id + "_deleteBt"];
	if (window[id + "_cancelBt"] != undefined) this.cancelBt = window[id + "_cancelBt"];
	if (window[id + "_submitBt"] != undefined) this.submitBt = window[id + "_submitBt"];

	/*
	 * Function to initialize jQuery related values and events
	 */
	this.initForm = function() {

		// Form HTML element
		this.$form = $("#" + id);

		// The HTML form dialog bar
		$formBar = $("#" + id + "_dialogBar");
		$formBarTitle = $("#" + id + "_dialogTitle");

		// Cancel and Submit labels
		if (isNotEmpty(window[id + "_cancelBt"])) window[id + "_cancelBt"].setLabel(cancelBtLabel);
		if (isNotEmpty(window[id + "_submitBt"])) window[id + "_submitBt"].setLabel(submitBtLabel);

		if ($formBar.length == 0) $formBar = null;

		for (x in inputs) {
			this[inputs[x]].initInput();
		}

		//Base on the first input defines the pageID and moves the dialog bar to the page bar.
		if (inputs.length > 0 && pageID == undefined) {
			pageID = this[inputs[0]].$input.closest(".silk-page").attr("id");

			if (pageID == undefined) {
				pageID = this[inputs[0]].$input.closest(".modal").attr("id");
				if (pageID != undefined) {
					isModal = true;
				}
			}

			if (pageID != undefined) {
				$pageBar = window[pageID].$page.find(".silk-navbar");
				var $topBar = window[pageID].$page.find(".silk-top-bar");

				if ($topBar.length != 0) {
					if ($formBar != null) $topBar.append($formBar);
				}
				$("#" + pageID + "_closeBt").prependTo($("#" + pageID + "_closeBt").parent());
			}

		}

		/*
		 * Sets the insert button click method to the setInsert method.
		 * Cancel the process if the onInsert event returns false
		 */
		if (this.insertBt != null) {
			this.insertBt.on("click", $.proxy(function() {

				/**
				 * This event is triggered before the form is set for an insert. If the function returns *false*, the process is canceled. Created with the ```Form.on("insert", function(){})``` method.
				 * @event Form#Event:insert
				 */
				if (!ifUndefined(eventManager.dispatch("insert"), true)) return;

				this.setInsert();

			}, this));
		}

		/*
		 * Sets the update button click method to the setUpdate method.
		 * Cancel the process if the onUpdate event returns false
		 */
		if (this.updateBt != null) {
			this.updateBt.on("click", $.proxy(function() {

				/**
				 * This event is triggered before the form is set for an update. If the function returns *false* the process is canceled. Created with the ```Form.on("update", function(){})``` method.
				 * @event Form#Event:update
				 */
				if (!ifUndefined(eventManager.dispatch("update"), true)) return;

				this.setUpdate();

			}, this));
		}

		/*
		 * Sets the delete button click method to the setDelete method.
		 * Cancel the process if the onDelete event returns false
		 */
		if (this.deleteBt != null) {
			this.deleteBt.on("click", $.proxy(function() {

				/**
				 * This event is triggered before the form is set for a delete. If the function returns *false* the process is canceled. Created with the ```Form.on("delete", function(){})``` method.
				 * @event Form#Event:delete
				 */
				if (!ifUndefined(eventManager.dispatch("delete"), true)) return;

				this.setDelete();

			}, this));
		}

		/*
		 * Sets the cancel button click method to the doCancel method.
		 * Cancel the process if the onCancel event returns false
		 */
		if (this.cancelBt != null) {
			this.cancelBt.on("click", $.proxy(function() {

				/**
				 * This event is triggered before the form executes a cancel. If the function returns *false* the process is canceled. Created with the ```Form.on("cancel", function(){})``` method.
				 * @event Form#Event:cancel
				 */
				if (!ifUndefined(eventManager.dispatch("cancel"), true)) return;

				/*
				 * Calls doCancel. The parameter indicate that a button was clicked.
				 */
				this.doCancel(true);

			}, this));
		}

		/*
		 * Sets the confirmation dialog properties.
		 */
		if (confirmTitle != "") this.submitBt.setConfirmTitle(confirmTitle);
		if (confirmMessage != "") this.submitBt.setConfirmMessage(confirmMessage);
		if (confirmLabel != "") this.submitBt.setConfirmLabel(confirmLabel);
		if (confirmIcon != "") this.submitBt.setConfirmIcon(confirmIcon);

		if (isNotEmpty(confirmTarget)) {

			this.submitBt.on("validateConfirm", function() {
				return confirmTarget.indexOf(_action) > -1;
			});
		}

		/*
		 * Sets the submit button click method to the doSubmit method.
		 * Cancel the automatic submit process if the onSubmit event returns false
		 */
		if (this.submitBt != null) {
			this.submitBt.on("click", $.proxy(function() {
				this.doSubmit();
			}, this));
		}

		if (startMode) {
			setTimeout($.proxy(function() {
				this.setMode(true);
				this.setAction("update");
			}, this), 400);
		}

	}

};
