/*
 * Copyright (c) 2025 OopsClick LLC. All rights reserved.
 * This work is licensed under the O'Saasy License Agreement, a copy of which can be
 * found in the LICENSE file in the root directory of this project or at https://silkbuilder.com/core-license.
 */

/**
 * Returns an Input instance.
 * @class
 * @classdesc The Input Class provides properties, methods, and events to interface with the HTML tags generated by  the ```<silk:Input>``` tag.
 *
 * @constructor
 * @param {String} id - Unique identifier.
 * @param {String} type - The input type: text, textarea, code, sql, js, css, xml, xhtml, html, date, time, datetime, select, numeric, integer, decimal, checkbox, button, options, radio, password, file, email, hidden.
 * @param {String} label - The text used as the input's label.
 * @param {Object} options - Object containing the Input configuration options.
 * @param {String} initValue - The value that the Input will hold when created.
 * @param {String} [options.columnID] - The dataSource column name if different from the id parameter.
 * @param {String} [options.description] - The input's description only shows in editing mode.
 * @param {String} [options.descriptionPlace] - The input's description position: top or bottom.
 * @param {String} [options.width] - The width of the component in pixels or percentage.
 * @param {String} [options.height=200px] - The input's height in case of the types: textarea, code, sql, js, css, xml, xhtml, and html.
 * @param {String} [options.scrollHeight] - The height limit of the component in read mode before the content needs scrolling.
 * @param {String} [options.dataSource] - The dataProvider id in case of types: Select, options, and radio.
 * @param {Boolean} [options.required=false] - The logic value or expression to determine if the component should be required before data submission.
 * @param {Boolean} [options.editable=true] - The logic value or JavaScript expression to determine if the component should be visible.
 * @param {Boolean} [options.visible=true] - Expression to evaluate if the component should be visible.
 * @param {Boolean} [options.hideEmpty=false] - Expression to evaluate if the component should be hidden when in read mode.
 * @param {Integer} [options.maxLength] - The number of characters the input will allow.
 * @param {String} [options.name] - The "name" of the input if used under a regular <form> HTML tag, if different than the ID.
 * @param {String} [options.scriptValue] - Javascript expression returning the input's value.
 * @param {String} [options.scope=1] - The component end target. Check the setScope() method for values.
 * @param {String} [options.mask] - The input's entry mask or character filter. (http://igorescobar.github.io/jQuery-Mask-Plugin/)
 * @param {Boolean} [options.mode=false] - True if editing, or false if read only.
 * @param {String} [options.placeholder] - The input's placeholder text, the helping text shown inside the text input.
 * @param {String} [options.form] - The parent Form. Undefined if operating standalone.
 * @param {Boolean} [options.block=false] - If the component is the end of a block. Next Inputs will start in a new line.
 * @param {String} [options.cssClass] - The extra CSS classes to use with the input element.
 * @param {String} [options.inputClass] - Extra CSS classes affecting the component.
 * @param {String} [options.valueColumn] - Indicates the dataProvider's column containing the value to use in select, options, and radio.
 * @param {String} [options.labelColumn=label] - Indicates the dataProvider's column containing the label to use in select, options, and radio.
 * @param {String} [options.linkColumns] - Indicates the dataProvider's columns that will be updated in the dataSource. To use in select, options, and radio.
 * @param {String} [options.template] - A HTML schema defining the component read view.
 * @param {String} [options.target] - The HTML element in which the component will be rendered.
 * @param {String} [options.extraProperties] - To add extra HTML properties to the input.
 * @param {String} [options.htmlConfigFile=/ckeditor-conf/bar-simple.js] - The JavaScript file containing the custom configuration for CKEditor. To be used with type "html".
 * @param {String} [options.stringList] - A JSON array which will serve as dataProvider for select, options, and radio. This array should contain objects with the properties' value and label.
 * @param {String} [options.prompt] - The provided text will be added as an extra option to the select usually used to request a value selection.
 * @param {String} [options.promptValue] - The value returned by the select "prompt" if the user selects it.
 * @param {String} [options.filePreview=false] - If the component will show a button to preview an uploaded file. To use with a input type file.
 * @param {String} [options.fileDownload=false] - If the component will show a button to download an uploaded file. To use with a input type file.
 * @param {String} [options.filePreviewLabel=Preview] - The label of the preview button. To use with a input type file.
 * @param {String} [options.fileDownloadLabel=Download] - The label of the download button. To use with a input type file.
 * @param {String} [options.fileUploadLabel=Drag and drop file here, or click to select file.] - The label of the upload button. To use with a input type file.
 * @param {String} [options.filePreviewClass=btn-primary] - The preview button Bootstrap class. To use with a input type file.
 * @param {String} [options.fileDownloadClass=btn-primary] - The download button Bootstrap class. To use with a input type file.
 * @param {String} [options.filePreviewIcon=fas fa-file] - The preview button Font Awesome icon class. To use with a input type file.
 * @param {String} [options.fileDownloadIcon=fas fa-file-download] - The download button Font Awesome icon class. To use with a input type file.
 * @param {String} [options.uploadURL] - The URL of the service uploading the file. To use with type file.
 * @param {String} [options.fileTypeList] - String containing the comma-separated list of accepted file extensions. To use with a input type file.
 * @param {Integer} [options.fileSizeLimit] - The number of MB allowed to upload. To use with a input type file.
 * @param {Integer} [options.timer=0] - The number of milliseconds before triggering the "timer" event when entering data.
 * @param {String} [option.toggleList] - The list of comma-separated elements that will be toggled together with the component.
 *
 * @property {String} columnID - The input's unique identifier. This would be the name of the dataProvider column if part of a Form tag.
 * @property {Object} $input - The JQuery reference to the SILK Input HTML structure.
 * @property {Object} $filePreviewBt - The JQuery reference to the preview button.
 * @property {Object} $fileDownloadBt - The JQuery reference to the donwload button.
 * @property {Integer} selectedIndex - The index of the last dataProvider's item in the case of type select and radio.
 */
var Input = function(id, type, label, options, initValue) {

	if (ifUndefined(options, "") == "") options = {};

	this.className = "input";

	this.columnID = ifUndefined(options["columnID"], id);
	var description = ifUndefined(options["description"], "");
	var descriptionPlace = ifUndefined(options["descriptionPlace"], "top");
	var width = ifUndefined(options["width"], "");
	var height = ifUndefined(options["height"], "200px");
	var scrollHeight = ifUndefined(options["scrollHeight"], "");
	var dataSource = ifUndefined(options["dataSource"], "");
	var required = ifUndefined(options["required"], false);
	var editable = ifUndefined(options["editable"], true);
	var visible = ifUndefined(options["visible"], "");
	var hideEmpty = ifUndefined(options["hideEmpty"], false);
	var maxLength = ifUndefined(options["maxLength"], "");
	var name = ifUndefined(options["name"], "");
	var scriptValue = ifUndefined(options["scriptValue"], "");
	var scope = ifUndefined(options["scope"], 1);
	var mask = ifUndefined(options["mask"], "");
	var mode = ifUndefined(options["mode"], false);
	var placeholder = ifUndefined(options["placeholder"], "");
	var form = ifUndefined(options["form"], undefined);
	//var validation		= ifUndefined( options["validation"],"");
	var block = ifUndefined(options["block"], false);
	var cssClass = ifUndefined(options["cssClass"], "");
	var inputClass = ifUndefined(options["inputClass"], "");
	var valueColumn = ifUndefined(options["valueColumn"], "");
	var labelColumn = ifUndefined(options["labelColumn"], "label");
	var linkedColumns = ifUndefined(options["linkedColumns"], "");
	var template = ifUndefined(options["template"], "");
	var target = ifUndefined(options["target"], "");
	var extraProperties = ifUndefined(options["extraProperties"], "");
	var htmlConfigFile = ifUndefined(options["htmlConfigFile"], "/ckeditor-conf/bar-simple.js");
	var stringList = ifUndefined(options["stringList"], "");

	var prompt = ifUndefined(options["prompt"], "");
	var promptValue = ifUndefined(options["promptValue"], "");
	var direction = ifUndefined(options["direction"], "vertical");
	var itemsDirection = ifUndefined(options["itemsDirection"], "vertical");
	var targetPage = ifUndefined(options["targetPage"], "");

	var sanitize = ifUndefined(options["sanitize"], true);

	var filePreview = ifUndefined(options["filePreview"], false);
	var fileDownload = ifUndefined(options["fileDownload"], false);

	var filePreviewLabel = ifUndefined(options["filePreviewLabel"], "Preview");
	var fileDownloadLabel = ifUndefined(options["fileDownloadLabel"], "Download");
	var fileUploadLabel = ifUndefined(options["fileUploadLabel"], "Drag and drop file here, or click to select file.");

	var filePreviewClass = ifUndefined(options["filePreviewClass"], "btn-primary");
	var fileDownloadClass = ifUndefined(options["fileDownloadClass"], "btn-primary");

	var filePreviewIcon = ifUndefined(options["filePreviewIcon"], "fas fa-file");
	var fileDownloadIcon = ifUndefined(options["fileDownloadIcon"], "fas fa-file-download");

	var uploadURL = ifUndefined(options["uploadURL"], "");
	var fileTypeList = ifUndefined(options["fileTypeList"], "");
	var fileSizeLimit = ifUndefined(options["fileSizeLimit"], "");

	var timer = ifUndefined(options["timer"], 0);

	var inputTimer = null;

	var toggleList = ifUndefined(options["toggleList"], "");


	/**
	 * Returns the component's unique identifier.
	 */
	this.getID = function() {
		return id;
	}

	/*
	 * Setting event manager
	 */
	var eventManager = new EventManager();
	/**
	 * Load events to respond to the input's interactions. To set an event, use this code: ```Input.on(<eventName>, function(){<code>})```.
	 * @param {String} eventName - The event's name.
	 * @param {function} eventFunction - The function to be triggered.
	 */
	this.on = eventManager.on;

	/*
	 * Setting toggle manager
	 */
	var toggleManager = new ToggleManager(toggleList);

	this.$input;
	this.$dataField;
	this.$filePreviewBt = null;
	this.$fileDownloadBt = null;
	this.selectedIndex = 0;

	var $label;
	var $text;
	var $value;
	var $description;

	this.codeEditor = undefined;

	var $drop;
	var $progress;
	var $browse;

	var enableStatus = true;
	var visibleStatus = true;

	/*
	 * Defines if the validation of email addresses is single or multiple
	 */
	var singleEmail = false;
	if (type == "email") {
		singleEmail = true
	}
	if (type == "emails") {
		type = "email";
	}

	var previousValue = "";

	/*
	 * Connect to dataProvider.
	 */
	if (dataSource != "") {
		dataSource = window[dataSource];
		if (valueColumn == "") valueColumn = this.columnID;
	} else {
		valueColumn = "value";
	}

	/**
	 * The method to focus the input when in editable mode.
	 */
	this.focus = function() {
		$value.focus();
	}

	/**
	 * Method to programatically open a HTML Select input element
	 */
	this.openSelect = function() {
		$value.openSelect();
	}

	/**
	 * Method to return the original Input value before editing started.
	 * @returns {String}
	 */
	this.getPreviousValue = function() {
		return previousValue;
	}

	/**
	 * Method to set the Input's value before editing.
	 * @param {String} value - The value to apply.
	 */
	this.setPreviousValue = function(value) {
		if (type == "date" || type == "time" || type == "datetime") {
			previousValue = value;
		} else {
			previousValue = value;
		}
	}

	/**
	 * Returns the input element's ID.
	 * @returns {String}
	 */
	this.getInputID = function() {
		return id + "_input";
	}

	/**
	 * Returns the selected data dataProvider's item, or the value if the column is provided.
	 * @return {Object}
	 */
	this.getItem = function(column) {
		if (dataSource == "") return undefined;
		if (this.set == -1) return undefined;
		if (column == undefined) return dataSource.getItemAt(this.selectedIndex);
		return dataSource.getItemAt(this.selectedIndex, column);
	}

	/**
	 * Returns the input's type.
	 * @returns {String}
	 */
	this.getType = function() {
		return type;
	}

	/*
	 * Adds labelColumn to linkedColumns if linkColumn is not provided.
	 */
	if (labelColumn != "label" && labelColumn != "") {
		if (linkedColumns == "") {
			linkedColumns = labelColumn;
		} else {
			if (linkedColumns.indexOf(labelColumn) == -1) {
				linkedColumns = labelColumn + "," + linkedColumns;
			}
		}
	}

	/**
	 * Return the linked columns. These are the columns that will be updated into the Form's target dataSource.
	 * @returns {String}
	 */
	this.getLinkedColumns = function() {
		return linkedColumns.trim();
	}

	/**
	 * Sets the Input's operational scope. The values are:
	 * 0: Force send
	 * 1: If changed, go to DB (default)
	 * 2: If changed, go to DataProvider only
	 * 3: Stay in form
	 */
	this.setScope = function(newScope) {
		scope = newScope;
	}

	/**
	 * Returns the Input's operational scope.
	 * @returns {String}
	 */
	this.getScope = function() {
		return callFunction(scope);
	}

	/**
	 * Returns if the Input is required.
	 * @returns {Boolean}
	 */
	this.getRequired = function() {
		try {
			return callFunction(required)
		} catch (err) {
			return false;
		}
	};

	/**
	 * Returns if the Input is editable.
	 * @returns {Boolean}
	 */
	this.getEditable = function() {
		try {
			return callFunction(editable);
		} catch (err) {
			return false;
		}
	};

	/**
	 * Enables a disabled Input. If a parameter is provided, true enables it, and false disables it.
	 * @param {Boolean} status - Optional boolean value;
	 */
	this.setEnable = function(status) {
		if (status == undefined) status = true;
		this.$input.find("input").prop("disabled", !status);
		enableStatus = !status;
	};

	/*
	 * Disables an enable input.
	 * @param {Boolean} status - Optional boolean value;
	 */
	this.setDisable = function(status) {
		if (status == undefined) status = true;
		this.$input.find("input").prop("disabled", status);
		enableStatus = !status;
	};

	/*
	 * Returns true is the input is enable
	 * @return {Boolean}
	 */
	this.getEnable = function() {
		return enableStatus;
	};

	/*
	 * Returns true is the input is disable
	 * @return {Boolean}
	 */
	this.getDisable = function() {
		return !enableStatus;
	};

	/**
	 * Returns if the input is visible.
	 * @returns {Boolean}
	 */
	this.getVisible = function() {

		if (visible == "") return visibleStatus; // If visible has not been setup it return visibleStatys property

		try {
			visibleStatus = callFunction(visible);
		} catch (err) {
			visibleStatus = false
		}

		return visibleStatus;


	};

	/**
	 * Sets the Input's visible status.
	 * @param {Boolean} visibleMode - The visible status.
	 */
	this.setVisible = function(visibleMode) {

		if (hideEmpty) {
			if (this.getMode() == false && isEmpty(this.getValue())) {
				visibleMode = false;
			}
		}

		if (visibleMode == undefined) {
			visibleMode = this.getVisible();
		}

		this.$input.toggle(visibleMode);

		if (isNotEmpty(toggleList)) toggleManager.toggle(visibleMode, this.$input);

	}

	/**
	 * Hides or shows the input based on the provided parameter.
	 * @function
	 * @param {boolean} status - True shows and false hides.
	 */
	this.toggle = function(mode) {
		this.setVisible(mode);
	}

	/**
	 * Shows the input.
	 * @function
	 */
	this.show = function() {
		this.setVisible(true);
	}

	/**
	 * Hides the input.
	 * @function
	 */
	this.hide = function() {
		this.setVisible(false);
	}

	/**
	 * Sets Input's mask method following http://igorescobar.github.io/jQuery-Mask-Plugin/docs.html
	 */
	this.setMask = function(mask, option) {
		$value.mask(mask, option);
	}

	/**
	 * Sets the Input's interaction mode.
	 * @param {Boolean} viewMode - True sets the input to editing, false sets the input tas read only.
	 * @param {Boolean} setPreviousValue - If true (default) will set the previous value.
	 */
	this.setMode = function(viewMode, setPreviousValue) {

		viewMode = evalMode(viewMode);

		if (type == "hidden") return;

		//this.setVisible();

		if (viewMode == undefined) {
			mode = false;
		} else {
			mode = viewMode;
		}

		if (setPreviousValue == undefined) setPreviousValue = true;

		if (!this.getEditable()) mode = false;

		if (mode) {
			/*
			 * Change to write mode
			 */

			if (type == "checkbox") this.$input.css("pointer-events", "auto");

			if (setPreviousValue) {
				previousValue = this.getValue();
				this.cleanClasses();
				$value.removeClass("silk-input-missing");
			}


			if (width == "") {
				this.$input.css("max-width", "100%");
				this.$input.css("width", "100%");
			} else {
				let newWidth = width;
				if (width.indexOf("%") > -1) {
					newWidth = (getNumber(width) - 0.30) + "%";
				}
				this.$input.css("max-width", newWidth);
				this.$input.css("width", "100%");
			}

			if (type == "file") {
				if (filePreview) this.$filePreviewBt.toggle(this.getValue() != "");
				if (fileDownload) this.$fileDownloadBt.toggle(this.getValue() != "");

				$text.toggle(this.getValue() != "");
				$drop.show();
				$progress.hide();
				$progress.find("div").css("width", "0%");

			} else if (isIn(type, "sql", "js", "css", "xml", "xhtml")) {
				$text.show();
				this.codeEditor.setReadOnly(false);

			} else {
				$text.hide();
				//$value.show();
				$value.css('display', 'inline-block');
			}
			
			if (type == "html") {
				if (!CKEDITOR.instances[this.getInputID()]) {
					if (htmlConfigFile != "") {
						CKEDITOR.replace(this.getInputID(), {
							customConfig: window['contextPath'] + htmlConfigFile + "?unique" + (new Date()).getTime(),
							height: replaceAll(height, "px", "")
						});
					} else {
						CKEDITOR.replace(this.getInputID());
					}
					CKEDITOR.instances[this.getInputID()].on("change", $.proxy(function(e) {
						eventManager.dispatch("keyup", e, this);
					}, this));
				}
				// Added to hide when refreshing
				this.$input.find(".silk-input-value").hide();
			}

		} else {
			/*
			 * Change to read-only
			 */

			if (type == "checkbox") this.$input.css("pointer-events", "none");

			if (width == "") {
				this.$input.css("max-width", "100%");
				this.$input.css("width", "100%");
			} else {
				this.$input.css("width", "auto");
				this.$input.css("max-width", "");
			}

			if (type == "html") {
				if (CKEDITOR.instances[this.getInputID()]) {
					CKEDITOR.instances[this.getInputID()].updateElement();//function call fails here
					try {
						CKEDITOR.instances[this.getInputID()].destroy();
					} catch (err) {
						delete CKEDITOR.instances[this.getInputID()];
					}
					$('#cke_' + this.getInputID()).remove();
				}
			}

			if (type == "file") {
				if (filePreview) this.$filePreviewBt.toggle(this.getValue() != "");
				if (fileDownload) this.$fileDownloadBt.toggle(this.getValue() != "");

				$text.show();
				$drop.hide();
				$progress.hide();

			} else if (isIn(type, "sql", "js", "css", "xml", "xhtml")) {
				$text.show();
				this.codeEditor.setReadOnly(true);

			} else {
				$text.show();
				$value.hide();
			}
		}

		this.setVisible();

		$description.toggle(mode);

		/**
		 * This event is triggered when the Input's mode changes. Created with the ```Input.on("modeChange", function(mode,$text,$vale){})``` method.
		 * @param {Boolean} mode - The set mode,
		 * @param {Object} $text - JQuery reference to the input displayed text.
		 * @param {Object} $value - JQuery reference to the inputs input HTML element.
		 * @event Input#Event:modeChange
		 */
		eventManager.dispatch("modeChange", mode, $text, $value)

	}

	/**
	 * Returns the Input's mode.
	 * @returns {Boolean}
	 */
	this.getMode = function() {
		return mode;
	}

	/*
	 * Evaluates the mode. For editing is accepts the value: true, edit, open and entry.
	 */
	var evalMode = function(mode) {
		if (getObjectType(mode) == "number") {
			mode = mode == 1;
		} else if (getObjectType(mode) == "string") {
			if (("|true|edit|open|entry").indexOf(mode) > -1) {
				mode = true;
			} else {
				try {
					mode = callFunction(mode);
					if (getObjectType(mode) != "boolean") mode = false;
				} catch (err) {
					mode = false;
				}
			}
		}
		return mode;
	}

	/**
	 * Marks the Input as required
	 */
	this.markRequired = function() {
		$value.removeClass("silk-input-missing");
		if (type != "file") {
			$value.addClass("silk-input-required");
		} else {
			$drop.addClass("silk-input-required");
		}
	};

	/**
	 * Marks the Input as data missing.
	 */
	this.markMissing = function() {
		$value.removeClass("silk-input-required");
		if (type != "file") {
			$value.addClass("silk-input-missing");
		} else {
			$drop.addClass("silk-input-missing");
		}

	};

	/**
	 * Marks the Input as an entry error.
	 */
	this.markValidationError = function() {
		$value.removeClass("silk-input-required");
		$value.removeClass("silk-input-missing");
		if (type != "file") {
			$value.addClass("silk-input-error");
		} else {
			$drop.addClass("silk-input-error");
		}
	}

	/**
	 * Cleans the Input from markers like required, missing, and error.
	 */
	this.cleanClasses = function() {
		if (type != "file") {
			$value.removeClass("silk-input-missing");
			$value.removeClass("silk-input-error");
			$value.removeClass("silk-input-required");
		} else {
			$drop.removeClass("silk-input-missing");
			$drop.removeClass("silk-input-error");
			$drop.removeClass("silk-input-required");
		}

		if (this.getRequired()) {
			if (type != "file") {
				$value.addClass("silk-input-required");
			} else {
				$drop.addClass("silk-input-required");
			}
		}
	}

	/**
	 * Executes a validation process. Returns 0 if no errors and 1 if errors are found.
	 * @return {Integer}
	 */
	this.validate = function() {

		this.cleanClasses();

		var returnValue = 0;

		if (this.getRequired() && this.getVisible()) { // If required=true and visible=true
			var value = this.getValue();
			//console.log(this);
			//console.log(value);
			if (value == null) value = "";
			if (("" + value).trim() == "") {
				this.markMissing();
				returnValue = 1;
			} else {
				this.markRequired();
			}
		}

		if (type == "checkbox" && this.getRequired() && this.getValue() == 0) {
			returnValue = 1;
		}

		// add date validation
		if (type == "date" || type == "datetime") {
			var value = this.getValue();
			if (value == "") {
				returnValue = 0;
			} else {
				if (value.indexOf("-") != 4) {
					this.markValidationError();
					returnValue = 1;
				}
			}
		}

		/*
		 * Validate email
		 */
		if (type == "email") {

			let email = this.getValue();

			if (email != "") {

				/*
				 * Checks the email validation
				 */
				if (!isEmail(email, singleEmail)) {
					this.markMissing();
					returnValue = 1;
				}

			}
		}

		/**
		 * This event is triggered when an input is validated. If the event function returns false, the input will be marked an "invalid". Created with the ```Input.on("validation", function(type,value){})``` method.
		 * @param {String} type - The Input's type.
		 * @param {String} value - The input's entered value.
		 * @event Input#Event:validation
		 */
		if (!ifUndefined(eventManager.dispatch("validation", type, this.getValue()), true)) {
			this.markValidationError();
			returnValue = 1;
		};

		return returnValue;

	};

	var checkboxIsLogical = false;
	/**
	 * Changes the Input's stored value.
	 * @param {String} value - The new value.
	 */
	this.setValue = function(value) {

		if (value == null) value = "";
		if (value == undefined) value = "";

		/* CHEKCBOX */
		if (type == "checkbox") {
			
			if(value=="true"){
				value=1;
				checkboxIsLogical=true;
			}
			if(value=="false"){
				value=0;
				checkboxIsLogical=true;
			} 
			
			value = getNumber(value);

			var icon = document.createElement("span");
			icon.setAttribute("aria-hidden", "true");

			if (value == 0) {
				$value.prop("checked", false);
				icon.setAttribute("class", "far fa-square");
			} else {
				$value.prop("checked", true);
				icon.setAttribute("class", "far fa-check-square fa-lg");
			}
			$text.html(icon);

			/* SELECT */
		} else if (type == "select") {

			$value.val(value);

			if ($value.val() != null) {
				var $option = $value.find("option:selected");
				/*
				 * Check if prompt is selected
				 */
				if ($option.attr("recordIndex") == -1) {
					/*
					 * Load empty into text.
					 */
					$text.html("&nbsp;");
				} else {
					/*
					 * Load option label into text.
					 */
					$text.html(renderTemplate($option.text()));
				}
			} else {
				$value.prop("selectedIndex", 0);
				var $option = $value.find("option:selected");
				$text.html("&nbsp;");
			}

			var recordIndex = $option.attr("recordIndex");
			if (recordIndex == undefined) {
				this.selectedIndex = $value.prop("selectedIndex");
			} else {
				this.selectedIndex = getNumber(recordIndex);
			}

			/* OPTIONS */
		} else if (type == "options") {

			if (left(value, 1) != ",") value = "," + value;
			if (right(value, 1) != ",") value = value + ",";

			$text.text("");
			if (itemsDirection == "vertical") {
				var ulElement = document.createElement("ul");
				ulElement.setAttribute("style", "margin:0px;padding-left:20px;");
			} else {
				var ulElement = document.createElement("div");
			}

			var ulCount = 0;
			$value.find("input").each(function(x, element) {
				var checked = value.indexOf("," + $(element).val() + ",") > -1;
				$(element).prop("checked", checked);
				if (checked) {
					if (itemsDirection == "vertical") {
						var itemElement = document.createElement("li");
						itemElement.append($(element).attr("label"));
					} else {
						var itemElement = document.createElement("span");
						itemElement.setAttribute("style", "padding-right:10px;");
						var textElement = document.createTextNode("\u2022 " + $(element).attr("label"));
						itemElement.append(textElement);
					}
					ulElement.append(itemElement);
					ulCount++;
				}
			});
			if (ulCount == 0) ulElement = document.createTextNode('\u00A0');
			$text.append(ulElement);

			/* RADIO */
		} else if (type == "radio") {
			$text.text("");
			var valueLabel = "";
			$value.find("input").each(function(x, element) {
				if ($(element).val() == value) {
					$(element).prop("checked", true);
					valueLabel = $(element).attr("label");
				} else {
					$(element).prop("checked", false);
				}
			});
			$text.text(valueLabel);

			/* DATE TIME DATETIME */
		} else if (type == "date" || type == "time" || type == "datetime") {
			if (value == "") {
				$value.val(""); //datetimepicker("update",""da); //clearDates
				$text.html("&nbsp;");
			} else {
				$value.datetimepicker("update", stringToDate(value));
				$text.html(renderTemplate($value.val()));
			}

			/* HIDDEN */
		} else if (type == "hidden") {
			$value.val(value);

		/* Integer */
		/*
		} else if (type == "integer") {
			$value.val(value);
			if (value == "") value = "0";
			$text.html(value);
		*/

			/* INTEGER NUMERIC DECIMAL */
		} else if (type == "integer" || type == "numeric" || type == "decimal") {
			value = getNumber(value);
			
			if (value == 0) {
				$value.val("0");
				$text.html($.format.number(0, mask.replace("D", "")));
				if (mask !== "") $value.mask(mask, { reverse: true });
			} else {
				$value.val(value);
				if (mask !== "") $value.mask(mask, { reverse: true });
				$text.html(renderTemplate($value.val()));
			}

			/* PASSWORD */
		} else if (type == "password") {
			$value.val("");
			$text.html("&nbsp;");

			/* HTML */
		} else if (type == "html") {
			if (CKEDITOR.instances[this.getInputID()]) {
				CKEDITOR.instances[this.getInputID()].setData(value);
			} else {
				$value.val(value);
				if (value == "") value = "&nbsp;";
				$text.html(value);
			}

			/* code Editors */
		} else if (isIn(type, "sql", "js", "css", "xml", "xhtml")) {
			this.codeEditor.setCode(value);
			setTimeout($.proxy(function() { this.$input.find(".cm-scroller").scrollTop(0) }, this), 10);

			/* FILE */
		} else if (type == "file") {
			$value.val(value);
			if (value == "") value = "&nbsp;";
			$text.html(value);

			/* TEXT - OTHERS */
		} else {
			if (value == "") {
				$value.val("");
				$text.html("&nbsp;");
				if (mask !== "") $value.mask(mask);
			} else {
				$value.val(value);
				if (type == "code") {
					var html = $value.val();
					html = replaceAll(html, "&", "&amp;");
					html = replaceAll(html, "<", "&lt;");
					html = replaceAll(html, ">", "&gt;");
					html = replaceAll(html, "\t", "&nbsp;&nbsp;&nbsp;&nbsp;");
					html = html.replace(/\n/g, "<br />");
					$text.html(html);
				} else {
					if (mask !== "") $value.mask(mask);
					var textValue = $value.val().replace(/\n/g, "<br />");
					$text.html(renderTemplate(textValue));
				}
			}

			/*
			 * BUTTON
			 * Tiggers the change event which is not dispatch by JQuery on inputs with type button.
			 * The regular change even for inputs is set in the inputInit method.
			 */
			if (type == "button") {
				if (previousValue != this.getValue()) eventManager.dispatch("change");
			}

		}

		/**
		 * This event is triggered when the input's value is set. Created with the ```Input.on("setValue", function(value, $value){})``` method.
		 * @param {String} value - The value entered.
		 * @param {Object} $value - The JQuery instance to the input HTML element.
		 * @event Input#Event:setValue
		 */
		eventManager.dispatch("setValue", value, $value);

	}

	var renderTemplate = function(textValue) {
		if (template == "") return textValue;
		var dpItem = undefined;

		if (form != undefined) {
			dpItem = form.getSelectedItem();
		}

		if (dpItem == undefined) {
			dpItem = new Object();
			dpItem[this.columnID] = textValue;
		}

		// For Select
		if (dataSource != "") {
			var exItem = dataSource.getSelectedItem();
			for (var prop in exItem) {
				if (dpItem[prop] == undefined) dpItem[prop] = exItem[prop];
			}
		}

		textValue = getTemplateData(template, 0, dpItem);

		return textValue;

	}

	/**
	 * Returns the Input's stored value.
	 * @returns {String}
	 */
	this.getValue = function() {

		/**
		 * This event is triggered when the input's value is requested. If the event function returns a value this will become the returned value by the getValue method. Created with the ```Input.on("getValue", function($value){})``` method.
		 * @param {Object} $value - The jQuery instance to the input HTML element.
		 * @event Input#Event:getValue
		 */
		const eventResult = eventManager.dispatch("getValue", $value);
		if (eventResult != undefined) return eventResult;

		if (type == "checkbox") {
			if ($value.prop("checked")) {
				if( checkboxIsLogical ){
					return true;
				}else{
					return 1;
				}
			} else {
				if( checkboxIsLogical ){
					return false;
				}else{
					return 0;
				}
			}

		} else if (type == "select") {
			return $value.val();

		} else if (type == "options") {
			var value = ",";
			$value.find("input").each(function(x, element) {
				if ($(element).prop("checked")) value += $(element).val() + ",";
			});
			if (value == ",") value = "";
			return value;

		} else if (type == "radio") {
			var value = "";
			value = $value.find('input[name=' + id + ']:checked').val();
			if (value == undefined) value = "";
			return value;

		} else if (type == "date" || type == "time" || type == "datetime") {
			if ($value.val() == "") {
				return "";
			} else {
				return dateToString($value.datetimepicker("getDate"));
			}

		} else if (type == "integer" || type == "numeric" || type == "decimal") {
			return getNumber($value.val());

		} else if (type == "html") {
			if (CKEDITOR.instances[this.getInputID()]) {
				return CKEDITOR.instances[this.getInputID()].getData();
			} else {
				return $value.val();
			}

		} else if (isIn(type, "sql", "js", "css", "xml", "xhtml")) {
			return this.codeEditor.getCode();

		} else {
			if (scriptValue != "") {
				var processedValue = "";
				try {
					processedValue = callFunction(scriptValue);
				} catch (err) {
					//console.log(err);
					processedValue = scriptValue;
				}
				return processedValue;
			}

			return $value.val();
		}
	}

	/**
	 * Returns the Input's displayed read-only text.
	 * @returns {String}
	 */
	this.getText = function() {
		return $text.html();
	}

	/**
	 * Returns the Input's displayed label.
	 * @returns {String}
	 */
	this.getLabel = function() {
		return $label.html();
	}

	/**
	 * Sets the Input's label.
	 * @param {String} label - The new label.
	 */
	this.setLabel = function(label) {
		$label.text(label);
	}

	/**
	 * Returns if the Input value has changed.
	 * @return {Boolean}
	 */
	this.hasChanged = function() {
		if (!this.getEditable()) return false; // editable=false is ignored
		if (!this.getVisible()) return false; // visible=false is ignored
		if (scriptValue != "") return true;

		if (type == "select") {
			if (this.selectedIndex == -1 && promptValue == "") {
				return false;
			} else {
				if (form != undefined) {
					if (form.getAction() == 'insert') return true;
				}
			}
		}

		if (type == 'date' && previousValue != "" && previousValue.length < 11) previousValue += " 00:00:00.000";


		return previousValue != this.getValue();
	}

	/**
	 * Executes the loading of data from the dataSource into the Input.
	 */
	this.load = function() {

		var filterResult = true;
		var oldValue = this.getValue();

		$value.text("");

		if (dataSource == "") {
			console.log(id + ": No dataSource provided");
		}

		if (type == "select") {

			if (prompt !== "") {
				var optionElement = document.createElement("option");
				optionElement.setAttribute("value", promptValue);
				optionElement.setAttribute("recordIndex", -1);
				optionElement.append(prompt);
				$value.append(optionElement);
			}

			for (var x = 0; x < dataSource.length(); x++) {
				var item = dataSource.getItemAt(x);

				/**
				 * This event is triggered before a row item is added to a list. If the function returns false, the item is ignored.
				 * This works for type select, options, and ratio.
				 * Created with the ```Input.on("filterLoad", function(index,item){})``` method.
				 * @event Input#Event:filterLoad
				 */
				filterResult = eventManager.dispatch("filterLoad", item);

				if (filterResult == undefined) filterResult = true;
				if (filterResult) {
					var value = item[valueColumn];
					var label = item[labelColumn];

					var optionElement = document.createElement("option");
					optionElement.setAttribute("value", value);
					optionElement.setAttribute("recordIndex", x);
					if( oldValue==value ){
						optionElement.setAttribute("selected","");
					}
					optionElement.append(label);
					$value.append(optionElement);
					
				}
			}

			var recordIndex = $value.find("option:selected").attr("recordIndex");
			if (recordIndex == undefined) {
				this.selectedIndex = $value.prop("selectedIndex");
			} else {
				this.selectedIndex = getNumber(recordIndex);
			}
			

		}
		if (type == "options") {
			//var html = "";

			for (var x = 0; x < dataSource.length(); x++) {
				var item = dataSource.getItemAt(x);
				filterResult = eventManager.dispatch("filterLoad", item);
				if (filterResult == undefined) filterResult = true;
				if (filterResult) {

					var value = item[valueColumn];
					var label = item[labelColumn];

					var labelBox = document.createElement("label");

					var inputElement = document.createElement("input");
					inputElement.setAttribute("type", "checkbox");
					inputElement.setAttribute("value", value);
					inputElement.setAttribute("label", label);

					var textBox = document.createElement("span");
					textBox.innerHTML = label;

					labelBox.append(inputElement);
					labelBox.append(textBox);

					$value.append(labelBox);

					if (itemsDirection == "vertical") {
						$value.append("<br>");
					} else {
						$value.append("<span> &nbsp; </span>");
					}

				}
			}
		}

		if (type == "radio") {
			//var html = "";
			for (var x = 0; x < dataSource.length(); x++) {
				var item = dataSource.getItemAt(x);
				filterResult = eventManager.dispatch("filterLoad", item);
				if (filterResult == undefined) filterResult = true;
				if (filterResult) {

					var value = item[valueColumn];
					var label = item[labelColumn];

					var labelBox = document.createElement("label");

					var inputElement = document.createElement("input");
					inputElement.setAttribute("name", id);
					inputElement.setAttribute("type", "radio");
					inputElement.setAttribute("label", label);
					inputElement.setAttribute("value", value);

					var textBox = document.createElement("span");
					textBox.innerHTML = label;

					labelBox.append(inputElement);
					labelBox.append(textBox);

					$value.append(labelBox);

					if (itemsDirection == "vertical") {
						$value.append("<br>");
					} else {
						$value.append("<span> &nbsp; </span>");
					}

				}
			}
		}

		/**
		 * This event is triggered after the Input's value has been loaded from the dataSource. Created with the ```Input.on("afterLoad", function(){})``` method.
		 * @param {Object} $value - The jQuery instance to the input HTML element.
		 * @event Input#Event:afterLoad
		 */
		eventManager.dispatch("afterLoad");

		if (form != undefined) {
			if (form[this.columnID] != undefined) {
				this.setValue(form[this.columnID].getValue());
				this.setMode();
			}
		}


		
	}

	/*
	 * Generates the Input HTML holder.
	 */
	var getHtmlElement = function() {

		/*
		 * Creating HTML element entity based on the input type.
		 */
		var input = null;

		if (type == "textarea" || type == "html" || type == "code") {
			input = document.createElement("textarea");

		} else if (type == "select") {
			input = document.createElement("select");

		} else if (type == "options") {
			input = document.createElement("span");

		} else if (type == "radio") {
			input = document.createElement("span");

		} else {
			input = document.createElement("input");
		}

		var inputValue = "";
		var textValue = "\u00A0";

		if (scriptValue != "") {
			inputValue = scriptValue;
			textValue = scriptValue;
		}

		if (width == "") {
			if (type === "date") {
				width = "115px";
			} else if (type === "time") {
				width = "96px";
			} else if (type === "datetime") {
				width = "185px";
			} else if (type === "numeric") {
				width = "100px";
			} else if (type === "integer") {
				width = "100px";
			} else if (type === "decimal") {
				width = "130px";
			} else {
				//width="100%";
			}
		}

		if (mask == "") {
			if (type === "integer") mask = "#,###,##0";
			if (type === "numeric") mask = "#0";
			if (type === "decimal") mask = "#,###,###.00D";
		}
		
		var styleHeight = "";
		if (type == "textarea" || type == "html" || type == "code") {
			styleHeight = " height:" + height + " !important;";
		}

		if (type == "hidden") {
			input.setAttribute("id", id);
			input.setAttribute("type", "hidden");
			if (inputValue != "") input.setAttribute("value", inputValue);
			setDefaultInputAttributes(input, styleHeight);
			return input; // Does not need a Label container
		}

		if (type === "text" || type === "email" || type === "integer" || type === "numeric" || type === "decimal") {
			input.setAttribute("id", id + "_input");
			input.setAttribute("type", "text");
			if (inputValue != "") input.setAttribute("value", inputValue);
			setDefaultInputAttributes(input, styleHeight);
		}

		if (type == "password") {
			input.setAttribute("id", id + "_input");
			input.setAttribute("type", "password");
			setDefaultInputAttributes(input, styleHeight);
		}

		if (type == "button") {
			input.setAttribute("id", id + "_input");
			input.setAttribute("type", "button");
			setDefaultInputAttributes(input, styleHeight);
		}

		if (type == "file") {
			input.setAttribute("id", id + "_input");
			input.setAttribute("type", "hidden");
			setDefaultInputAttributes(input, styleHeight);
		}

		if (type == "date" || type == "time" || type == "datetime") {
			input.setAttribute("id", id + "_input");
			input.setAttribute("type", "text");
			setDefaultInputAttributes(input, styleHeight);
		}

		if (type == "textarea" || type == "code") {
			input.setAttribute("id", id + "_input");
			setDefaultInputAttributes(input, styleHeight);
			input.append(inputValue);
		}

		if (isIn(type, "sql", "js", "css", "xml", "xhtml")) {
			input.setAttribute("id", id + "_input");
			input.setAttribute("type", "hidden");
		}

		if (type == "html") {
			input.setAttribute("id", id + "_input");
			setDefaultInputAttributes(input, styleHeight);
			input.append(inputValue);
		}

		if (type == "checkbox") {
			input.setAttribute("id", id + "_input");
			input.setAttribute("type", "checkbox");
			input.setAttribute("class", "silk-input-value");
			input.setAttribute("name", name);
			input.setAttribute("style", "display: none;")

		}

		if (type == "select") {
			input.setAttribute("id", id + "_input");
			input.setAttribute("class", "form-control silk-input-value silk-input-select " + cssClass);
			input.setAttribute("name", name);
			input.setAttribute("style", "display: none;")
		}

		if (type == "options") {
			input.setAttribute("id", id + "_input");
			input.setAttribute("class", "form-control silk-input-value");
			input.setAttribute("name", name);
			input.setAttribute("style", "display: none;")
		}

		if (type == "radio") {
			input.setAttribute("id", id + "_input");
			input.setAttribute("class", "form-control silk-input-value");
			input.setAttribute("name", name);
			input.setAttribute("style", "display: none;")
		}


		/*
		 * Generate Label and Text view
		 */
		var labelContainer;
		if (type == "file") {
			labelContainer = document.createElement("div");
		} else {
			labelContainer = document.createElement("label");
		}

		labelContainer.setAttribute("id", id);

		if (width == "") {
			inputClass += " silk-full-width";
		} else {
			inputClass += " silk-partial-width";
		}

		labelContainer.setAttribute("class", "silk-input " + inputClass + " silk-input-box-" + type);

		if (type != "hidden" && description != "" && descriptionPlace == "top") {
			var descriptionBox = document.createElement("div");
			descriptionBox.setAttribute("class", "silk-input-description");
			//labelContainer.append(descriptionBox);
		}

		if (type == "checkbox") {
			var iconBox = document.createElement("span");
			iconBox.setAttribute("class", "silk-input-text");

			var icon = document.createElement("span");
			icon.setAttribute("class", "fa fa-square-o");
			icon.setAttribute("aria-hidden", "true");

			iconBox.append(icon);

			var labelBox = document.createElement("span");
			labelBox.setAttribute("class", "silk-input-label");
			labelBox.append(label);

			labelContainer.append(iconBox);
			labelContainer.append(input);
			labelContainer.append(document.createTextNode('\u00A0'));
			labelContainer.append(labelBox);
			if (descriptionBox != undefined) labelContainer.append(descriptionBox);

		} else if (isIn(type, "sql", "js", "css", "xml", "xhtml")) {
			var labelBox = document.createElement("span");
			labelBox.setAttribute("class", "silk-input-label silk-input-label-margin");

			var textBox = document.createElement("div");
			var inputTextClass = "form-control silk-input-value silk-input-code";
			textBox.setAttribute("id", id + "_code");
			textBox.setAttribute("class", inputTextClass);

			labelContainer.append(labelBox);
			if (descriptionBox != undefined) labelContainer.append(descriptionBox);
			labelContainer.append(textBox);
			labelContainer.append(input);

		} else if (type == "file") {

			var labelBox = document.createElement("span");
			labelBox.setAttribute("class", "silk-input-label");
			labelBox.append(label);
			labelContainer.append(labelBox);
			if (descriptionBox != undefined) labelContainer.append(descriptionBox);

			var textBox = document.createElement("span");
			textBox.setAttribute("class", "form-control silk-input-text");
			textBox.append(textValue);
			labelContainer.append(textBox);

			var dropBox = document.createElement("div");
			dropBox.setAttribute("class", "form-control silk-input-drop");
			dropBox.setAttribute("style", "height:" + height);
			dropBox.innerHTML = "<p>" + fileUploadLabel + "</p>";
			labelContainer.append(dropBox);

			var progressBox = document.createElement("div");
			progressBox.setAttribute("class", "progress silk-input-progress");
			progressBox.setAttribute("style", "height:50px");
			progressBox.innerHTML = "<div class='progress-bar progress-bar-striped progress-bar-animated' role='progressbar' style='width: 0%; height:50px' ></div>"
			labelContainer.append(progressBox);

			var browseBox = document.createElement("input");
			browseBox.setAttribute("type", "file");
			browseBox.setAttribute("class", "silk-input-browse");
			browseBox.setAttribute("style", "display: none;");

			if (fileTypeList != "") {
				let acceptList = fileTypeList.split(",");
				for (x = 0; x < acceptList.length; x++) {
					let item = acceptList[x].trim();
					if (item.indexOf("/") == -1) {
						if (item.indexOf(".") == -1) item = "." + item;
						acceptList[x] = item;
					} else {
						acceptList[x] = item;
					}
				}
				browseBox.setAttribute("accept", acceptList.toString());
			}

			labelContainer.append(browseBox);

			if (filePreview) {
				var buttonBox = document.createElement("button");
				buttonBox.setAttribute("id", id + "_previewBt");
				buttonBox.setAttribute("class", "btn " + filePreviewClass + " btn-sm xsilk-input-text");

				var icon = document.createElement("i");
				icon.setAttribute("class", filePreviewIcon);
				icon.setAttribute("aria-hidden", "true");

				buttonBox.append(icon);
				if (filePreviewLabel != "") buttonBox.append(" " + filePreviewLabel);

				labelContainer.append(buttonBox);
			}

			if (fileDownload) {
				var buttonBox = document.createElement("button");
				buttonBox.setAttribute("id", id + "_downloadBt");
				buttonBox.setAttribute("class", "btn " + fileDownloadClass + " btn-sm xsilk-input-text");

				var icon = document.createElement("i");
				icon.setAttribute("class", fileDownloadIcon);
				icon.setAttribute("aria-hidden", "true");

				buttonBox.append(icon);
				if (fileDownloadLabel != "") buttonBox.append(" " + fileDownloadLabel);

				labelContainer.append(buttonBox);
			}

			//labelContainer.append(document.createTextNode( '\u00A0' ));
			labelContainer.append(input);

		} else {
			var labelBox = document.createElement("span");
			labelBox.setAttribute("class", "silk-input-label silk-input-label-margin");

			var textBox = document.createElement("span");
			var inputTextClass = "form-control silk-input-text";
			if (scrollHeight != "") {
				inputTextClass += " silk-input-text-scroll";
				textBox.setAttribute("style", "height:" + scrollHeight + ";");
			}
			textBox.setAttribute("class", inputTextClass);
			textBox.append(textValue);

			labelContainer.append(labelBox);
			if (descriptionBox != undefined) labelContainer.append(descriptionBox);
			labelContainer.append(textBox);
			labelContainer.append(input);

		}

		if (type != "hidden" && description != "" && descriptionPlace == "bottom") {
			var descriptionBox = document.createElement("div");
			descriptionBox.setAttribute("class", "silk-input-description");
			labelContainer.append(descriptionBox);
		}

		return labelContainer;

	}

	var setDefaultInputAttributes = function(input, styleHeight) {
		input.setAttribute("class", "form-control silk-input-value silk-input-type-" + type + " " + cssClass);
		input.setAttribute("style", "display: none;" + styleHeight);
		if (placeholder != "") input.setAttribute("placeholder", placeholder);
		if (maxLength != "") input.setAttribute("maxLength", maxLength);
		if (name != "") input.setAttribute("name", name);

		if (extraProperties != "") {
			var extraList = extraProperties.trim();
			extraList = replaceAll(extraList, "  ", " ").split(" ");
			for (var x in extraList) {
				var parts = extraList[x].split("=");
				var part1 = parts[0];
				var part2 = (parts.length == 1) ? part1 : replaceAll(parts[1], "'", "");

				//console.log(part1);
				//console.log(part2);

				input.setAttribute(part1, part2);
			}
		}
	}

	/**
	 * Sets the Input's dataSource using a JSON structure. The JSON's items should have at least the 'value' and 'label' properties.
	 * @param {String} newList - JSON array.
	 */
	this.setStringList = function(newList) {
		if (newList != undefined) stringList = newList;

		var html = "";
		var itemList = "";

		if (stringList == "") return;

		try {
			itemList = JSON.parse(stringList);
		} catch (err) {
			console.log(err);
			$value.text("");
			return;
		}

		if (type == "select") {
			if (prompt !== "") {
				var optionElement = document.createElement("option");
				optionElement.setAttribute("value", promptValue);
				optionElement.setAttribute("recordIndex", -1);
				optionElement.append(prompt);
				$value.append(optionElement);
			}
		}

		for (var x = 0; x < itemList.length; x++) {
			var item = itemList[x];

			/*
			 * Fill select's options.
			 */
			if (type == "select") {
				var optionElement = document.createElement("option");
				optionElement.setAttribute("value", item.value);
				optionElement.setAttribute("recordIndex", x);
				optionElement.append(item.label);
				$value.append(optionElement);
			}

			/*
			 * Fill options check boxes.
			 */
			if (type == "options") {
				var labelBox = document.createElement("label");

				var inputElement = document.createElement("input");
				inputElement.setAttribute("type", "checkbox");
				inputElement.setAttribute("value", item.value);
				inputElement.setAttribute("label", item.label);
				inputElement.setAttribute("style", "margin:8px 5px 2px 0px;");

				labelBox.append(inputElement);
				labelBox.append(item.label);

				$value.append(labelBox);

				if (itemsDirection == "vertical") {
					$value.append("<br>");
				} else {
					$value.append("<span> &nbsp; </span>");
				}

			}

			/*
			 * Fill options check boxes.
			 */
			if (type == "radio") {
				var labelBox = document.createElement("label");

				var inputElement = document.createElement("input");
				inputElement.setAttribute("name", id);
				inputElement.setAttribute("type", "radio");
				inputElement.setAttribute("value", item.value);
				inputElement.setAttribute("label", item.label);
				inputElement.setAttribute("style", "margin:8px 5px 2px 0px;");

				labelBox.append(inputElement);
				labelBox.append(item.label);

				$value.append(labelBox);

				if (itemsDirection == "vertical") {
					$value.append("<br>");
				} else {
					$value.append("<span> &nbsp; </span>");
				}

			}

		}

	}

	var handleDrop = function(e, _this) {
		let dt = e.dataTransfer;
		let files = dt.files;
		handleFiles(files, _this);
	};

	/*
	 * Received uploadURL, formData, fileName, fileSize
	 */
	var handleFiles = function(files, _this) {

		let file = files[0];
		let fileName = file.name;
		let fileSize = file.size;
		
		/**
		 * This event is triggered after the file extension and size has been validated. Created with the ```Input.on("fileValidate", function(Input, typeError, sizeError){})``` method.
		 * @param {Object} Input - Reference to the Input.
		 * @param {Boolean} typeError - True if the file extension type is not a match.
		 * @param {Boolean} sizeError - True if the size is beyond set bounderies.
		 * @param {Object} file - The file element to be uploaded
		 * @event Input#Event:fileLoaded
		 */
		eventManager.dispatch("fileLoad", _this, file);
		
		/*
		 * If the upload URL is not provided the handle process is canceled.
		 */
		if (uploadURL == "") return;

		/**
		 * Verifies the allowed extensions.
		 */
		var typeError = false
		if (fileTypeList != "") {

			var pos = fileName.lastIndexOf(".") + 1;
			if (pos > 0) {
				var extension = fileName.substring(pos);
				if (!fileTypeList.includes(extension)) typeError = true;
			}

		}

		/**
		 * Verifies the file size limit on MB.
		 */
		var sizeError = false;
		if (fileSizeLimit != "") {
			var sizeLimit = getNumber(fileSizeLimit) * 1048576;
			if (fileSize > sizeLimit) sizeError = true;
		}

		if (typeError || sizeError) {
			_this.markValidationError();

			/**
			 * This event is triggered after the file extension and size has been validated and errors had been found. Created with the ```Input.on("fileValidate", function(Input, typeError, sizeError){})``` method.
			 * @param {Object} Input - Reference to the Input.
			 * @param {Boolean} typeError - True if the file extension type is not a match.
			 * @param {Boolean} sizeError - True if the size is beyond set bounderies.
			 * @param {Object} file - The file element to be uploaded
			 * @event Input#Event:fileValidate
			 */
			eventManager.dispatch("fileValidate", _this, typeError, sizeError, file);

			return;
		}


		/**
		 * Instantiating the FormData Object
		 */
		let formData = new FormData();

		/*
		 * Seets the file data
		 */
		formData.append(_this.columnID, file);

		/**
		 * This event is triggered before a file is uploaded. Created with the ```Input.on("beforeUpload", function(Input, formData, fileName, fileSize){})``` method.
		 * If the function returns false it will cancel the update process.
		 * @param {Object} input - Reference to the Input.
		 * @param {Object} formData - The form used to upload the file.
		 * @param {String} fileName - The name of the file to be uploaded.
		 * @param {Integer} fileSize - The file's size.
		 * @param {Object} file - The file element to be uploaded
		 * @event Input#Event:beforeUpload
		 */
		if (!ifUndefined(eventManager.dispatch("beforeUpload", _this, formData, fileName, fileSize, file), true)) {
			//if (result == undefined) result = true;
			//if (result == false)
			return;
		}

		$drop.hide();
		$text.hide();
		$progress.show();

		var xhr = new XMLHttpRequest();

		xhr.upload.onprogress = function(e) {
			if (e.lengthComputable) {
				var progress = getNumber((e.loaded / e.total) * 100, 0);
				$progress.find("div").css("width", progress + "%")
			}
		};

		xhr.onreadystatechange = function(e) {
			if (xhr.readyState == 4 && xhr.status == 200) {

				/*
				 * If exists reloading the JSON reponse.
				 */
				var responseObject = null;
				try {
					responseObject = JSON.parse(xhr.responseText);
					/*
					 * Set new fileName if it has changed
					 */
					if (responseObject["fileName"] != undefined) fileName = responseObject.fileName;
				}
				catch (err) {
					/*
					 * If the response text is a JSON strucure it is return as a plain text.
					 */
					responseObject = xhr.responseText;
				}

				/*
				 * Sets the file name into the input value. This could be the new name if set properly.
				 */
				_this.setValue(fileName);
				_this.setPreviousValue("");
				_this.cleanClasses();

				$text.show();
				$drop.show();
				$progress.hide();

				/*
				 * Triggering afterUpload Event
				 */

				/**
				 * This event is triggered after a file is uploaded. Created with the ```Input.on("afterUpload", function(Input, status, response){})``` method.
				 * If the function returns false it will cancel the update process.
				 * @param {Object} input - Reference to the Input.
				 * @param {Boolean} status - The upload process status: true is success and false is failure.
				 * @param {Object} response - If the operation was a success, it could return the response text or an object if the response is a JSON structure. If the operation returns an error, then this will contain the operation JavaScript object.
				 * @event Input#Event:afterUpload
				 */
				eventManager.dispatch("afterUpload", _this, true, responseObject);


			} else if (xhr.readyState == 4 && xhr.status != 200) {
				/*
				 * If an error occurs the event afterUpload is triggered.
				 */
				console.log("Silk - Error during field " + _this.columnID + " upload.")
				eventManager.dispatch("afterUpload", _this, false, xhr);
			}

			$progress.find("div").css("width", "0%");

		};
		xhr.open('POST', uploadURL, true);
		xhr.send(formData);

	};

	/**
	 * Clears the input value
	 */
	this.clear = function(){
		let initMode = this.getMode();
		this.setValue("")
		this.setPreviousValue("");
		this.setMode(initMode);
	}
	
	/*
	 * Initializes the input
	 */
	this.initInput = function() {

		if (target == "") {
			$("#" + id).replaceWith(getHtmlElement());
			if (block) $("#" + id).after("<br>");
		} else {
			$("#" + target).append(getHtmlElement());
			if (block) $("#" + target).append("<br>");
		}

		this.$input = $("#" + id);
		this.$dataField = this.$input.find('.silk-input-value');


		$label = this.$input.find('.silk-input-label');
		$text = this.$input.find('.silk-input-text');
		$value = this.$input.find('.silk-input-value');
		$description = this.$input.find('.silk-input-description');

		if (type != "hidden" && label != "") $label.html(label.replaceAll("</p>", "<br/></p>").replace(/<[\/]{0,1}(p)[^><]*>/ig, ""));
		if (type != "hidden" && description != "") $description.html(description);

		if (type == "hidden") $value = this.$input;
		if (type == "numeric" || type == "integer" || type == "decimal") $value.css("text-align", "right");
		if (type == "html") $text.addClass("silk-input-text-html");

		if ($text.hasClass("form-control")) $text.css("display", "block");

		if (maxLength !== "") {
			$value.keydown($.proxy(function(e) {
				if (this.getValue().length > getNumber(maxLength) - 1) e.preventDefault();
			}, this))
		}

		/*
		 * set input name property
		 */
		$value.attr("name", id);

		/*
		 * Set keyup in the input
		 */
		$value.keyup($.proxy(function(e) {

			var value = $value.val();

			if (value == "" || value == undefined) {
				$text.html("&nbsp;");
				this.cleanClasses()
			} else {
				this.validate();
				$text.text(value);
			}

			/*
			 * Triggers a form change everytime the user presses a key
			 */
			if (form != undefined) {
				form.setInputMode(true, false);
				form.dispatchOnChange(this);
			}

			/**
			 * This event is triggered at input's keyboard keyup event. Created with the ```Input.on("keyup", function(even,Input){})``` method.
			 * @param {Object} event - The Keyboard event.
			 * @param {Object} Input - Reference to the Input.
			 * @event Input#Event:keyup
			 */
			eventManager.dispatch("keyup", e, this);

			$value.removeClass("silk-input-error");

			if (timer > 0) {
				clearTimeout(inputTimer);
				inputTimer = setTimeout($.proxy(function() {

					/**
					 * This event triggered when the input's data entry timer concludes. Created with the ```Input.on("timer", function(value, Input){})``` method.
					 * @param {String} value - The input stored value.
					 * @param {Object} Input - Reference to the Input.
					 * @event Input#Event:timer
					 */
					eventManager.dispatch("timer", this.getValue(), this);

				}, this), timer);
			}

		}, this));

		$value.keydown($.proxy(function(e) {

			/**
			 * This event is triggered at input's keyboard keydown event. Created with the ```Input.on("keydown", function(even,Input){})``` method.
			 * @param {Object} event - The Keyboard event.
			 * @param {Object} Input - Reference to the Input.
			 * @event Input#Event:keydown
			 */
			var keyResult = eventManager.dispatch("keydown", e, this);

			if (keyResult == undefined) keyResult = true;

			if (keyResult == false) {
				e.preventDefault();
				return false;
			}

		}, this));

		if (type == "date" || type == "time" || type == "datetime") {

			if (type == "date") {
				$value.datetimepicker({
					format: 'mm/dd/yyyy',
					minView: 2,
					fontAwesome: true,
					autoclose: true
				});
			}

			if (type == "time") {
				$value.datetimepicker({
					format: 'H:ii P',
					startView: 1,
					minView: 0,
					maxView: 1,
					showMeridian: true,
					todayBtn: false,
					fontAwesome: true,
					formatViewType: 'time',
					autoclose: true
				});
			}

			if (type == "datetime") {
				$value.datetimepicker({
					format: 'mm/dd/yyyy H:ii P',
					startView: 2,
					minView: 0,
					maxView: 4,
					showMeridian: true,
					fontAwesome: true,
					autoclose: true
				});
			}

			$value.on("changeDate", function(e) {
				$value.val($(this).val());
				$text.text($(this).val());
			});
		};

		/*
		 * Fill select's options using the stringList variable.
		 */
		if (type == "select" && dataSource == "") {
			this.setStringList();
		};

		/*
		 * Fill options check boxes using the stringList variable.
		 */
		if (type == "options" && dataSource == "") {
			this.setStringList();
		};

		/*
		 * Fill raiod check boxes using the stringList variable.
		 */
		if (type == "radio" && dataSource == "") {
			this.setStringList();
		};


		/*
		 * Binds the click event to input type button
		 */
		if (type == "button") {
			$value.on('click', $.proxy(function() {
				if (this.getMode()) {

					/**
					 * This event is triggered when a input type 'button' is clicked in data entry mode. Created with the ```Input.on("click", function(Input){})``` method.
					 * @param {Object} Input - Reference to the Input.
					 * @event Input#Event:click
					 */
					eventManager.dispatch("click", this);

					if (targetPage != "") window[targetPage].show();

				}

			}, this));
		};

		/*
		 * Fill options check boxes using the stringList variable.
		 */
		if (type == "code") {
			$value.on('keydown', function(e) {
				if (e.key == 'Tab') {
					e.preventDefault();
					var start = this.selectionStart;
					var end = this.selectionEnd;

					// set textarea value to: text before caret + tab + text after caret
					this.value = this.value.substring(0, start) +
						"\t" + this.value.substring(end);

					// put caret at right position again
					this.selectionStart =
						this.selectionEnd = start + 1;
				}
			});
		};

		/*
		 * Code Editors
		 */
		if (type == "sql") {
			this.codeEditor = new SqlEditor(id + "_code");
			this.codeEditor.setReadOnly(true);
		}

		if (type == "js") {
			this.codeEditor = new JSEditor(id + "_code");
			this.codeEditor.setReadOnly(true);
		}

		if (type == "css") {
			this.codeEditor = new CssEditor(id + "_code");
			this.codeEditor.setReadOnly(true);
		}

		if (type == "xml") {
			this.codeEditor = new XmlEditor(id + "_code");
			this.codeEditor.setReadOnly(true);
		}

		if (type == "xhtml") {
			this.codeEditor = new HtmlEditor(id + "_code");
			this.codeEditor.setReadOnly(true);
		}

		/*
		 * Binds click events to file buttons.
		 */
		if (type == "file") {

			$drop = this.$input.find('.silk-input-drop');
			$progress = this.$input.find('.silk-input-progress');
			$browse = this.$input.find('.silk-input-browse');

			if (filePreview) this.$filePreviewBt = $("#" + id + "_previewBt");
			if (fileDownload) this.$fileDownloadBt = $("#" + id + "_downloadBt");

			$drop.on('click dragenter dragover dragleave drop', function(e) {
				e.preventDefault();
				e.stopPropagation();
			})

			$drop.on('click', function() {
				$browse.val("");
				$browse.trigger("click");
			})

			$drop.on('drop', $.proxy(function(e) {
				handleDrop(e.originalEvent, this);
			}, this))

			$browse.change($.proxy(function(e) {
				handleFiles(e.currentTarget.files, this);
			}, this));

			if (filePreview) {
				this.$filePreviewBt.on('click', $.proxy(function() {
					/**
					 * This event is triggered when input's preview button is clicked. Created with the ```Input.on("clickPreview", function(){})``` method.
					 * @event Input#Event:clickPreview
					 */
					eventManager.dispatch("clickPreview");
				}, this));
			}

			if (fileDownload) {
				this.$fileDownloadBt.on('click', $.proxy(function() {
					/**
					 * This event is triggered when input's download button is clicked. Created with the ```Input.on("clickDownload", function(){})``` method.
					 * @event Input#Event:clickDownload
					 */
					eventManager.dispatch("clickDownload");
				}, this));
			}

		};

		/*
		 * Bind change even to input
		 */
		$value.change($.proxy(function() {

			var recordIndex = $value.find("option:selected").attr("recordIndex");
			if (recordIndex == undefined) {
				this.selectedIndex = $value.prop("selectedIndex");
			} else {
				this.selectedIndex = getNumber(recordIndex);
			}

			/**
			 * This event is triggered when the Input's value has changed. Created with the ```Input.on("change", function(Input){})``` method.
			 * @param {Object} Input - Reference to the Input.
			 * @event Input#Event:change
			 */
			eventManager.dispatch("change");

			if (form != undefined) {
				form.setInputMode(true, false);
				form.dispatchOnChange(this);
			}

		}, this));

		// Creates initial values if define by JavaScript object
		if (initValue != undefined) {
			this.setValue(initValue);
		} else {
			this.setValue("");
		}

		/**
		 * This event is triggered after the Input element has been initialized. Created with the ```Input.on("afterInit", function(Input){})``` method.
		 * @param {Object} Input - Reference to the Input.
		 * @event Input#Event:afterInit
		 */
		eventManager.dispatch("afterInit", this);

		this.setMode(mode);

	}

	if (target != "") this.initInput();

};
