/*
 * Copyright (c) 2025 OopsClick LLC. All rights reserved.
 * This work is licensed under the O'Saasy License Agreement, a copy of which can be
 * found in the LICENSE file in the root directory of this project or at https://silkbuilder.com/core-license.
 */

/**
 * Returns a LogicGrid instance.
 *
 * @class
 * @classdesc
 * The LogicGrid Class provides properties, methods, and events to interface with the Objects generated by the ```<silk:LogicGrid>``` tag.
 *
 * @constructor
 * @param {String} id - The LogicGrid unique identifier.
 */
var LogicGrid = function(id) {
	this.className = "LogicGrid";

	this.id = id;

	var actionArray = [];
	var options = {};
	var debug = false;

	/*
	 * 
	 */
	this.setOptions = function(opt) {
		options = opt;
	}

	/*
	 * 
	 */
	this.getOptions = function() {
		return options;
	}

	/**
	 * Activates the debuging messaging
	 * 
	 * @param {Boolean} debug - The logic
	 */
	this.setDebug = function(dbg) {
		debug = dbg;
	}

	/**
	 * Add an element and its criteria to the LogicGrid processor.
	 * 
	 * @param element the 
	 * @param criteria
	 */
	this.addAction = function(element, criteria) {
		let actionObject = {};
		actionObject["element"] = element;
		actionObject["criteria"] = criteria;
		actionArray.push(actionObject);
	}

	/**
	 * Returns the result of checking the the provided criteria.
	 * @param {Object} criteria - The criteria object to evualate.
	 * @returns {Boolean}
	 */
	this.getStatus = function() {

		if (debug && arguments.length > 0) console.log("parameters: ", arguments);

		let criteria = arguments[0];

		if (criteria == undefined) return false;
		if (typeof criteria !== 'string') return false;
		if (criteria == "") return false;

		criteria = criteria.replaceAll(" ", "");

		let status = true;
		let negation = false;

		let criteriaArray = criteria.trim().split(",");
		for (x in criteriaArray) {
			status = true;
			let partArray = criteriaArray[x].split(":");
			for (y in partArray) {

				y = getNumber(y);

				let queryKey = partArray[y];
				if (debug) console.log("Value searched: " + queryKey);

				/*
				 * Checking for negation statment
				 */
				if (queryKey.indexOf("!") > -1) {
					if (debug) console.log("Negation activated");
					negation = true;
					queryKey = queryKey.replace("!", "");
				}

				/*
				 * Checking if all options are accepted
				 */
				if (queryKey == "*") {
					if (debug) console.log("Accept any value");
					status = status && true;
					negation = false;
					continue;
				}



				let gridGroup = options.gridLabels[y];
				if (debug) console.log("Search group:" + gridGroup);

				let gridDP = options[gridGroup + "DP"];
				if (debug) console.log("DP:", gridDP);

				let gridKey = options[gridGroup + "Key"];
				if (debug) console.log("DP search key:" + gridKey);

				let gridItem = gridDP.getIndexItemOf(gridKey, queryKey);
				if (gridItem == undefined) {
					if (debug) console.log("Value not found in DP");
					status = false;
					negation = false;
					continue;
				}

				let gridValue = gridItem[gridDP.getPkColumn()]
				if (gridValue == undefined) {
					if (debug) console.log("PK column does not exist");
					status = false;
					negation = false;
					continue;
				}
				if (debug) console.log("ID value found: " + gridValue);

				let queryValue = null;
				if ((y + 1) < arguments.length) {
					queryValue = arguments[y + 1];
					if (debug) console.log("Selected value from parameter " + (y + 1) + " : " + queryValue);
				}
				if (queryValue == null) {
					queryValue = eval(options.gridElements[y]);
					if (debug) console.log("Selected value: " + queryValue);
				}


				let queryStatus = gridValue == queryValue;
				if (debug) console.log("Logic status: " + queryStatus);

				/*
				 * Appliying negation
				 */
				if (negation) {
					queryStatus = !queryStatus;
					negation = false;
					if (debug) console.log("Negation change status: " + queryStatus);
				}

				status = status && queryStatus;

				if (debug) {
					console.log("Group status: " + status);
					console.log("- - - - - - - - - - - - - - -");
				}

			}

			if (status) break;

		}

		return status;

	}

	/**
	 * Returns an array containing the list of loaded actions.
	 * @returns {Array}
	 */
	this.getActions = function() {
		return actionArray;
	}

	/**
	 * Executes the action in the loaded elements.
	 */
	this.run = function() {
		for (x in actionArray) {
			let item = actionArray[x];
			let status = this.getStatus(item.criteria);
			if (typeof item.element === "function") item.element(status);
			if (typeof item.element === "object") item.element.toggle(status);
		}
	};

}
