/*
 * Copyright (c) 2025 OopsClick LLC. All rights reserved.
 * This work is licensed under the O'Saasy License Agreement, a copy of which can be
 * found in the LICENSE file in the root directory of this project or at https://silkbuilder.com/core-license.
 */

/**
 * Returns a Modal instance. 
 * @class
 * @classdesc The Modal Class provides properties, methods, and events to interface with the HTML tags generated by the ```<silk:Modal>``` tag.
 *
 * @constructor
 * @param {String} id - Modal's name or unique identifier.
 *
 * @property {Object} $modal - jQuery object referencing the modal HTML tag.
 * @property {Object} $header - jQuery object referencing the modal's header HTML tag.
 * @property {Object} $body - jQuery object referencing the modal's body HTML tag.
 * @property {Object} $footer - jQuery object referencing the modal's footer HTML tag.
 */
var Modal = function(id) {

	/* $modal : Public property */
	this.$modal = undefined;

	/* $header : Public property */
	this.$header = undefined;

	/* $body : Public property */
	this.$body = undefined;

	/* $body : Public property */
	this.$footer = undefined;

	/*
	 * Setting eventManager instance
	 */
	var eventManager = new EventManager();

	/**
	 * Load events to respond to the Modal's interactions. To set an event, use this code: ```Modal.on(<eventName>, function(){<code>})```.
	 * @param {String} eventName - The event's name.
	 * @param {function} eventFunction - The function to be triggered.
	 */
	this.on = eventManager.on;

	/**
	 * Shows or opens the modal dialog.
	 * @function
	 */
	this.show = function(left, top, width) {
		/**
		 * This event is triggered before the Modal is shown. If the function returns 'false', the modal is not shown. Created with the ```Modal.on("beforeShow", function(){})``` method.
		 * @event Modal#Event:beforeShow
		 */
		if( !ifUndefined(eventManager.dispatch("beforeShow"),true) ) return;

		if (left != undefined) {
			this.$modal.children().first().removeAttr("class");
			this.$modal.find(".modal-content").css("top", top + "px");
			this.$modal.find(".modal-content").css("left", left + "px");
			if (width != undefined) this.$modal.find(".modal-content").css("width", width + "px");
		}

		modalObject.show();
	};

	/**
	 * Hides the modal dialog.
	 * @function
	 */
	this.hide = function() {
		modalObject.hide();
	};

	/**
	 * Opens the modal dialog. Similar to show.
	 * @function
	 */
	this.open = function() {
		this.show();
	}

	/**
	 * Closes the modal dialgo. Similar to hide.
	 * @function
	 */
	this.close = function() {
		this.hide();
	}

	/**
	 * Sets the header title of the modal dialog.
	 * @function
	 * @param {String} title - The new modal's header title.
	 */
	this.setTitle = function(title) {
		this.$modal.find(".modal-title").text(title);
	}

	/**
	 * Gets the title of the modal dialog.
	 * @function
	 */
	this.getTitle = function() {
		this.$modal.find(".modal-title").html();
	}

	/**
	 * Sets the HTML content of the modal dialog.
	 * @function
	 * @param {String} content - The new content in HTML format.
	 */
	this.setBody = function(content) {
		this.$modal.find(".modal-body").html(content);
	}

	/*
	 * Added for Page compatibility
	 */
	this.$page = undefined;
	this.mask = function() { }
	this.goBack = function() {
		this.$modal.modal('hide');
	};
	//-------------------------- End compatibility with page

	var modalObject = null;

	this.initModal = function() {
		this.$modal = $('#' + id);
		this.$page = this.$modal;
		this.$header = this.$modal.find(".modal-header");
		this.$body = this.$modal.find(".modal-body");
		this.$footer = this.$modal.find(".modal-footer");

		modalObject = new bootstrap.Modal(document.getElementById(id));

		$('#' + id + "_closeBt").on("click", $.proxy(function() {

			/**
			 * The event is triggered before the Modal is closed. Created with the ```Modal.on("beforeClose", function(){})``` method. If the function returns *false*, the modal will not close.
			 * @event Modal#Event:beforeClose
			 */
			if( ifUndefined(eventManager.dispatch("beforeClose"), true) ){
				this.close();
			}

		}, this));


		this.$modal.on('shown.bs.modal', $.proxy(function(e) {

			/**
			 * The event is triggered when the Modal is shown. Created with the ```Modal.on("afterShow", function(){})``` method.
			 * @event Modal#Event:afterShow
			 */
			eventManager.dispatch("afterShow");

			/**
			 * The event is triggered when the Modal is shown. This is similar to the event *afterShow*. Created with the ```Modal.on("show", function(){})``` method.
			 * @event Modal#Event:show
			 */
			eventManager.dispatch("show");

		}, this));

		this.$modal.on('hidden.bs.modal', $.proxy(function(e) {

		/**
		 * The event is triggered when the Modal is hidden or closed. Created with the ```Modal.on("afterClose", function(){})``` method.
		 * @event Modal#Event:afterClose
		 */
		eventManager.dispatch("afterClose");

			
		/**
		 * The event is triggered when the Modal is hidden or closed. This is similar to the *beforeClose* event. Created with the ```Modal.on("close", function(){})``` method.
		 * @event Modal#Event:close
		 */
		eventManager.dispatch("close");

		}, this));

		/*
		 * Process help button.
		 */
		if ($("#" + id + " .silk-help").length > 0) {
			$("#" + id + " .silk-head-help").show();
		} else {
			$("#" + id + " .silk-head-help").remove();
		}

	}

	this.resize = function() { };

};