/*
 * Copyright (c) 2025 OopsClick LLC. All rights reserved.
 * This work is licensed under the O'Saasy License Agreement, a copy of which can be
 * found in the LICENSE file in the root directory of this project or at https://silkbuilder.com/core-license.
 */

/** 
 * Returns a Page instance.
 * @class
 * @classdesc The SilkPage Class provides properties, methods, and events to interface with the HTML tags generated by the ```<silk:Page>``` tag.
 *
 * @constructor
 * @param {String} id Unique identifier.
 * @param {String} stage The stage's code to be used in the layout scheme.
 * @param {Integer} width Deprecated.
 * @param {String} screenSetup The layout scheme.
 * @param {String} returnPage The name of the page to return when clicking the back button.
 * @param {String} tabsNav The name of the TabsNav object holding the page
 *
 * @property {String} id - The page's name and unique identifier.
 * @property {Object} $page - jQuery object referencing the page HTML tag.
 * @property {Object} $content - jQuery object referencing the page HTML tag.
 * @property {Boolean} isSingle - Indicates if the page is being displayed alone.
 *
 */
var Page = function(id, stage, width, screenSetup, returnPage, tabsNav) {

	/* id : Public property */
	this.id = id;

	/* $page : Public property */
	this.$page = null;

	/* $content : Public property */
	this.$content = null;

	this.stage = stage;
	this.width = width;
	this.layout = screenSetup.split("|");
	this.masked = false;
	this.index = -1;
	this.$backButton = null;

	/* isSingle : Public property */
	this.isSingle = false;

	this.headerWidth = 0;
	this.tabsNav = tabsNav;

	/*
	 * Setting event manager : Private Property
	 */
	var eventManager = new EventManager();

	/**
	 * Load events to respond to the page's interactions. To set an event, use this code: ```Page.on(<eventName>, function(){<code>})```.
	 * @param {String} eventName - The event's name.
	 * @param {function} eventFunction - The function to be triggered.
	 */
	this.on = function(eventName, eventFunction) {
		eventManager.on(eventName, eventFunction);
	}

	/**
	 * Returns the page's name or unique identifier.
	 * @returns {String} Unique identifier.
	 */
	this.getID = function() {
		return this.id;
	}

	/**
	 * Executes the resizing of pages referencing the currently active page.
	 */
	this.resize = function() {

		/*
		 * Defines the application with checking in screen is running as root element or a child element.
		 */
		if ($(".screen").parent().prop("tagName") == "BODY") {
			let bodyHeight = $(".screen").parent().innerHeight();
			let screenHeaderHeight = ifUndefined($(".silk-screen-header").outerHeight(), 0);
			let screenFooterHeight = ifUndefined($(".silk-screen-footer").outerHeight(), 0);
			let pageHeaderHeight = this.$page.find(".silk-head").outerHeight();

			let padding = getNumber(this.$content.css("padding-top")) + getNumber(this.$content.css("padding-bottom"));
			let margin = getNumber(this.$content.css("margin-top")) + getNumber(this.$content.css("margin-bottom"));
			let border = getNumber(this.$content.css("border-top-width")) + getNumber(this.$content.css("border-bottom-width"));

			//console.log(this.id+" >", bodyHeight, pageHeaderHeight, screenHeaderHeight, screenFooterHeight, padding, margin, border );

			let calculatedHeight = bodyHeight - pageHeaderHeight - screenHeaderHeight - screenFooterHeight - padding - margin - border;

			this.$content.height(calculatedHeight);

		} else {
			/*
			 * Customs location, not in the body
			 */
			this.$content.css("height", "");
		}

		/*
		 * Process a tabNavs positioning.
		 */
		if (this.tabsNav != "null") {
			if (window[this.tabsNav].activePage == this.id) {
				if (this.$page.find(".silk-navbar").length != 0) {

					window[this.tabsNav].$tabs.width(1);

					this.headerWidth = 0;
					this.$page.find(".silk-navbar").children().each($.proxy(function(index, element) {
						var $element = $(element);

						if ($element.hasClass("btn")) {
							this.headerWidth += $element.width();
						}
					}, this));
					window[this.tabsNav].$tabs.width(this.$page.find(".silk-navbar").width() - this.headerWidth - 10);
					window[this.tabsNav].relocateTab();
				}
			}
			window[this.tabsNav].setBarWidth();
		}

	}

	/**
	 * Makes a page visible and the active one.
	 */
	this.show = function() {

		/*
		 * Sets current focused page
		 */
		silk.focusedPage = this.id;

		/*
		 * Initializes current layout values base on screen size
		 */
		var currentLayout = this.layout[silk.getScreenMode()].split(",");
		var aStages = new Array();
		var aWidth = new Array();
		var aBack = new Array();

		/*
		 * Parses selected layout distribution data
		 */
		currentLayout.forEach(function(element) {
			var parts = (element + "::").split(":");
			aStages.push(callFunction(parts[0]));
			aWidth.push(callFunction(parts[1]));
			aBack.push(callFunction(parts[2]));
		});



		/*
		 * Applies layout to pages.
		 * It will display pages included in the layout, and hide others.
		 * It will setup the page's width.
		 * will also show the back button is selected.
		 */
		var visiblePages = new Array();
		for (var x in silk.pageList) {
			var selectedPage = silk.pageList[x]
			var position = aStages.indexOf(silk.pageList[x].stage);

			selectedPage.$page.removeClass("silk-page-border");

			/*
			 * If the page is part of a TabNav, then the activePage is selected to be displayed.
			 * If the current page is part of a TabNav it is not processed.
			 */
			var targetTabsNav = silk.pageList[x].tabsNav;
			if (targetTabsNav != "null" && this.tabsNav == "null") {
				if (selectedPage.id == window[targetTabsNav].activePage) {
					// if stage was not found on stage list, then the first TavNav element is used.
					if (position == -1) {
						position = aStages.indexOf(window[window[targetTabsNav].pageList[0].pageName].stage);
					}
				} else {
					position = -1;
				}
			}

			if (position > -1) {

				selectedPage.$page.show();

				selectedPage.$page.attr("width", aWidth[position]);

				if (aBack[position] == "b") {
					selectedPage.$backButton.show();
				} else {
					selectedPage.$backButton.hide();
				}
				visiblePages.push(x);
			} else {
				selectedPage.$page.hide();
			}
		}
		for (var x = 0; x < (visiblePages.length - 1); x++) {
			var page = silk.pageList[visiblePages[x]];
			page.$page.addClass("silk-page-border");
			page.resize();

		}

		this.isSingle = visiblePages.length == 1;

		this.resize();

		/*
		 * Moving TabsNav object to page header.
		 */
		if (this.tabsNav != "null") {
			if (this.$page.find(".silk-navbar").length != 0) {
				this.$page.find(".silk-navbar").append(window[this.tabsNav].$tabs);
				window[this.tabsNav].setActive(this.id);
			}
		}

		/*
		 * Trigger onShow event
		 */

		/**
		 * The event is triggered when the page becomes active. Created with the ```Page.on("show", function(){})``` method.
		 * @event Page#Event:show
		 */
		eventManager.dispatch("show");

		/*
		 * Call tables in page to sync header size
		 */
		this.$page.find(".silk-table").each(function() {
			var tableID = $(this).attr("id");
			window[tableID].syncHeader();
		});

	}

	/**
	 * Executes the page masking. The masking process isolates the page from other pages.
	 * @param {boolean} mode - If true, the page is masked; if false, the page is unmasked. 
	 */
	this.mask = function(mode) {
		if (mode == undefined) {
			this.masked = !this.masked;
		} else {
			this.masked = mode;
		}
		setTimeout($.proxy(function() { this.maskProcess(); }, this), 300);
	}

	this.maskProcess = function() {
		if (silk.transitioning) {
			setTimeout($.proxy(function() {
				this.maskProcess();
			}, this), 100);
			return;
		}

		if (this.masked) {
			if (this.$page.position().left > 10) {
				$("#coverLeft").width(this.$page.position().left);
				$("#coverLeft").fadeIn(200);
			} else {
				$("#coverLeft").fadeOut(200);
			}
			var left = this.$page.position().left + this.$page.width();
			if ((left + 10) < silk.$screen.width()) {
				$("#coverRight").width(silk.$screen.width() - left);
				$("#coverRight").css('left', left);
				$("#coverRight").fadeIn(200);
			} else {
				$("#coverRight").fadeOut(200);
			}
		} else {
			$("#coverLeft").fadeOut(200);
			$("#coverRight").fadeOut(200);
		}
	}

	/**
	 * Returns to the previous linked page, or to the set returned page.
	 */
	this.goBack = function() {
		if (returnPage == "null") {
			if (this.index > 0) silk.pageList[this.index - 1].show()
		} else {
			window[returnPage].show();
		}
	}

	/**
	 * Sets the page title if the page is using a header.
	 * @param {String} title - The new page header's title.
	 */
	this.setTitle = function(title) {
		this.$page.find(".silk-navbar-title").text(title);
	}

	/**
	 * Gets the page's title if the page is using a header.
	 * @returns {String} The page header's title.
	 */
	this.getTitle = function() {
		return this.$page.find(".silk-navbar-title").html();
	}

	/**
	 * Return if the page is visible or not.
	 * @returns {Boolean} The visible status
	 */
	this.getVisible = function() {
		return !(this.$page.css("display") == "none");
	}

	this.initPage = function() {

		this.$page = $("#" + this.id);
		this.$content = this.$page.find(".silk-content");

		/*
		 * Set back button action
		 */
		var buttonID = id + "_backBt";
		this.$backButton = $("#" + buttonID);

		this.$backButton.click($.proxy(function() {
			this.goBack();
		}, this))

		/*
		 * Process help button.
		 */
		if ($("#" + id + " .silk-help").length > 0) {
			$("#" + id + " .silk-head-help").show();
		} else {
			$("#" + id + " .silk-head-help").remove();
		}

		/*
		 * Set tabNav title
		 */
		if (this.tabsNav != "null") {
			if (this.$page.find(".silk-navbar-title").length != 0) {
				var titleHtml = this.$page.find(".silk-navbar-title").html().trim();
				console.lo
				this.$page.find(".silk-navbar-title").empty();
				window[this.tabsNav].addPage(this.id, titleHtml);
			}
		}

	}


}
