/*
 * Copyright (c) 2025 OopsClick LLC. All rights reserved.
 * This work is licensed under the O'Saasy License Agreement, a copy of which can be
 * found in the LICENSE file in the root directory of this project or at https://silkbuilder.com/core-license.
 */

/** 
 * Returns a Pagination instance. 
 * @class
 * @classdesc The Pagination Class provides properties, methods, and events to interface with the HTML tags generated by  the ```<silk:Pagination>``` tag.
 *
 * @constructor
 * @param {String} id - Unique identifier.
 * @param {Integer} size=500 - The number of target items per page.
 * @param {Integer} pages=10 - The number of pages listed in the pagination bar.
 * @param {String} label=Records - Optional pagination label.
 *
 * @property {Object} $pagination - jQuery object referencing the pagination HTML tag.
 * @property {Integer} currentPage - The index of the selected page
 * @property {Integer} totalRows - The total rows returned by the query.
 * @property {Integer} totalPages - The total generated pages.
 * @property {Integer} $pageStartRow - The page starting the pages list view.
 * @property {Integer} $pageSize - The number of items per page.
 * @property {Integer} $showPages - Number of pages to be displayed
 * @property {Object} $leftArrow - jQuery object referencing the pagination's left arrow.
 * @property {Object} $rightArrow - jQuery object referencing the pagination's right arrow.
 *
 */
var Pagination = function(id, size, pages, label){
	this.id = id;
	this.$pagination;
	this.currentPage = 0;
	this.totalRows = 0;
	this.totalPages = 0;
	this.pageStartRow = 0;
	this.pageSize = size;
	this.showPages = pages;
	
	this.groupSelected = 0;
	this.groupTotal = 0;
	this.$leftArrow;
	this.$rightArrow;
	this.leftLimit = 0;
	this.rightLimit = 0;
	
	/*
	 * Setting event manager
	 */
	var eventManager = new EventManager();
	/**
	 * Load events to respond to the pagination's interactions. To set an event, use this code: ```Pagination.on(<eventName>, function(){<code>})```.
	 * @param {String} eventName - The event's name.
	 * @param {function} eventFunction - The function to be triggered.
	 */
	this.on = eventManager.on;
	
	if( label==undefined ) label="Records";
	
	/**
	 * Method to clean the pagination container.
	 */
	this.clean = function(){
		this.pageStartRow = 0;
		this.$pagination.html("");
		
	}
	
	this.load = function(totalRows, totalPages){
		this.clean();
		
		if( totalRows==0 ) return;
		
		this.totalRows = totalRows;
		this.totalPages = totalPages;
		var totalFormated = getFormattedValue(totalRows,"numeric")
		var html = "";
		
		if( label!="none")	html += "<li class='page-item disable'><span class='page-link'  >"+totalFormated+" "+label+"</span></li>";
		
		html += "<li class='page-item left-arrow' style='display:none;'><span class='page-link'>&#9664;</span></li>";
		
		for( x=0; x<this.totalPages; x++ ){
			html +=  "<li class='page-item "+ ((x==0)? "active" : "")+"' style='display:none;' >"
							+"<a href='#' data-pageStartRow='"+(this.pageSize*x)+"' data-index='"+x+"' class='page-link' >"
								+(x+1)
							+"</a>"
						+"</li>";
		}
		
		html += "<li class='page-item right-arrow'  style='display:none;' ><span class='page-link'  >&#9654;</span></li>";
		this.$pagination.html(html);
		
		this.$leftArrow = this.$pagination.find(".left-arrow");
		this.$rightArrow = this.$pagination.find(".right-arrow");
		
		this.groupSelected = 0;
		this.groupTotal = Math.ceil(this.totalPages/this.showPages);
		this.activateItems(0);
		
	}
	
	this.activateItems = function(){
		this.$leftArrow.toggle( this.groupSelected>0 );
		this.$rightArrow.toggle( this.groupSelected<(this.groupTotal-1) );
		
		this.leftLimit = this.groupSelected*this.showPages;
		this.rightLimit = (this.groupSelected*this.showPages)+this.showPages;
		
		this.$pagination.find('a').each($.proxy(function(index,element){
			var $item = $(element);
			$item.parent().toggle( index >= this.leftLimit && index < this.rightLimit );
			
		},this));
	}
	
	this.initPagination = function(){
		this.$pagination = $("#"+this.id);
		
		this.$pagination.on('click','a',$.proxy(function(element){
			var $item = $(element.currentTarget);
			if( $item.parent().hasClass("active") ) return;
			
			this.pageStartRow = getNumber( $item.attr("data-pageStartRow") );
			this.currentPage = getNumber( $item.attr("data-index") );
			
			this.$pagination.find("li").removeClass("active");
			$item.parent().addClass("active");
			
			/**
			 * The event is triggered when a page button is clicked. Created with the ```Pagination.on("click", function(){})``` method.
			 * @event Pagination#Event:click
			 */
			eventManager.dispatch("click");
			
		},this));
		
		this.$pagination.on('click','.left-arrow',$.proxy(function(element){
			if( this.groupSelected<=0 ) return;
			this.groupSelected--;
			this.activateItems(this.groupSelected);
		},this));
		
		this.$pagination.on('click','.right-arrow',$.proxy(function(element){
			if( this.groupSelected>=this.groupTotal ) return;
			this.groupSelected++;
			this.activateItems(this.groupSelected);
		},this));
		
	}
	
};
