/*
 * Copyright (c) 2025 OopsClick LLC. All rights reserved.
 * This work is licensed under the O'Saasy License Agreement, a copy of which can be
 * found in the LICENSE file in the root directory of this project or at https://silkbuilder.com/core-license.
 */

/** 
 * Returns a Tile instance. 
 * @class
 * @classdesc The Tab Class provides properties, methods, and events to interface with the HTML generated by the ```<silk:Tag>``` tag.
 *
 * @constructor
 * @param {String} id - Unique identifier.
 * @param {Object} option - Object containing the configuration.
 *
 */
var Tab = function(id, options) {

	//var dataSource		= ifUndefined( options["dataSource"],undefined);

	var tabs = new Array();

	this.index = -1;
	this.$tab;
	this.$content;

	/*
	 * Will lauch the on click event.
	 */	
	var callClickTrigger = true;

	/*
	 * Setting event manager
	 */
	var eventManager = new EventManager();

	/**
	 * Load events to respond to the Tab's interactions. To set an event, use this code: ```Tab.on(<eventName>, function(){<code>})```.
	 * @param {String} eventName - The event's name.
	 * @param {function} eventFunction - The function to be triggered.
	 */
	this.on = eventManager.on;

	/**
	 * Show the tab component.
	 */
	this.show = function() {
		this.$tab.show();
	};

	/**
	 * Hiddes the tab component.
	 */
	this.hide = function() {
		this.$tab.hide();
	};

	/**
	 * Toggles the component's visibility. If a parameter is provided, *true* shows the component, *false* hides the component.
	 * @param {Boolan} value - The logic value.
	 */
	this.toggle = function(value) {
		if (value == undefined) {
			this.$tab.toggle();
			return;
		}
		this.$tab.toggle(value);
	};

	/**
	 * Returns the array containing the tabs.
	 * @returns {Array}
	 */
	this.getTabs = function(index) {
		if (index == undefined) return tabs;
		return tabs[index];
	};

	/**
	 * Returns the number of tabs
	 * @returns {Integer}
	 */
	this.size = function() {
		return tabs.length;
	}

	/**
	 * Activates a tab based on the provided index
	 * @param {Integer} index - The tab index
	 * @param {Boolean} execClick - (Optional) If false the on click event will not be called.
	 */
	this.setIndex = function(index, execClick) {
		if( execClick===false ) callClickTrigger = false;
		if (index == undefined) index = this.index;
		tabs[index].$tab.trigger("click");
		this.index = index;
	};

	/**
	 * Returns the selecte tab item.
	 * @returns {Object}
	 */
	this.getSelectedTab = function() {
		return tabs[this.index];
	};

	/**
	 * Returns the index of the tab with the provided id.
	 * @param {Integer} id - The tab's id.
	 * @returns {Integer}
	 */
	this.indexOf = function(id) {
		for (var x in tabs) {
			if (tabs[x].id == id) {
				return x;
			}
		}
		return -1;
	};

	/**
	 * Returns the active or selected tab object. If a parameter is provided, it searches for the tab using the provided index or ID and returns the tab object. 
	 * @parma {Integer|String} x - The tab index or id. If not provided, uses the selected.
	 * @returns {Object}
	 */
	this.getActive = function(x) {
		x = this.getTabIndex(x);
		if (x == -1) return false;
		return tabs[x].$tab.hasClass("active");
	};

	/**
	 * Return if the tab is visible
	 * @parma {Integer|String} x - The tab index or id. If not provided uses the selected tab.
	 * @returns {object}
	 */
	this.getVisible = function(x) {
		x = this.getTabIndex(x)
		if (x == -1) return false;
		return tabs[x].$tab.is(":visible");
	};

	/**
	 * Show a tab item that is being hidden.
	 * @param {Integer|String} Tab index or id. If not provided uses the selected tab.
	 */
	this.showTab = function(x) {
		this.toggleTab(x, true);
	};

	/**
	 * Returns the selecte tab item.
	 * @parma {Integer|String} Tab index or id. If not provided uses the selected tab.
	 */
	this.hideTab = function(x) {
		this.toggleTab(x, false);
	};

	/**
	 * Toggles the tab item's visibility. If a parameter is provided, *true* shows the tab, *false* hides the tab.
	 * @param {Integer|String} x - The tab index or id. If not provided uses the selected tab.
	 * @param {Boolean} value - The logic value
	 */
	this.toggleTab = function(x, value) {
		x = this.getTabIndex(x)
		if (x == -1) return;

		if (value == undefined) {
			tabs[x].$tab.toggle();
			return;
		}

		tabs[x].$tab.toggle(value);
	};

	this.getTabIndex = function(x) {
		if (x == undefined) {
			x = this.index;
		} else {
			if (isNumeric(x)) {
				if (x > (tabs.length - 1)) x = -1;
			} else {
				let tid = x;
				x = this.indexOf(tid);
				if (x == -1) {
					console.log(id + ": No tab " + tid + " ID found.");
				}
			}
		}
		return getNumber(x);
	};

	/**
	 * Adds a new tab to the tab group. If other tabs exist, the tab will be added to the right of the last tab. It is automatically selected, unless the *silent* parameter is set to *true*. Returns the index of the newly created tab.
	 * @param {String} id - The tab's unique identifier
	 * @param {String} title - The tab's title
	 * @param {String} content - The tab's content
	 * @param {Boolean} silent - Optional. If set to true the tab will not get selected.
	 * @returns {Integer}
	 */
	this.addTab = function(id, title, content, silent) {

		if (title != undefined) {

			var tabHtml = ""
				+ "<button id='" + id + "_tab' class='nav-item nav-link silk-nav-link ' data-bs-toggle='tab' data-bs-target='#" + id + "' type='button' role='tab' aria-controls='" + id + "' aria-selected='' >"
				+ title
				+ "</button>";
			this.$tab.append(tabHtml);

			if (content == undefined) content = "";

			var contentHtml = ""
				+ "<div id='" + id + "' class='tab-pane silk-tab-pane fade ' role='tabpanel' aria-labelledby='" + id + "_tab'>"
				+ content
				+ "</div>";
			this.$content.append(contentHtml);

		}

		var item = new Object();
		item["id"] = id;
		item["$tab"] = $("#" + id + "_tab");
		item["$content"] = $("#" + id);
		tabs.push(item);

		var newIndex = tabs.length - 1;

		if (silent == undefined) {
			silent = true;
		} else {
			silent = false;
		}

		if (silent) {
			this.index = newIndex;
			this.setIndex(newIndex);
		}

		/**
		 * This event is triggered when a tab is added. Created with the ```Tab.on("add", function(){index});``` method.
		 * @event Tab#Event:add
		 */
		eventManager.dispatch("add", newIndex);


		return newIndex;
	};

	/**
	 * Removes the tab based on the provided index.
	 * @param {Integer} index - The index to be removed.
	 */
	this.removeTab = function(index) {
		tabs[index].$tab.remove();
		tabs[index].$content.remove();
		tabs.splice(index, 1);

		/**
		 * This event is triggered when a tab is removed. Created with the ```Tab.on("removed", function(){index});``` method.
		 * @event Tab#Event:removed
		 */
		eventManager.dispatch("removed", index);

		if (index == 0) {
			if (tabs.length > 0) {
				this.index = 0;
				this.setIndex();
			} else {
				this.index = -1;
			};
		} else {
			this.index = index - 1;
			this.setIndex();
		}

	};

	this.initTab = function() {

		this.$tab = $("#" + id);
		this.$content = $("#" + id + "_content");

		this.$tab.on("click", $.proxy(function(e) {

			let $element = $(e.target);

			if ($element.hasClass("close-icon")) return;

			if ($element.attr("role") != "tab") {
				$element = $element.parent();
			}

			if ($element.attr("id") == undefined) return;

			let id = $element.attr("id").replace("_tab", "");

			for (x in tabs) {
				if (tabs[x].id == id) {
					this.index = getNumber(x);
					break;
				}
			}

			let tabID = this.getTabs()[this.index].id;

			/**
			 * This event is triggered when the tab is clicked. Created with the ```Tab.on("click", function(index, tabID, clickTarget){});``` method.
			 * @event Tab#Event:click
			 */
			if( callClickTrigger ){
				eventManager.dispatch("click", this.index, tabID, e.target);
			}else{
				callClickTrigger  = true;
			}

		}, this));

		if (this.$tab.find("button").length > 0) this.index = 0;

	};

}
