/*
 * Copyright (c) 2025 OopsClick LLC. All rights reserved.
 * This work is licensed under the O'Saasy License Agreement, a copy of which can be
 * found in the LICENSE file in the root directory of this project or at https://silkbuilder.com/core-license.
 */

/**
 * Returns a Table instance.
 * @class
 * @classdesc The Table Class provides properties, methods, and events to interface with the HTML generated by the ```<silk:Table>``` tag.
 *
 * @constructor
 * @param {String} id - Unique identifier.
 * @param {Object} option - Object containing the configuration.
 * @param {String} [option.dataSource] - Unique identifier of the dataProvider used to fill the table.
 * @param {Boolean} [option.autoSelect=true] - If true, the table will automatically load the data from the dataProvider. If false, it will wait for the select command.
 * @param {String}[option. targetPage] - Unique identifier of the page which will become active when a row is selected.
 * @param {String} [option.header=fixed] -  Defines the header location: `fixed` Attaches the header to the top of the page. `inline` Attaches the header to the top of the table location. `none` No header.
 * @param {Boolean} [option.treeData=false] - Indicates if the data should be treated as a tree structure. If the dataProvider is set as *treeData=true*, then the table inherits the value.
 * @param {String} [option.rootLabel] - The label used to display in the root row.
 * @param {Boolean} [option.noRoot=false] - Defines if the Root will be an editable row. The default is NO.
 * @param {Boolean} [option.multiRoot=false] - Defines if the tree will support multiple root branches. The default is NO, just one root.
 * @param {String} [option.iconOpen] - The icon showing an open branch if treeData is true. The default value is `fa-regular fa-folder-open fa-lg` from Fontawesome.
 * @param {String} [option.iconClose] - The icon showing a close branch if treeData is true. The default value is `fa-solid fa-folder-closed fa-lg` from Fontawesome.
 * @param {String} [option.iconEmpy] - The icon showing an end branch if treeData if true. Empty by default.
 * @param {Integer} [option.collapsable] - Indicates the tree can collapse.
 * @param {Integer} [option.collapsedLevel] - Indicates the number of open levels. Other levels will remain closed.
 * @param {Boolean} [option.selectable=true] - If true, the row will change color when selected.
 * @param {Boolean} [option.dpSearch=false] - If false, the search is done in the loaded data. If true, the search leads to a dataProvider select call. It can also receive the name of the DataProvider to be loaded.
 * @param {Boolean} [option.input=false] - If true, it will create input fields for the configured columns.
 * @param {String} [option.toggleList] - The list of comma-separated elements that will be toggled together with the component.
 *
 * @property {Object} $table - jQuery object referencing the table HTML tag container.
 * @property {Object} $tableSearchInput - jQuery object referencing the search text input element.
 * Get the parameters `index` and `item`.
 *
 */
var Table = function(id, options) {
	this.className = "table";

	var dataSource = ifUndefined(options["dataSource"], "");
	var autoSelect = ifUndefined(options["autoSelect"], true);
	var targetPage = ifUndefined(options["targetPage"], "");
	var header = ifUndefined(options["header"], "fixed");
	var treeData = ifUndefined(options["treeData"], undefined);
	var rootLabel = ifUndefined(options["rootLabel"], "");
	var noRoot = ifUndefined(options["noRoot"], false);
	var multiRoot = ifUndefined(options["multiRoot"], false);
	var deleteBranch = ifUndefined(options["deleteBranch"], false);
	var iconOpen = ifUndefined(options["iconOpen"], "fa-regular fa-folder-open fa-lg");
	var iconClose = ifUndefined(options["iconClose"], "fa-solid fa-folder-closed fa-lg");
	var iconEmpty = ifUndefined(options["iconEmpty"], "fa-regular fa-file fa-lg");
	var collapsable = ifUndefined(options["collapsable"], true);
	var collapsedLevel = ifUndefined(options["collapsedLevel"], 100);
	var selectable = ifUndefined(options["selectable"], true);
	var dpSearch = ifUndefined(options["dpSearch"], false);
	var parentList = ifUndefined(options["parentList"], "");
	var input = ifUndefined(options["input"], false);
	var toggleList = ifUndefined(options["toggleList"], "");

	var dpSearchTarget = undefined;
	if (typeof dpSearch !== "boolean") {
		/*
		 * If dpSearch is not boolean the text is set to "dpSearchTarge" and then dpSearch is set to "true".
		 * This is use generally when the application is use another DataProvider to do pagination.
		 * In this case the search should initiate with the dataProvider holding the pagination.
		 */
		dpSearchTarget = dpSearch;
		dpSearch = true;
	}

	this.$table;
	var $tableHead;
	var $tableData;
	var $emptyBox;
	var noBorder = false;
	var pageID;
	var modal = false;

	/**
	 * Returns the component's unique identifier.
	 * @returns {String}
	 */
	this.getID = function() {
		return id;
	}


	/*
	 * Store the recordSync contition.
	 * True : The record sync is executing.
	 * False : The record sync has not started.
	 */
	this.recordSyncLoading = false;

	var eventManager = new EventManager();
	/**
	 * Load events to respond to the tables's interactions. To set an event, use this code: ```Table.on(<eventName>, function(){<code>})```.
	 * @param {String} eventName - The event's name.
	 * @param {function} eventFunction - The function to be triggered.
	 */
	this.on = eventManager.on;

	/*
	 * Setting toggle manager
	 */
	var toggleManager = new ToggleManager(toggleList);

	// Defines the treeData based on the dataProvider isTreeData() method.
	if (dataSource != "") {
		dataSource = window[dataSource];
		if (treeData == undefined) treeData = dataSource.isTreeData();
	} else {
		if (treeData == undefined) treeData = false;
	}

	// Set the targetPage
	if (targetPage != "") {
		targetPage = window[targetPage];
	} else {
		targetPage = undefined;
	}

	this.$tableSearchInput = undefined;

	/* --------------------------------------------------------------------------------------- */

	/**
	 * Toggles the component between hidden and showing.  If the parameter is *true*, the component will be shown. If the *false*, the component will be hidden.
	 * @function
	 * @param {boolean} status - (Optional) True shows and false hides.
	 */
	this.toggle = function(status) {

		let toogleStatus = true;

		if (status == undefined) {
			toogleStatus = this.$table.is(':visible');
		} else {
			if (typeof status == "boolean") {
				toogleStatus = status;
			} else {
				toogleStatus = callFunction(status);
			}
		}

		/**
		 * This event is triggered when the table's visibility changes. Created with the ```Table.on("toggle", function(toogleStatus){})``` method. This event is triggered when the methods show, hide, and toggle are used. If the event function returns true or false, it will overwrite the toggle requested. Not returning a value preserves the original requested status.
		 * @event Table#Event:toggle
		 */
		let toggleEvent = eventManager.dispatch("toggle", toogleStatus);

		if (toggleEvent != undefined) toogleStatus = toggleEvent;

		this.$table.toggle(toogleStatus);

		if (isNotEmpty(toggleList)) toggleManager.toggle(this.$table.getCSSValue("display") != "none", this.$table);
	}

	/**
	 * Hides the table component.
	 * @function
	 */
	this.hide = function() {
		this.toggle(false)
	};

	/**
	 * Shows or unhides the table component.
	 * @function
	 */
	this.show = function() {
		this.toggle(true)
	};

	/**
	 * Get the text typed in the search text input.
	 * @returns {String}
	 */
	this.getSearchText = function() {
		if (this.$tableSearchInput == undefined) return "";
		if (this.$tableSearchInput.length == 0) return "";
		return this.$tableSearchInput.val().trim();
	}

	/**
	 * Sets the text of the search text input.
	 * @param {String} text - The new input text.
	 */
	this.setSearchText = function(text) {
		text = text.trim();
		this.$tableSearchInput.val(text);
		this.$tableSearchInput.trigger("keyup");
	}

	/**
	 * Clears the content of the search text input.
	 */
	this.clearSearchText = function() {
		this.$tableSearchInput.val("");
		this.$tableSearchInput.trigger("keyup");
	}

	/**
	 * Toggle the search input from visible to hidden. It requires the property `searchable="true"`.
	 * @param {Boolean} mode - The logic condition. True shows and false hides.
	 * @param {Boolean} reload - (Optional) If true, it clears filtering if the search input is hidden.
	 */
	this.toggleSearch = function(mode) {
		if (mode == undefined) {
			mode = this.$tableSearchInput.parent().is(':visible');
			mode = !mode;
		}
		this.$tableSearchInput.parent().toggle(mode);
		if (!mode) {
			this.setSearchText("");
		}
	}

	/**
	 * Returns the number of rows loaded in the table.
	 * @returns {Integer}
	 */
	this.length = function() {
		return $tableData.find("tr").length;
	}

	/**
	 * Returns the number of rows in the table.
	 * @returns {Integer}
	 */
	this.size = function() {
		return $tableData.find("tr").length;
	}

	/**
	 * Returns if the table is set to evaluate a tree data structure.
	 * @returns {Boolean}
	 */
	this.isTreeData = function() {
		return treeData;
	}

	/**
	 * Returns if the table should limit the root.
	 * @returns {Boolean}
	 */
	this.getNoRoot = function() {
		return noRoot;
	}

	/**
	 * Sets the root label if treeData is true;
	 */
	this.setRootLabel = function(newRootLabel) {
		rootLabel = newRootLabel;
		this.refreshRow(0);
	}

	/**
	 * Returns if the tree will allow a branch to be deleted. By default, only leaves are to be deleted. It is the developer's responsibility to program the deletion of children's branches or leaves.
	 * @returns {Boolean}
	 */
	this.getDeleteBranch = function() {
		return deleteBranch;
	}

	// --------- COLUMNS ---------

	/*
	 * Stores the columns objects
	 */
	var columns = new Array();

	if (treeData) {
		columns.push(new Column("", {
			title: "<i class='fa-solid fa-folder-tree'></i>",
			template: "<span class='{" + id + "_level_icon} silk-tree-icon' style='left:{" + id + "_level_width}px; color: {" + id + "_icon_color}' aria-hidden='true'></span>",
			width: "20px",
			align: "left",
			valign: "middle",
			wrap: true
		}
		));
	}

	/**
	 * Sets the tree icons programmatically. This overwrites the default icons.
	 * @param {String} open - The icon representing the open status.
	 * @param {String} close - The icon representing the close status.
	 * @param {String} empty - The icon representing a final branch.
	 */
	this.setTreeIcons = function(open, close, empty) {
		if (open != undefined) iconOpen = open;
		if (close != undefined) iconClose = close;
		if (empty != undefined) iconEmpty = empty;
	}

	/**
	 * Clean the columns array.
	 */
	this.cleanColumns = function() {
		columns = new Array();
	}

	/**
	 * Clean the headers from table.
	 */
	this.cleanHeaders = function() {
		$tableHead.html("");
	}

	/**
	 * Adds a column object to the columns array. This also adds the header.
	 *
	 * @param {Object} column - The column object
	 */
	this.addColumn = function(column) {
		if (column.getTableID() == "") column.setTableID(id);
		columns.push(column);
	}

	/**
	 * Removes a column object to the columns array. This also removes the header.
	 *
	 * @param {Object} column - The column object
	 */
	this.removeColumn = function(index) {
		columns.splice(index, 1);
	}

	/**
	 * Gets the columns array
	 * @returns {Array}
	 */
	this.getColumns = function() {
		return columns;
	}

	/**
	 * Sorts the data by the provided column
	 * @param {String} - Column to sort
	 */
	this.sort = function(column) {
		dataSource.sort(column);
	}

	/**
	 * Generates the table's columns using the loaded Column objects.
	 */
	this.buildHeaders = function() {

		if (header == "none") return;

		this.cleanHeaders();

		for (var x = 0; x < columns.length; x++) {

			if (!columns[x].getVisible()) continue;

			var title = columns[x].getTitle();

			if (columns[x].getSortColumn() != "" && !treeData) {

				let sortIcon = "";

				if (dataSource.getSortColumn() == columns[x].getSortColumn()) {
					if (dataSource.getSortDirection() == 1) {
						sortIcon = "<i class='fa-solid fa-caret-up' style='padding-left:4px' ></i>";
					} else {
						sortIcon = "<i class='fa-solid fa-caret-down'style='padding-left:4px' ></i> ";
					}
				}

				title = "<a href=\"javascript:" + id + ".sort('" + columns[x].getSortColumn() + "');\">" + title + "</a>" + sortIcon;
			}

			var thElement = document.createElement("th");
			thElement.setAttribute("id", columns[x].getID());
			thElement.setAttribute("style", "text-align:" + columns[x].getAlign() + ";");
			thElement.innerHTML = title;
			$tableHead.append($(thElement));

		}

	}

	// --------- COMPONENTS ---------

	/*
	 * Stores the components objects linked to this object
	 */
	var components = new Array();

	/**
	 * Adds a new component to the components array.
	 *
	 * @param {Object} component - The component object.
	 */
	this.addComponent = function(component) {
		components.push(component);
	}

	/**
	 * Gets the loaded component array.
	 * @returns {Array}
	 */
	this.getComponents = function() {
		return components;
	}

	/**
	 * Gets a reference to the dataSource.
	 * @returns {Object}
	 */
	this.getDataSource = function() {
		return dataSource;
	}

	// --------- LOAD PROCESS ---------

	/**
	 * The method retrieves data from the data provider and generates the table's rows. 
	 * @param {String} action - Indicating what action to load: insert, update, delete.
	 * @param {Integer} index - The position where the data will be loaded.
	 */
	this.load = function(action, index) {

		this.operationIndex = index;

		//console.log( "Table "+id+" action "+action );

		if (action == undefined) {
			this.action = "select";
		} else {
			this.action = action;
		}

		/**
		 * This event is triggered before the table content is loaded. Created with the ```Table.on("beforeLoad", function(){})``` method.
		 * @event Table#Event:beforeLoad
		 */
		eventManager.dispatch("beforeLoad", this.action, this.operationIndex);

		if (this.action == "select") {

			this.buildHeaders();

			/*
			 * Process SELECT action
			 */
			$tableData.html("");

			for (var x = 0; x < dataSource.size(); x++) {
				var item = dataSource.getItemAt(x);

				/**
				 * This event is triggered before a row item is added to the table content.  If the event function returns *false*, the item is ignored and not added. Created with the ```Table.on("filterLoad", function(index,item){})``` method.
				 * @event Table#Event:filterLoad
				 */
				if (!ifUndefined(eventManager.dispatch("filterLoad", x, item), true)) continue;

				if (treeData) {
					if (item._treeLevel > collapsedLevel) continue;

					if (item._childrenCount > 0 && item._treeLevel == collapsedLevel) {
						item[id + "_level_status"] = 0;
					} else if (item._childrenCount > 0 && item._treeLevel < collapsedLevel) {
						item[id + "_level_status"] = 1;
					} else {
						item[id + "_level_status"] = -1;
					}
				}

				//console.log( dataSource.selectObject.pkColumn );
				//console.log(item);

				var pkValue = item[dataSource.selectObject.pkColumn];
				var rowsHtml = generateRowHtml(pkValue, item, x);
				$tableData.append(rowsHtml);

			}

			/*
			 * If inputs are active the load stops after rendering table.
			 * Mask are applied to input fields.
			 */
			if (input) {
				this.$table.find(".form-control").each(function(x, el) {
					var $input = $(el);
					var mask = $input.attr("data-mask");
					if (isNotEmpty(mask)) $input.mask(mask);
				});
				return;
			}

			/**
			 * This event is triggered after the table content has been loaded and its content displayed. Created with the ```Table.on("afterLoad", function(){})``` method.
			 * @event Table#Event:afterLoad
			 */
			eventManager.dispatch("afterLoad", this.action, this.operationIndex);

			/*
			 * Verifies if table is showing records and triggers click on row if necessary when the rows are being created.
			 */
			if (this.length() > 0) {
				/*
				 * Process when no pages are being used
				 */
				if (pageID == undefined) {
					if (autoSelect && !input) {
						$tableData.find("tr:first-child td").last().trigger("click");
						if (dataSource.doRecordSync) {
							dataSource.execRecordSyncAfterLoadingSelect = true;

						}
					}
					/*
					 * Process when using a pages
					 */
				} else {
					if (autoSelect && !window[pageID].isAlone && !input) {
						$tableData.find("tr:first-child td").last().trigger("click");
						if (dataSource.doRecordSync) {
							this.recordSyncLoading = true;
							dataSource.execRecordSyncAfterLoadingSelect = true;
						}
					}
				}

			} else {
				/*
				 * It table is empty calls component's clean function
				 */
				for (x in components) {
					if (components[x]["clean"] != undefined) components[x].clean();
				}
				this.operationIndex = -1;
			}

			/*
			 * To hide or show the insert button based on parentList records.
			 */
			for (x in components) {
				if (components[x]["insertBt"] != undefined) {
					if (parentList != "") {
						if (window[parentList].length() == 0) {
							components[x]["insertBt"].hide();
						} else {
							components[x]["insertBt"].show();
						}
					}
				}
			}


		} else if (this.action == "insert") {
			/*
			 * Process INSERT action
			 */

			var item = dataSource.selectObject.data[this.operationIndex];
			var pkValue = item[this.getPkColumn()];
			var html = "";

			//a=;

			var insertTreeData = treeData;

			if (noRoot == true) {
				/*
				 * Creation of the ROOT row
				 */
				if (dataSource.size() == 1) {
					insertTreeData = false;
					item[dataSource.selectObject.levelControlColumn] = 0;
					item["_treeLevel"] = 0;
					item[id + "_level_status"] = 0;
					item["_childrenCount"] = 0
				} else {
					insertTreeData = true;
				}
			}

			if (insertTreeData) {

				item["_childrenCount"] = 0;
				item[id + "_level_status"] = -1;

				var totalRecords = $tableData.children().length;
				var $targetRow = $tableData.find("tr:eq(" + this.selectedIndex + ")");
				var recordIndex = dataSource.getIndex($targetRow.attr("data-pk"));
				var parentItem = dataSource.selectObject.data[recordIndex];
				var level = parentItem[dataSource.selectObject.levelControlColumn];

				/*
				 * Increment children count in parent item
				 */
				parentItem._childrenCount = parentItem._childrenCount + 1;

				/*
				 * If parent item does not have children
				 */
				var addChildren = parentItem[id + "_level_status"] == 0;
				if (parentItem[id + "_level_status"] != 1) {
					parentItem[id + "_level_status"] = 1;
					this.refreshRow(this.selectedIndex, recordIndex);
					$targetRow = $tableData.find("tr:eq(" + this.selectedIndex + ")");
				}
				/*
				 * If parent item has children and it is closed
				 */
				if (addChildren) {
					//console.log("Add childre 1*");
					var childrenElements = new Array();
					childrenElements = loadChildren(parentItem);
					for (var i = childrenElements.length - 1; i >= 0; i--) {
						$targetRow.after(childrenElements[i]);
					}
					this.selectedIndex++;
				} else {
					/*
					 * Searching for the last children to add new record
					 */
					for (x = this.selectedIndex + 1; x < totalRecords; x++) {
						$targetRow = $tableData.find("tr:eq(" + x + ")");
						recordIndex = dataSource.getIndex($targetRow.attr("data-pk"));
						this.selectedIndex = x;
						if (dataSource.selectObject.data[recordIndex][dataSource.selectObject.levelControlColumn] <= level) {
							this.selectedIndex--;
							break;
						}
					}

					/*
					 * If children was not loaded adds the record
					 *
					 */
					html = generateRowHtml(pkValue, item, this.selectedIndex);
					$tableData.find("tr:eq(" + this.selectedIndex + ")").after(html);
				}

			} else {
				this.selectedIndex = $tableData.children().length;
				html = generateRowHtml(pkValue, item, this.selectedIndex);
				$tableData.append(html);
			}

			this.selectItem(this.operationIndex);

		} else if (this.action == "update") {
			/*
			 * Process UPDATE action
			 */
			this.refreshRow(this.selectedIndex, this.operationIndex);
			this.selectItem(this.operationIndex);

		} else if (this.action == "delete") {

			/*
			 * Process DELETE action
			 */
			if (treeData) {
				var parentValue = dataSource.operationObject.data[0][dataSource.selectObject.parentTreeColumn];
				var parentRecord = dataSource.getIndex(dataSource.operationObject.data[0][dataSource.selectObject.parentTreeColumn]);
				var parentItem = dataSource.selectObject.data[parentRecord];
				var parentIndex = $tableData.find("tr[data-pk=\'" + parentValue + "\']").index();

				/*
				 * Removing children from the screen
				 */
				deleteChildren(this.selectedIndex + 1, this.selectedLevel);

				parentItem._childrenCount--;
				if (parentItem._childrenCount == 0) {
					parentItem[id + "_level_status"] = -1;
					this.refreshRow(parentIndex, parentRecord);
				}

			}
			var $toDelete = $selectedRow;
			this.selectUp();
			$toDelete.remove();

			if (window[pageID] != undefined) {
				window[pageID].show();
				window[pageID].mask(false);
			}

		}

		if (this.length() == 0 && !input) {
			/*
			 * It table is empty and not in input mode calls component's load function to reset form status and button
			 */
			for (x in components) {
				if (components[x]["setMode"] != undefined) components[x].setMode(false);
			}
		}


		/*
		 * Activates masks template in inputs
		 */
		if (input) $.applyDataMask(this.$table.find("." + id + "-input"));

		/*
		 * Sync header, and trigger a next sync in 200 ms.
		 */

		this.syncHeader();
		setTimeout($.proxy(function() {
			this.syncHeader();
		}, this), 400);


		this.action = "select";

		$emptyBox.toggle(this.length() == 0);

		/*
		 * Process if search text is being use with dpLoad="false" and is not input true
		 */
		if (!dpSearch && !input) {
			if (this.getSearchText() != "") {
				setTimeout($.proxy(function() { this.filterData(); }, this), 100);
			}
		}

	} // end this.load


	this.errorHandle = function() {

		/**
		 * Event triggered after an error. Created with the ```Table.on("error", function(){})``` method.
		 * @event Table#Event:error
		 */
		eventManager.dispatch("error");
		this.action = "select";

	}

	/**
	 * Switch the column's input status, or set the input to the provided status. If *true* is provided, it activates the inputs. If *false* is provided, it deactivates the inputs. This only works in columns set as input holders.
	 * @param inputStatus The input status.
	 */
	this.setInputs = function(inputStatus) {
		if (inputStatus == undefined) {
			input = !input;
		} else {
			input = inputStatus;
		}

		this.$tableSearchInput.prop("disabled", input)

		this.load();
	};


	/**
	 * Returns an array containing an array of input objects. If a function is provided, this will be executed for each row. The function will receive an object containing the inputs as a parameter.
	 * @param {Function) inputProcessor - An optional function, will be called for each input processed.
	 * @returns Array
	 */
	this.getInputs = function(inputProcessor) {
		var inputArray = new Array;
		this.$table.find("tbody tr").each(function(x, trElement) {
			var $row = $(trElement);
			var rowIndex = $row.attr("data-index");
			var rowObject = new Object();
			var inputCount = 0;
			$row.find("input,textarea,div").each(function(y, inputElement) {
				var $inputElement = $(inputElement);
				if ($inputElement.hasClass(id + "-input")) {
					inputCount++;
					var dataColumn = $inputElement.attr("data-column");

					var inputObject = new Object();
					var inputType = $inputElement.attr("data-type");
					inputObject["index"] = rowIndex;

					var oldValue = $inputElement.attr("data-value");

					var value = "";
					if (inputType == "html") {
						value = $inputElement.html();
					} else {
						value = $inputElement.val();
					}

					var item = JSON.parse($inputElement.attr("data-json"));

					if (inputType == "integer" || inputType == "number" || inputType == "decimal" || inputType.indexOf("decimal(") > -1) {
						oldValue = getNumber(oldValue, 20);
						value = getNumber(value, 20);
					}

					var action = "none";
					if (isNotEmpty(value) && isEmpty(oldValue)) {
						action = "insert";
					}

					if (isEmpty(value) && isNotEmpty(oldValue)) {
						action = "delete";
					}

					if (isNotEmpty(value) && isNotEmpty(oldValue) && value != oldValue) {
						action = "update";
					}

					inputObject["type"] = inputType;
					inputObject["oldValue"] = oldValue;
					inputObject["value"] = value;
					inputObject["action"] = action;
					inputObject["hasChanged"] = value != oldValue;
					inputObject["item"] = item;

					rowObject[dataColumn] = inputObject;
				}
			});

			if (inputCount > 0) {
				if (inputProcessor != undefined) {
					inputProcessor(rowObject)
				}
				inputArray.push(rowObject);
			}
		});

		return inputArray;
	};


	/*
	 * Generates HTML data for table row
	 *
	 * @param index The dataSource index used to mark the row.
	 * @param item The row object.
	 */
	var generateRowHtml = function(pkValue, item, index) {

		var trElement = document.createElement("tr");
		trElement.setAttribute("data-pk", pkValue);
		trElement.setAttribute("data-index", index);

		var index = dataSource.getIndex(pkValue);
		for (y in columns) {

			if (!columns[y].getVisible(item)) continue;

			var style = "";

			if (columns[y].getAlign() != "") {
				style += "text-align:" + columns[y].getAlign() + "; ";
			}

			if (columns[y].getValign() != "") {
				style += "vertical-align:" + columns[y].getValign() + "; ";
			}

			if (noBorder) {
				style += "border:none;";
			}


			if (treeData) {
				var treeWidth = (item._treeLevel) * 15;
				if (isNaN(treeWidth)) treeWidth = 0;
				if (y == 0) item[id + "_level_width"] = treeWidth;
				if (y == 1) style += "padding-left: " + treeWidth + "px;";

				if (item._childrenCount == undefined) {
					item["_childrenCount"] == 0
					item[id + "_level_status"] = -1;
				}

				if (item._childrenCount == 0) {
					if (item._iconEmpty == undefined) {
						item[id + "_level_icon"] = iconEmpty;
					} else {
						item[id + "_level_icon"] = item._iconEmpty;
					}
					if (item._iconEmptyColor != undefined) {
						item[id + "_icon_color"] = item._iconEmptyColor;
					}
				} else {
					if (item[id + "_level_status"] == 0) {
						if (item._iconClose == undefined) {
							item[id + "_level_icon"] = iconClose;
						} else {
							item[id + "_level_icon"] = item._iconClose;
						}
						if (item._iconCloseColor != undefined) {
							item[id + "_icon_color"] = item._iconCloseColor;
						}
					} else {
						if (item._iconOpen == undefined) {
							item[id + "_level_icon"] = iconOpen;
						} else {
							item[id + "_level_icon"] = item._iconOpen;
						}
						if (item._iconOpenColor != undefined) {
							item[id + "_icon_color"] = item._iconopenColor;
						}
					}
				}

			}

			var data = "";
			if (input && columns[y].hasInput) {

				/*
				 * Process to generate INPUT
				 */
				var returnedType = "";
				var returnedMask = "";
				var drawInput = true;

				/*
				 * Checks if the column's visibleColum property has been set.
				 */
				if (columns[y].getVisibleColumn() != "") {
					drawInput = getNumber(item[columns[y].getVisibleColumn()]) == 1;
				}

				/**
				 * This event is triggered before each input is generated. If the event function returns *true*, the input will be created. If it returns *false*, it will not render an input.
				 * If the event returns a text value, the input will be generated, and the provided text is used to define the input's type. The text can contain an added mask separated by a pipe symbol.
				 * If the event returns undefined, the input is also generated.
				 * Created with the ```Table.on("renderInput", function(value,pdIndex,dpItem){})``` method.
				 * @event Table#Event:renderInput
				 */
				var dispatchResult = eventManager.dispatch("renderInput", columns[y].getValueColumn(), getNumber(index), item);

				/*
				 * If the event return a non-bolean uses the type return and set it as visitible.
				 */
				if (dispatchResult != undefined) {
					drawInput = dispatchResult;
				}

				/*
				 * If the event returns a non-boolean
				 */
				if (!(typeof drawInput == "boolean")) {
					drawInput = "" + drawInput;
					if (drawInput.indexOf("|") > -1) {
						returnedType = drawInput.split("|")[0];
						returnedMask = drawInput.split("|")[1];
					} else {
						returnedType = drawInput;
					}
					drawInput = "true";
				}

				/*
				 * Will generate the Input if drawInput is true.
				 */
				if (drawInput) {

					/*
					* Sets input label if provided
					*/
					if (columns[y].getLabelColumn() != "") {
						style += "padding:4px;";
						data += item[columns[y].getLabelColumn()] + "<br/>";
					} else {
						style += "padding:2px 4px 2px 4px;";
					}

					// --- Defines type --- //

					/*
					 * The list of allow input types
					 */
					var typeList = "text,textarea,html,number,integer,decimal(1),decimal(2),decimal(3),decimal(4),decimal(5),decimal(6)";

					/*
					 * Initializes type with the defined column's type.
					 */
					var type = columns[y].getInputType();

					/*
					   * If the type is not part of the typeList it is treated like an item's property.
					 */
					if (typeList.indexOf(type.toLowerCase()) == -1) {
						if (item[type] != undefined) {
							type = item[type];
						}
					}

					/*
					 * If the "event:input" returned a type it is set
					 */
					if (returnedType !== "") type = returnedType;

					/*
					 * If the type is not part of the typeList it defaults to "text".
					 */
					if (typeList.indexOf(type.toLowerCase()) == -1) {
						type = "text";
					}

					// --- Defines mask --- //

					/*
					 * Initializes mask with the defined column's mask.
					 */
					var mask = columns[y].getInputMask();

					/*
					   * The mask is check against the item's property.
					 */
					if (mask != "") {
						if (item[mask] != undefined) {
							mask = item[mask];
						}
					}

					/*
					 * If the "event:renderInput" returned a mask it is set
					 */
					if (returnedMask !== "") mask = returnedMask;

					/**
					 * This event is triggered while the input is being generated. If the event's function returns an object, it will be saved as a JSON String in the input's property 'data-json' for use in post operations. Created with the ```Table.on("dataInput", function(dpIndex,pdItem,inputType){})``` method.
					 * @event Table#Event:dataInput
					 */
					data += columns[y].getInput(index, item, type, mask, eventManager.dispatch("dataInput", index, item, type));

				} else {
					/*
					 * If the event:input return false a empty space is returned.
					 */
					data = "&nbsp;";
				}
			} else {
				/*
				 * Check for distinct
				 */
				var renderData = false;
				if (columns[y].getDistinct() == "") {
					renderData = true;
				} else {
					if (index == 0) {
						renderData = true;
					} else if (getObjectType(columns[y].getDistinct()) == 'boolean') {
						renderData = true;
					} else {
						var value1 = "";
						var value2 = "";

						var distinctColumns = columns[y].getDistinct().split(",");
						for (l in distinctColumns) {
							var distinctColumn = distinctColumns[l].trim();
							value1 += item[distinctColumn];
							value2 += dataSource.getItemAt(index - 1)[distinctColumn];
						}

						if (value1 != value2) renderData = true;
					}
				}

				/*
				 * Gets the regular Column data if renderData is true
				 */
				if (renderData) data = columns[y].getData(index, item);
			}

			if (treeData && index == 0 && !noRoot) {
				if (y == 1) {
					if (rootLabel != "") data = rootLabel;
				}
				if (y > 1) data = "&nbsp;";
			}

			var tdElement = document.createElement("td");
			tdElement.setAttribute("style", style);
			if (columns[y].getDraggable() || columns[y].getOrdering()) tdElement.setAttribute("draggable", "true");
			if (columns[y].getCssClass() != "") tdElement.setAttribute("class", columns[y].getCssClass());
			if (columns[y].getWrap() === false) tdElement.setAttribute("nowrap", "nowrap");
			if (columns[y].getWrap() === "full") tdElement.setAttribute("fullwrap", "fullwrap");

			tdElement.innerHTML = data;

			trElement.append(tdElement);

		}

		return trElement;
	}

	/**
	 * Reload the data for the selected row by default, or the indicated row.
	 * @param {Integer} trIndex - The row index within the table row.
	 * @param {Integer} dpIndex - The row index in the dataProvider.
	 */
	this.refreshRow = function(trIndex, dpIndex) {
		if (trIndex == undefined) trIndex = this.selectedIndex;
		if (dpIndex == undefined) dpIndex = this.operationIndex;
		var item = dataSource.selectObject.data[dpIndex];
		var $tr = $tableData.find("tr:eq(" + trIndex + ")");
		var $newTr = $(generateRowHtml(item[this.getPkColumn()], item, trIndex));
		$tr.replaceWith($newTr);
		this.syncHeader();

	}

	/**
	 * Returns an array containing the generational children of a record.
	 * @param {pkValue} - The primary key value to evaluate.
	 * @return {Array}
	 */
	this.getChildren = function(pkValue) {
		if (pkValue == undefined) pkValue = this.getSelectedItem(dataSource.getPkColumn());
		return dataSource.getChildren(pkValue);
	}


	// --------- SELECTED INDEX ---------

	/**
	 * Returns the selected item object, or the column's value if a columnName is provided.
	 * @param {String} columnName=undefined - The column's value to return. Optional.
	 * @returns {Object|String}
	 */
	this.getSelectedItem = function(columnName) {
		if (this.operationIndex == -1) return new Object();
		if (columnName == undefined) return dataSource.getItemAt(this.operationIndex);
		return dataSource.getItemAt(this.operationIndex, columnName);
	}

	/**
	 * Sets the value of the provided column in the selected row.
	 * @param {String} columnName - The column to be updated
	 * @param {String} value - The new value
	 */
	this.setSelectedItem = function(columnName, value) {
		if (columnName == undefined) return;
		return dataSource.setItemAt(this.operationIndex, columnName, value);
	}

	/**
	 * Gets the data primary key.
	 * @returns {String}
	 */
	this.getPkColumn = function() {
		var pk = dataSource.selectObject.pkColumn;
		if (pk == undefined) pk = "nopk"
		return pk;
	}

	/**
	 * Gets the primary key's value of the selected row.
	 * @returns {String}
	 */
	this.getPkValue = function() {
		return this.getSelectedItem(this.getPkColumn());
	}

	// --------- CLICK EVENT ---------

	this.selectedIndex = -1;
	this.operationIndex = -1;
	this.selectedLevel = 0;
	this.selectedChildrenCount = 0;

	var $selectedCell = null;
	var $selectedRow = null;
	var $silkContent = null;
	var rowIndex = -1;

	/*
	 * To use when ordering = true;
	 */
	var dragSourceIndex = -1;
	var dragTargetIndex = -1;
	var dragPkValue = "";

	/*
	 * Callback function connected to the JQuery mouse events.
	 */
	this.mouseCallback = function(mouseAction, event) {

		/*
		 * If inputs are active disables mouse actions.
		 */
		if (input) {
			event.stopPropagation();
			return;
		}

		/*
		 * if mouse action is click, the row is unmarked
		 */
		if (mouseAction == 'click') if ($selectedRow != null) $selectedRow.removeClass("table-active");

		/*
		 * load temporal selected cell and row
		 */
		var $tmpSelectedCell = $(event.currentTarget);
		var $tmpSelectedRow = $tmpSelectedCell.parent();

		/*
		 * Adding the DP row affected
		 */
		var rowItem = {};
		var rowPK = "";
		if (dataSource != "") {
			rowPK = $tmpSelectedRow.attr("data-pk");
			rowItem = dataSource.getIndexItem(rowPK);
		}

		/*
		 * Detects if real click and assigns column clicked
		 */
		var colIndex = -1;
		var mouseEvent = false
		if (event.originalEvent != undefined) {
			mouseEvent = true;
			colIndex = $tmpSelectedCell.index();
		}

		/*
		 * Process the mouse drag events
		 */
		if (mouseAction == 'dragstart') {

			/*
			 * Copies rowPK to select row after dropping.
			 */
			dragPkValue = rowPK;

			/**
		* This event is triggered when a row begins to be dragged. The event function provides the column index, row index, data provider item, and the mouse event. Created with the ```Table.on("dragStart", function(columnIndex, rowIndex, dpItem, event ){})``` method.
		* @event Table#Event:dragStart
		*/

			/*
			 * Ordering
			 */
			if (columns[colIndex].getOrdering()) {
				dragSourceIndex = $tmpSelectedRow.index();
				dragTargetIndex = -1;
			}
			/* End Ordering */

			eventManager.dispatch("dragStart", colIndex, $tmpSelectedRow.index(), rowItem, event);
			return;

		} else if (mouseAction == 'dragenter') {
			/**
			 * This event is triggered when a dragged row enters another row area. The event function provides the column index, row index, data provider item, and the mouse event. Created with the ```Table.on("dragStart", function(columnIndex, rowIndex, dpItem, event ){})``` method.
			 * @event Table#Event:dragEnter
			 */
			eventManager.dispatch("dragEnter", colIndex, $tmpSelectedRow.index(), rowItem, event);
			return;

		} else if (mouseAction == 'dragover') {
			/**
			 * This event is triggered when a dragged row is over another row area.  The event function provides the column index, row index, data provider item, and the mouse event. Created with the ```Table.on("dragStart", function(columnIndex, rowIndex, dpItem, event ){})``` method.
			 * @event Table#Event:dragOver
			 */
			eventManager.dispatch("dragOver", colIndex, $tmpSelectedRow.index(), rowItem, event);
			return;

		} else if (mouseAction == 'dragleave') {
			/**
			 * This event is triggered when a dragged row leaves a row area. The event function provides the column index, row index, data provider item, and the mouse event. Created with the ```Table.on("dragStart", function(columnIndex, rowIndex, dpItem, event ){})``` method.
			 * @event Table#Event:dragLeave
			 */
			eventManager.dispatch("dragLeave", colIndex, $tmpSelectedRow.index(), rowItem, event);
			return;

		} else if (mouseAction == 'dragdrop') {

			/*
			 * Ordering
			 */
			if (columns[colIndex].getOrdering()) {


				dragTargetIndex = $tmpSelectedRow.index();

				var updateArray = new Array();
				for (var x = 0; x < dataSource.size(); x++) {

					if (dragSourceIndex < dragTargetIndex) {
						if (x != dragSourceIndex) {
							updateArray.push(dataSource.getItemAt(x, dataSource.getPkColumn()));
						}
						if (x == dragTargetIndex) {
							updateArray.push(dataSource.getItemAt(dragSourceIndex, dataSource.getPkColumn()));
						}
					}
					else {
						if (x == dragTargetIndex) {
							updateArray.push(dataSource.getItemAt(dragSourceIndex, dataSource.getPkColumn()));
						}
						if (x != dragSourceIndex) {
							updateArray.push(dataSource.getItemAt(x, dataSource.getPkColumn()));
						}
					}
				}

				if (dataSource.sourceType == "SQL") {
					dataSource.cleanOperations();
				}

				for (var x in updateArray) {
					if (dataSource.sourceType == "SQL") {
						dataSource.setOperationAction("update");
						dataSource.setOperationItem(dataSource.getPkColumn(), updateArray[x]);
						dataSource.setOperationItem(dataSource.selectObject.orderColumn, x);
					}
					dataSource.setItemAt(dataSource.getIndex(updateArray[x]), dataSource.selectObject.orderColumn, x);
				}

				if (dataSource.sourceType == "SQL") {
					dataSource.batch();
				}

				dataSource.sort(dataSource.selectObject.orderColumn, false);

			}
			/* End Ordering */

			/*
			 * Select the moved row.
			 */
			this.selectRow(dataSource.getIndex(dragPkValue));

			/**
			 * This event is triggered when a dragged row is dropped over a row area. The event function provides the column index, row index, data provider item, and the mouse event. Created with the ```Table.on("dragStart", function(columnIndex, rowIndex, dpItem, event ){})``` method.
			 * Created with the ```Table.on("dragStart", function(columnIndex, rowIndex, dpItem, event ){})``` method.
			 * @event Table#Event:dragDrop
			 */
			eventManager.dispatch("dragDrop", colIndex, $tmpSelectedRow.index(), rowItem, event);

			/*
			 * Exist after a drag and drop.
			 */
			return;
		}

		/*
		 * Set the selected row
		 */
		$selectedCell = $tmpSelectedCell;
		$selectedRow = $tmpSelectedRow;

		/*
		 * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
		 * The next process are related to click event.
		 * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
		 */

		/*
		 * Marks the selected index property based on the selectedRow index value.
		 */
		this.selectedIndex = $selectedRow.index();

		/*
		 * If dataProvider has only one records operationIndex is set to 0.
		 */

		if (dataSource.length() == 1) {
			this.operationIndex = 0;
		} else {
			this.operationIndex = dataSource.getIndex($selectedRow.attr("data-pk"));
		}

		if (this.length() == 1 && this.action == "delete") {
			// Calls components to clean values after click
			for (x in components) {
				if (components[x]["clean"] != undefined) {
					components[x].clean();
				}
			}
		} else {

			/*
			 * If doRecordSync is true, the record sync loading status is false, and it is a real mouse click.
			 * it change the record sync laoding status to true and
			 * will execute the recordSync method in the DataProvider
			 */
			if (dataSource.doRecordSync && !this.recordSyncLoading && mouseEvent) {
				this.recordSyncLoading = true;
				dataSource.recordSync();
			} else {
				// Calls components to load data after click
				for (x in components) {
					if (components[x]["load"] != undefined) {
						components[x].load();
					}
				}
			}

			if (dataSource.detailDP != null) {
				// If set it will call the detailDP and wait to fill no existing attributes
				dataSource.select(dataSource.detailDP);
			}
		}

		/*
		 * Collects the tree level
		 */
		if (treeData) {
			var item = dataSource.selectObject.data[this.operationIndex];
			var status = item[id + "_level_status"];
			this.selectedLevel = item[dataSource.selectObject.levelControlColumn];

			/*
			 * Process child records in tree data if first TD is clicked.
			 */
			if (collapsable) {
				if ($selectedCell.is(':first-child')) {

					if (status != -1) {

						if (status == 0) {
							/*
							 * Insert children records
							 */
							item[id + "_level_status"] = 1;

							var childrenElements = new Array();
							childrenElements = loadChildren(item);
							for (var i = childrenElements.length - 1; i >= 0; i--) {
								$selectedRow.after(childrenElements[i]);
							}
						}

						if (status == 1) {
							/*
							 * Delete children records
							 */
							item[id + "_level_status"] = 0;
							deleteChildren(this.selectedIndex + 1, this.selectedLevel);
						}

						this.refreshRow(this.selectedIndex, this.operationIndex);
						this.syncHeader();
						$selectedRow = $tableData.find("tr:eq(" + this.selectedIndex + ")");

					}
				}
			}
		}

		/*
		 * If the host page is single the row will not be selected
		 */

		if (eventManager.eventExists("visualSelection")) {

			/**
			 * This event is triggered when a row is clicked and will be marked selected. Created with the ```Table.on("visualSelection", function(colIndex, dpIndex, mouseEvent){})``` method.
			 * @param {Integer} coldIndex  - The column clicked. The first one is 0.
			 * @param {Integer} dbIndex - The dataProvider index of the selected row.
			 * @param {Boolean} realClick - Returns true if the "click" has been triggered by a physical click.
			 * @param {Object} mouseEvent - The mouse click even object.
			 * @event Table#Event:visualSelection
			 */
			if (ifUndefined(eventManager.dispatch("visualSelection", colIndex, this.selectedIndex, mouseEvent, event), false)) {
				$selectedRow.addClass("table-active");
			}

		} else {
			if (selectable === "always") {
				$selectedRow.addClass("table-active");
			} else {
				if (window[pageID] != undefined) {
					if (window[pageID].isSingle != undefined) {
						if (selectable && !window[pageID].isSingle) $selectedRow.addClass("table-active");
					}
				} else {
					if (selectable) $selectedRow.addClass("table-active");
				}
			}
		}

		/**
		 * This event is triggered when a row is clicked. Created with the ```Table.on("click", function(colIndex, dpIndex, mouseEvent){})``` method.
		 * @param {Integer} coldIndex  - The column clicked. The first one is 0.
		 * @param {Integer} dbIndex - The dataProvider index of the selected row.
		 * @param {Boolean} realClick - Returns true if the "click" has been triggered by a physical click.
		 * @param {Object} mouseEvent - The mouse click even object.
		 * @event Table#Event:click
		 */
		eventManager.dispatch("click", colIndex, this.selectedIndex, mouseEvent, event);

		// Show page if it is real click.
		if (mouseEvent) {
			if (columns[colIndex].getTargetPage() != "") {
				if (treeData && !noRoot) {
					if (this.selectedIndex > 0) columns[colIndex].showPage();
				} else {
					columns[colIndex].showPage();
				}
			} else {
				if (targetPage != undefined) {
					targetPage.show();
				}
			}
		}
	}

	/*
	 * Function to load children rows to populate tree.
	 */
	var loadChildren = function(item) {
		var rowArray = [];
		var parentID = item[dataSource.selectObject.rootTreeColumn];
		var parentLevel = item[dataSource.selectObject.levelControlColumn];
		for (var y in dataSource.selectObject.data) {
			var rowItem = dataSource.selectObject.data[y];
			var rowItemParentID = rowItem[dataSource.selectObject.parentTreeColumn];
			var rowItemLevel = rowItem[dataSource.selectObject.levelControlColumn];
			if (rowItemParentID === parentID && rowItemLevel == parentLevel + 1) {
				var childrenArray = [];
				if (rowItem._childrenCount > 0) {
					if (rowItem[id + "_level_status"] == undefined) rowItem[id + "_level_status"] = 0;
					if (rowItem[id + "_level_status"] == 1) childrenArray = loadChildren(rowItem);
				} else {
					rowItem[id + "_level_status"] = -1;
				}
				//$target.after( generateRowHtml(rowItem[dataSource.selectObject.pkColumn], rowItem, y) );
				rowArray.push(generateRowHtml(rowItem[dataSource.selectObject.pkColumn], rowItem, y));
				rowArray = rowArray.concat(childrenArray);
				dataSource.selectObject.data[y][id + "_level_status"] = rowItem[id + "_level_status"];
			}
		}

		return rowArray;
	}

	/*
	 * Function to delete children rows to collapse tree.
	 */
	var deleteChildren = function(targetIndex, level) {
		var $targetRow = $tableData.find("tr:eq(" + targetIndex + ")");
		var recordIndex = dataSource.getIndex($targetRow.attr("data-pk"));

		if (recordIndex == -1) return;

		while (dataSource.selectObject.data[recordIndex][dataSource.selectObject.levelControlColumn] > level) {
			$targetRow.remove();
			$targetRow = $tableData.find("tr:eq(" + targetIndex + ")");
			if ($targetRow.length == 0) break;
			recordIndex = dataSource.getIndex($targetRow.attr("data-pk"));
		}

	}


	/*
	 * Select table row bases on the dataSource index
	 *
	 * @param index The dataSource index
	 */
	this.selectItem = function(dpIndex) {

		if (dataSource.length() == 0) return;
		if (dpIndex == undefined) return;
		var pkValue = dataSource.selectObject.data[dpIndex][this.getPkColumn()];
		$tableData.find("tr[data-pk=\'" + pkValue + "\']").find("td:last-child").trigger("click");

		/*
		 * Puts row in screen if needed
		 */
		$tableData.find("tr[data-pk=\'" + pkValue + "\']")[0].scrollIntoViewIfNeeded();

	}

	/**
	 * Selects the row in the table using the provided index. If the property *selectedIndex* is manually changed, this method can be called without the parameter for visual synchronization. 
	 *
	 * @param index The table row index
	 */
	this.selectRow = function(index) {

		if (index == undefined) index = this.selectedIndex;
		$tableData.find("tr:eq(" + index + ")").find("td:last-child").trigger("click");

		/*
		 * Puts row in screen if needed
		 */
		$tableData.find("tr:eq(" + index + ")")[0].scrollIntoViewIfNeeded();

	}

	this.unselectRow = function() {
		if ($selectedRow != null) $selectedRow.removeClass("table-active");
	}


	/**
	 * Selects the row above the currently selected row.
	 */
	this.selectUp = function() {
		if (this.selectedIndex > -1) this.selectRow(this.selectedIndex - 1);
	}

	/**
	 * Selects the row below the currently selected row.
	 */
	this.selectDown = function() {
		if (this.selectedIndex < $tableData.children().length - 1) this.selectRow(this.selectedIndex + 1);
	}

	/**
	 * Syncronizes the tables header with the columns width.
	 */
	this.syncHeader = function() {

		//$tableData.parent().find("thead").show();
		var sourceList = $tableData.find("tr:visible:first td");
		var targetList = $tableHead.find("th");

		for (x = 0; x < sourceList.length; x++) {
			if (columns[x].getWidth() == "0") {
				$(sourceList[x]).css("width", "");
			} else {
				$(sourceList[x]).css("width", columns[x].getWidth());
			}
			$(targetList[x]).css("width", "");
		}

		if (header == "none") {
			return;
		}

		/*
		 * Fixes table header to top.
		 */
		if (header == "fixed" || header == "top-fixed") {
			if ($("#personListTopHeader").length > 0) {
				this.$table.find(".silk-table-header").css("top", $("#" + id + "TopHeader").height());
			} else {
				this.$table.find(".silk-table-header").css("top", 0);
			}
		}

	}


	// --------- CALL ACTIONS ---------

	/*
	 * Function used by other elements to request actions to the dataSource.
	 *
	 * @param operationList The operationList
	 */
	this.callAction = function(operationList) {
		dataSource.callAction(operationList, this.operationIndex);
	}

	/*
	 * Manges the timer when fillwing the search input.
	 */
	this.searchTimer;

	/**
	 * Filters the table's rows based on the provided text. In the case of `dpSearch="true"`, a select method will be called, and the dataProvider should receive the search text in a parameter. The search input functionality activated by `searchable="true"` uses this method.
	 * @param {String} searchText - The text used to filter the table rows
	 */
	this.filterData = function(searchText) {
		var text = searchText;
		if (searchText == undefined) text = this.getSearchText();

		/**
		 * This event is triggered when the search input text changes.  It is used to evaluate the text entered in the search input. If the event function returns a value, it will be used to replace the original search value. Created with the ```Table.on("searchText", function(){})``` method.
		 * @param {String} text - The entered text.
		 * @event Table#Event:searchText
		 */
		if (eventManager.eventExists("searchText")) text = eventManager.dispatch("searchText", text);

		if (dpSearch) {
			//if( text.length < 3 ){
			//	$tableData.empty();
			//}
			if (dpSearchTarget) {
				window[dpSearchTarget].select();
			} else {
				dataSource.select();
			}
		} else {
			if (text == '') {
				$tableData.find('tr').show();
			} else {
				text = text.toLowerCase();
				$tableData.find('tr').each(function(index, element) {
					toggleTR($(element), text);
				});
			}
		}
		this.syncHeader();
	}

	var toggleTR = function($element, text) {
		var elementText = $element.text().toLowerCase();
		var arrayText = text.split(' ');
		var countSearch = 0;
		var countFound = 0;

		for (var x = 0; x < arrayText.length; x++) {
			if (arrayText[x] != '') {
				countSearch++;
				if (elementText.indexOf(arrayText[x]) != -1) {
					countFound++;
				}
			}
		};

		$element.toggle(countSearch == countFound);
	}

	// --------- Initialize Table  ---------

	this.initTable = function() {

		this.$table = $("#" + id);

		$tableHead = this.$table.find(".silk-table-header");
		$tableData = this.$table.find(".silk-table-data tbody");
		$emptyBox = $("#" + id + "Empty");

		pageID = this.$table.closest(".silk-page").attr("id");
		$silkContent = this.$table.closest(".silk-content");
		noBorder = this.$table.find("table").hasClass("no-border");

		this.$tableSearchInput = $("#" + id + "_search_input");

		modal = this.$table.parent().hasClass("modal-body");
		if (modal) {
			this.$table.parent().removeClass("modal-margin");
			this.$table.parent().addClass("modal-no-margin");
			this.$table.find("table").css("margin", "0px")
		}

		if ($silkContent.length == 0) {
			$silkContent = $("body");
		}

		if (pageID != undefined) {

			/*
			 * Clear top content padding if first on table
			 */
			if (header == "fixed" || header == "none" || header == "top-fixed") {
				if ($("#" + id + "TopHeader").length == 0) {
					if ($silkContent.children().first().hasClass("silk-table") || $silkContent.children().first().hasClass("silk-help")) {
						/*
						 * Removes content top border
						 */
						$silkContent.addClass("silk-table-first-on-page");

						/*
						 * Removes line of TH to look better
						 */
						$tableHead.addClass("silk-table-first-on-page-header");
					}
				}
			}

		}

		/*
		 * Add click listener to TD elements.
		 */
		$tableData.on("click", "td", $.proxy(function(event) {

			/*
			 * If table is in input entry mode the click event is disable.
			 */
			if (input) return;

			/*
			 * Prevents triggering a click event after a text selection action.
			 */
			if (window.getSelection().toString() != "") {
				event.preventDefault();

				/**
				 * Triggered when a text has been selected in a table row. Created with the ```Table.on("textSelection", function(text){})``` method.
				 * @param {String} text - The selected text.
				 * @event Table#Event:textSelection
				 */
				eventManager.dispatch("textSelection", window.getSelection().toString());

				return;
			}

			/*
			 * Calls the mouse callback function
			 */
			this.mouseCallback('click', event);

		}, this))

		/*
		 * Activates mouse drag events call backs.
		 */
		$tableData.on("dragstart", "td", $.proxy(function(event) {
			this.mouseCallback('dragstart', event);

			if (columns[event.currentTarget.cellIndex].getOrdering()) {
				var img = document.createElement("img");
				img.src = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAIKADAAQAAAABAAAAIAAAAACshmLzAAACEUlEQVRYCe1XTUsCURSdZ4O4UdciLYKwFkKRVJvEEjeFtlCLfkX0E/oJ0a8IUxcVtQlTDMSCMHBRErUQmbW6kZBec4w3TDajXsFp48D47jv345y5zkMvS6VSM3Ozs1ucsSXOuVOy4GKMtRnnzx/1+h17LJUiX5K0MQ5vLp9fRF54c/NlnHybJN3LeHKJc3J+u922FwqFbSSuBgLvTqfzk1oE3LZx255Kp8OdTseFGzaVHPHgVrtAv6rVqqdWq62JTNjAxJ6ykgWoqtnF1VVMJWE6oh4Gnw4bySQLyGaz681m88/TAoNvJFZdEElAo9FwPVUqW7r8XyZ8iPkFDtmQBJxnMjvdbtduVhM+xJj5jXBWLpWOjRxWYaQOTEKULIoWi8X521wuhnMtsEmsDoejFQmHL4PB4Bvqax2wghyEeEBwwcalCfjZWv+pCUBb0J5JSxBfgeCZnoLpKdBeQvFSWL1qAqanwOrWCz7tFAhg0HpyenqgKMrCoBiPx/N6dHh4NihG79PeAT1oZu8lEteyLJv++4UPMWb5RjhJgNfrba0sL98ZFQIGH2LM/EY4SQAKxOPxstvtVvqLAYOvHx+2JwtQxyq+G41eqoX100wPg28YYb+fLAAF/H6/4vP5HkQx2MDEnrLaMChSEkTsfjKZw08rbtgCp6zgljGlqn0jD6eYBUOh0A0Ix5kLkQdu9t/j+Tcv4O5d+y8EhwAAAABJRU5ErkJggg==";
				event.originalEvent.dataTransfer.setDragImage(img, 15, 15);
			}

		}, this))

		$tableData.on("dragenter", "td", $.proxy(function(event) {
			event.preventDefault();
			event.stopPropagation();
			this.mouseCallback('dragenter', event);
		}, this))

		$tableData.on("dragover", "td", $.proxy(function(event) {
			event.preventDefault();
			event.stopPropagation();
			this.mouseCallback('dragover', event);
		}, this))

		$tableData.on("dragleave", "td", $.proxy(function(event) {
			event.preventDefault();
			event.stopPropagation();
			this.mouseCallback('dragleave', event);
		}, this))

		$tableData.on("drop", "td", $.proxy(function(event) {
			event.preventDefault();
			event.stopPropagation();
			this.mouseCallback('dragdrop', event);
		}, this))


		for (y in columns) {
			columns[y].initColumn();
		}

		/*
		 * Generate table headers.
		 */
		this.buildHeaders();

		/*
		 * Set search input area
		 */
		if (this.$tableSearchInput.length > 0) {
			this.$tableSearchInput.keyup($.proxy(function() {
				clearTimeout(this.searchTimer);
				this.searchTimer = setTimeout($.proxy(function() { this.filterData(); }, this), 600);
			}, this))

			$("#" + id + "_search_clean").click($.proxy(function() {
				this.$tableSearchInput.val("");
				this.filterData();
			}, this))
		}

		/*
		 * Disables search input if input row is active.
		 */
		this.$tableSearchInput.prop("disabled", input);

	};

};
