/*
 * Copyright (c) 2025 OopsClick LLC. All rights reserved.
 * This work is licensed under the O'Saasy License Agreement, a copy of which can be
 * found in the LICENSE file in the root directory of this project or at https://silkbuilder.com/core-license.
 */

/**
 * Returns a TabNav instance.
 * @class
 * @classdesc The TabNav Class provides properties, methods, and events to interface with the HTML generated by the ```<silk:TabNav>``` tag.
 * @constructor
 *
 * @property {Object} $tabs - The jQuery object referencing the tabs HTML tag.
 * @property {Object} $active - The jQuery object referencing the active tab.
 * @property {Array} pageList - The array containing the page's names that the TabNav manages.
 * @property {String} activePage - The active page's name being visualized.
 */
var TabsNav = function(id) {

	/* $tabs : Public Property */
	this.$tabs = undefined;

	/* $active : Public Property */
	this.$active = undefined;

	/* pageList : Public Property */
	this.pageList = new Array();

	/* activePage : Public Property */
	this.activePage = "";

	this.scrollLeft = 0;

	/**
	 * Adds a new page to the Tab Navigator.
	 * @param {String} pageName - Page's name or unique identifier.
	 * @param {String} pageTitle - Page title to show in tab.
	 */
	this.addPage = function(pageName, pageTitle) {
		var pageObject = new Object();
		pageObject["pageName"] = pageName;
		pageObject["pageTitle"] = pageTitle;
		pageObject["active"] = 0;

		var pageIndex = -1;
		for (x in this.pageList) {
			if (this.pageList[x].pageName == pageName) {
				pageIndex = x;
				break;
			}
		}
		if (pageIndex == -1) {
			this.pageList.push(pageObject);
		} else {
			this.pageList[pageIndex].pageTitle = pageTitle;
		}

	}

	/**
	 * Activates the tab related to the provided page's name.
	 * @param {String} pageName - Page's name or unique identifier.
	 */
	this.setActive = function(pageName) {
		if (pageName == undefined) return;
		this.$tabs.find(".nav-link").each($.proxy(function(index, element) {
			if (this.pageList[index].pageName == pageName) {
				this.pageList[index].active = 1;
				$(element).addClass("active");
				$(element).find(".silk-head-help").show();
				this.activePage = pageName;
			} else {
				this.pageList[index].active = 0;
				$(element).removeClass("active");
				$(element).find(".silk-head-help").hide();
			}
		}, this));

		this.$active = this.$tabs.find(".active");
		this.$tabs.scrollLeft(this.scrollLeft);

		this.relocateTab();

		this.setBarWidth();

	}

	/**
	 * Toggle the tab status of the provided page's name between active and inactive
	 * @param {String} pageName - Page's name or unique identifier.
	 * @param {boolean} mode - True to  activate and false to deactivate the tab
	 */
	this.toggleTab = function(pageName, mode) {
		if (pageName == undefined) return;
		var pageRequestedIndex = -1;
		for (i = 0; i < this.pageList.length; i++) {
			if (this.pageList[i].pageName == pageName) {
				pageRequestedIndex = i;
				break;
			}
		}

		if (pageRequestedIndex == -1) return;

		if (mode) {
			$(this.$tabs.find("li")[pageRequestedIndex]).show();
		} else {
			$(this.$tabs.find("li")[pageRequestedIndex]).hide();

			if (this.activePage == pageName) {
				if (pageRequestedIndex > 0) {
					this.setActive(this.pageList[pageRequestedIndex - 1].pageName);
					this.show();
				} else {
					if (pageRequestedIndex < (this.pageList.length - 1)) {
						this.setActive(this.pageList[pageRequestedIndex + 1].pageName);
						this.show();
					}
				}
			}
		}

		this.relocateTab();
	}

	/**
	 * Hides the tab of the provided page's name.
	 * @param {String} pageName - Page's name or unique identifier.
	 */
	this.hideTab = function(pageName) {
		this.toggleTab(pageName, false);
	}

	/**
	 * Unhides the tab of the provided page's name'
	 * @param {String} pageName  - Page's name or unique identifier.
	 */
	this.showTab = function(pageName) {
		this.toggleTab(pageName, true);
	}

	this.relocateTab = function() {

		if (this.$active == undefined) return;

		var activeLeft = this.$active.parent().position().left - 30;
		var activePosition = activeLeft + this.$active.parent().width() + 60;

		if (activeLeft < 0) {
			this.$tabs.scrollLeft(this.$tabs.scrollLeft() + activeLeft);
			this.scrollLeft = this.$tabs.scrollLeft();
			return;
		}

		if (activePosition > this.$tabs.width()) {
			this.$tabs.scrollLeft(this.$tabs.scrollLeft() + (activePosition - this.$tabs.width()));
			this.scrollLeft = this.$tabs.scrollLeft();
		}

	}

	/**
	 * Renders or re-generates the tabs' HTML.
	 */
	this.render = function() {
		var $ulElement = this.$tabs.children().first();
		$ulElement.text("");

		for (x in this.pageList) {
			var liElement = document.createElement("li");
			liElement.setAttribute("class", "nav-item");

			var aElement = document.createElement("a");
			//aElement.setAttribute("class","nav-link "+((x==0)? 'active' : ''))
			aElement.setAttribute("class", "nav-link");
			aElement.setAttribute("href", "#");
			aElement.setAttribute("data-index", x);
			aElement.innerHTML = this.pageList[x].pageTitle;

			liElement.append(aElement);
			$ulElement.append(liElement);
		}

		this.setActive(this.activePage);
	}

	/**
	 * Shows the page related to the active tab.
	 * @function
	 */
	this.show = function() {
		window[this.activePage].show();
	}

	/**
	 * Returns true if the provided page's name exists in the list of pages; otherwise, it returns false.
	 * @param {String} pageName - Page's name or unique identifier.
	 */
	this.exists = function(pageName) {
		var response = false;
		for (x in this.pageList) {
			if (this.pageList[x].pageName == pageName) {
				response = true;
				break;
			}
		}
		return response;
	}

	/**
	 * Syncs the TabsNav's width with the host header.
	 */
	this.setBarWidth = function() {
		page = this.activePage;

		if (window[page] != undefined) {
			this.$tabs.height(42);
			var headerWidth = window[page].headerWidth;
			var navWidth = window[page].$page.find(".silk-navbar").width();
			var $backBt = $("#" + window[page].id + "_backBt");
			var leftWidth = $backBt.parent().width();
			var rightWidth = $backBt.parent().parent().find(".silk-navbar-right").width()

			this.$tabs.css("margin-left", leftWidth);
			this.$tabs.width(navWidth - headerWidth - leftWidth - rightWidth - 10);
		}
	}

	/*
	 * Initializes the TabsNav
	 */
	this.initTabsNav = function() {
		this.$tabs = $("#" + id);

		if (this.pageList.length == 0) {
			this.$tabs.hide();
			return;
		}

		this.activePage = this.pageList[0].pageName;
		this.render();

		window[this.activePage].$page.find(".silk-navbar").append(this.$tabs);

		this.$tabs.children().first().on('click', $.proxy(function(e) {
			e.preventDefault();
			var $element = $(e.target);
			var index = $element.data('index');
			if (index == undefined) {
				index = $element.parent().data('index');
				if (index == undefined) return;
			}

			this.scrollLeft = this.$tabs.scrollLeft();
			window[this.pageList[index].pageName].show();

			this.setBarWidth();

			setTimeout(function() {
				silk.layoutScreens();
			}, 100);

		}, this))

		setTimeout($.proxy(function() {
			this.setBarWidth();
		}, this), 300);

	}

}
