/*
 * Copyright (c) 2025 OopsClick LLC. All rights reserved.
 * This work is licensed under the O'Saasy License Agreement, a copy of which can be
 * found in the LICENSE file in the root directory of this project or at https://silkbuilder.com/core-license.
 */

/**
 * Returns a Tile instance.
 * @class
 * @classdesc The Tile Class provides properties, methods, and events to interface with the HTML generated by the ```<silk:Tile>``` tag.
 *
 * @constructor
 * @param {String} id - Unique identifier.
 * @param {Object} option - Object containing the configuration.
 * @param {String} [option.dataSource] - Unique identifier of the dataProvider used to fill the Tile.
 * @param {String} [option.columns] - The number of tiles to define a row's columns. All tiles will be grouped in rows.
 * @param {String} [option.rowClass] - The CSS class used by the row div. This only works when the column property is more than 0.
 * @param {String} [option.content] - The HTML template used to generate the tile.
 * @param {String} [option.rendererFn] - The function that re-processes the generated tile's HTML.
 *
 * @property {Object} $tile - jQuery object referencing the Tile HTML tag.
 *
 */
var Tile = function(id, options) {

	var dataSource = ifUndefined(options["dataSource"], undefined);
	var columns = ifUndefined(options["columns"], "");
	var rowClass = ifUndefined(options["rowClass"], "");
	var content = ifUndefined(options["content"], "");
	var rendererFn = ifUndefined(options["rendererFn"], "");

	this.className = "tile";
	this.$tile;

	/**
	 * Returns the component's unique identifier.
	 * @returns {String}
	 */
	this.getID = function() {
		return id;
	}

	var eventManager = new EventManager();
	/**
	 * Load events to respond to the tiles's interactions. To set an event, use this code: ```Tile.on(<eventName>, function(){<code>})```.
	 * @param {String} eventName - The event's name.
	 * @param {function} eventFunction - The function to be triggered.
	 */
	this.on = eventManager.on;

	this.renderer = null;

	if (dataSource != "") dataSource = window[dataSource];

	this.getDataSource = function() {
		return dataSource;
	}


	/**
	 * This event is triggered before a cell item is added to the tile's elements.  If the function returns *false*, the item is ignored. Created with the ```Tile.on("filterLoad", function(index,item){})``` method.
	 * @event Tile#Event:filterLoad
	 */

	/**
	 * The method that loads the data from the DataProvider and fills the Tile.
	 */
	this.load = function() {

		/**
		 * This event is triggered before the table's content is loaded. Created with the ```Tile.on("beforeLoad", function(){})``` method.
		 * @event Tile#Event:beforeLoad
		 */
		eventManager.dispatch("beforeLoad", this.action, this.operationIndex);

		/*
		 * Clears tile's html content
		 */
		this.$tile.html("");

		if (dataSource == undefined) return;

		var rowIndex = 0;
		var currentCell = 0;
		var html = "";

		if (dataSource.className == "dataProvider") {
			/*
			 * Process SELECT action
			 */
			for (var x = 0; x < dataSource.length(); x++) {

				var item = dataSource.getItemAt(x);

				if (!ifUndefined(eventManager.dispatch("filterLoad", x, item), true)) continue;

				if (currentCell == 0 && columns > 0) {
					html += "<div class='" + rowClass + " silk-tile-row' data-index='" + rowIndex + "' >";
				}
				currentCell++;

				html += generateTile(x, item);

				if (currentCell == (columns) && columns > 0) {
					html += "</div>";
					currentCell = 0;
					rowIndex++;
				}

			}

			if (currentCell != (columns) && columns > 0) {
				html += "</div>";
			}
		}

		if (dataSource.className == "table") {
			/*
			 * Process TABLE action
			 */
			var item = dataSource.getSelectedItem();

			if (ifUndefined(eventManager.dispatch("filterLoad", 0, item), true)) {
				html = generateTile(0, item);
			}

		}

		/*
		 * Fills tile's html content
		 */
		this.$tile.html(html);

		/**
		 * This event is triggered after the table content is loaded. Created with the ```Tile.on("afterLoad", function(){})``` method.
		 * @event Tile#Event:afterLoad
		 */
		eventManager.dispatch("afterLoad", this.action, this.operationIndex);

	}

	/**
	 * Event triggered when a tile cell is clicked. Created with the ```Tile.on("click", function(item,$content,dpIndex,rowIndex,event){})``` method.
	 * @param {Object} item - The item object from the dataSource of the clicked cell.
	 * @param {Object} $content - The JQuery reference to the clicked cell.
	 * @param {Integer} dpIndex - The dataProvider index.
	 * @param {Integer} rowIndex - The cell Index.
	 * @param {Object} event - The click javascrit event object.
	 * @event Tile#Event:click
	 */

	/*
	 * Callback function connected to the JQuery mouse events.
	 */
	this.mouseCallback = function(mouseAction, event) {

		var $content = $(event.target).closest(".silk-tile-cell");

		if ($content.length == 0) return;

		var cellIndex = $content.attr("cellIndex");
		var pkValue = $content.attr("pkValue");
		var dpIndex = -1;
		var item = {};

		dpIndex = dataSource.getIndex(pkValue);
		item = dataSource.getItemAt(dpIndex);
		dataSource.setSelectedIndex(dpIndex);

		/*
		 * If mouse action is click, the row is unmarked
		 */

		/**
		 * This event is triggered when a tile cell is clicked. Created with the ```Tile.on("click", function(item,$content,dpIndex,rowIndex,event){})``` method.
		 * @param {Object} item  - The item rendering a tile
		 * @param {JQuery} $content - The jQuery object of the selected tile.
		 * @param {Integer} dpIndex - The DataProvider index of the selected tile.
		 * @param {integer} cellIndex - The cell index of the selected tile.
		 * @param {Object} event - The JavaScript click event object.
		 * @event Tile#Event:click
		 */
		if (mouseAction == 'click') eventManager.dispatch("click", item, $content, dpIndex, cellIndex, event);

	}

	/*
	 * Generates HTML data for table row
	 *
	 * @param index The dataSource index used to mark the row.
	 * @param item The row object.
	 */
	var generateTile = function(index, item) {
		var html = getTemplateData(content, index, item, this.renderer);
		if (dataSource != undefined) {
			html = html.replace("__value__", item[dataSource.getPkColumn()]);
			html = html.replace("__index__", index);
		}
		return html;
	}

	/**
	 * Add a new cell to the end of the tile.
	 * @param id The ID of the element to be added.
	 */
	this.appendCell = function(id) {
		$("#" + id).addClass("silk-tile-cell");
		$("#" + id).attr("cellIndex", this.$tile.children().length);
		this.$tile.append($("#" + id));
	}

	/**
	 * Add a new cell to the beginning of the tile's elements.
	 * @param {Integer} id The ID of the element to be added.
	 */
	this.prependCell = function(id) {
		$("#" + id).addClass("silk-tile-cell");
		$("#" + id).attr("cellIndex", 0);
		this.$tile.children().each($.proxy(function(x) {
			let $item = $(this.$tile.children()[x])
			let index = getNumber($item.attr("cellindex"));
			$item.attr("cellindex", index + 1);
		}, this));
		this.$tile.prepend($("#" + id));
	}

	// --------- Initialize Table  ---------

	this.initTile = function() {
		this.$tile = $("#" + id);

		/*
		 * Add pkValue to content template.
		 */
		var $content = $("<div></div>");

		/*
		 * Checks if content is a HTML element.
		 */
		try {
			$(content);
		} catch (a) {
			/*
			 * Content gets wraped into a div to make it into a HTML element to define the tile.
			 */
			content = "<div>" + content + "</div>";
		}

		/*
		 * If the content returns multiple elements these are wrapped in a div element defineing the tile.
		 */
		if ($(content).length > 1) {
			content = "<div>" + content + "</div>";
		}

		$content.append($(content));
		$content.children().first().attr("pkValue", "__value__");
		$content.children().first().attr("cellIndex", "__index__");
		$content.children().first().addClass("silk-tile-cell");
		content = $content.html();

		if (rendererFn != "") {
			this.renderer = window[rendererFn];
		}

		/*
		 * Add click listener to tile elements.
		 */
		this.$tile.on("click", $.proxy(function(event) {
			event.stopPropagation();

			/*
			 * Prevents triggering a click event after a text selection action.
			 */
			if (window.getSelection().toString() != "") {
				event.preventDefault();

				/**
				 * Triggered when a text has been selected in a table row. Created with the ```Tile.on("textSelection", function(text){})``` method.
				 * @param {String} text - The selected text.
				 * @event Tile#Event:textSelection
				 */
				eventManager.dispatch("textSelection", window.getSelection().toString());

				return;
			}

			/*
			 * Calls the mouse callback function
			 */
			this.mouseCallback('click', event);

		}, this))

	};

};
